### PR TITLE
Show also full item name clickboxes in GroundItems

### PR DESCRIPTION
**Pull request by deathbeam**
- Remove the possibility of having the item both highlighted and hidden
when using the highlight/hidden boxes.
- Expand the clickbox for highlighting/hiding item to it's entire name
- Left click name highlights item, right click hides item
- Highlight background when in highlighting mode of the background item
that is hovered
- In order to help in cluttered environments, bring currently hovered item name to front

Depends on: #1236

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview of new features:
peek 2018-03-20 19-12

Preview of bringing the ground item to front:
peek 2018-03-22 10-12

### CODE REVIEW

**Comment by Adam-** [comment]
I think I would prefer picking one method and then sticking with it. I am told osb/konduit use the existing implemented method, so maybe we should just stick with that.

**Comment by deathbeam** [comment]
Well the thing is this implementation is objectively better in terms of functionality. Reasons what I collected from Discord discussion earlier to why not implement it are:

* Other clients have boxes
* Personal preferences
* Usage is less obvious than when using boxes

From these 3 points I deem only 3rd point valid, and it is true, but I feel like with either Wiki page or even drawing small box in bottom left or bottom right that left click is highlight and right click is hide would be sufficient enough. I agree with @Abextm that when UI needs explanation it is not very good, that is why I added this as toogle, because even when the usage is not so obvious, the functionality is strictly better and that is worth having at least as toggle, even though I would prefer to solve 3rd point somehow and replace current functionality.

**Comment by SomeoneWithAnInternetConnection** [comment]
I'm not sure I see the "objectively better" here, especially with the "usage is less obvious" thing. Checkboxes are a UI component that basically everyone who's used a computer will be familiar with, while "left click to highlight, and right click to hide" isn't.

Something else that was brought up in that discussion on discord was that making the whole name clickable means that when there are a bunch of items on the ground, the overlap between them is going to be much more significant with the proposed UI vs the current checkboxes.

The fact that other clients have boxes **is** a valid factor, because it adds an additional layer of familiarity with the checkbox thing and, for users who are familiar with those clients, makes the proposed UI even more confusing than it already is.

This proposed UI change might have some advantages over the current checkboxes, but it certainly doesn't beat them hands down. I don't think the added confusion of breaking with the current convention is worth it here.

**Comment by deathbeam** [comment]
So after discussion in Discord, I removed the toggle and changed the new functionality just to improve old boxes functionality. This means, that you can still use the boxes, and now they are improved in a way that when you hover of the box, entire name gets highlighted, what helps in cluttered areas. The new functionality works too, so when you hover of the name, it gets highlighted too and you can left click it to highlight and right click to hide. Along with other improvements in this change, this makes the "highlighting" mode better than other clients have, what was the goal of this PR, and it is a good compromise that do not breaks the existing widely used implementation for the boxes, just enhances it with advanced functionality.

**Comment by deathbeam** [comment]
Added dependency on #1051 and with that, added also new commit that introduces bringing ground item name to front when in highlighting mode and is hovered.

**Pull request closed without merging**
