### PR TITLE
Add support for toggleable chat to fixed mode (expand to chat)

### PR DESCRIPTION
**Pull request by deathbeam**
Add support for toggleable chat to fixed mode
- Add main fixed area and fixed game canvas area to WidgetId and
WidgetInfo
- Add chatbox search and chatbox make all to WidgetId and WidgetInfo
- Rename stretched fixed mode plugin to just fixed mode
- Move the enabling of stretched fixed mode to inside of the new renamed
plugin
- Add option for enabling extended view to chat (basically toggleable
chat that draws over game canvas instead of underneath it) with same
behaviour as resizable mode chat

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview:
peek 2018-06-03 16-38

screenshot 2018-06-04 18 10 14

### CODE REVIEW

**Comment by Hydrox6** [comment]
Would it be possible to have the border sprites extend down where the chatbox is when it's not being rendered? That extra space will drive people crazy.

**Comment by deathbeam** [comment]
Split the second commit to multiple. For the border sprites, I am not really sure, I am scared that it will interfere with interface styles. Also, its like 1 px space or so, not really noticeable.

**Comment by Hydrox6** [comment]
The space is very noticeable when one frame it's black and the next it has the chatbox edge in it.

**Comment by deathbeam** [comment]
Updated the PR with added support for ESC closing the chat too. For the border sprites, I am not going to mess with them, at least not in this PR.

**Comment by deathbeam** [comment]
Updated the PR to auto-contract bank interface when chat widget opens:

peek 2018-06-03 16-38

**Comment by deathbeam** [comment]
Adding some real-life example, super nice when bossing with stretched fixed

screenie

**Comment by deathbeam** [comment]
I will reopen this maybe when we would want to implement this, I guess.

**Pull request closed without merging**
