### PR TITLE
Barbarian assault: plugin enhancements

### PR DESCRIPTION
**Pull request by BegOsrs**
Includes some features to enhance the barbarian assault minigame gameplay experience.

# Barbarian Assault Configuration

Barbarian assault plugin

### Show call change timer	
Shows time to next call change

### Chat colors
Enable game chat colors on messages announced by this plugin

### Show death times
Shows the time all penance monsters of a certain type are killed in an info box, the chat, or both

### Show duration
Displays duration after each wave and/or round

### Reward points
Gives summary of reward points in the chat after each wave and/or round

### Rewards breakdown
Gives summary of advanced points breakdown in the chat

### Show eggs loaded on hopper
Displays the amount of loaded eggs on cannon hoppers

### Highlight mode
Define the mode of all inventory highlights

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outline&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Overlay
 

### Highlight arrows
Highlights arrows called by your teammate

### Highlight arrow color
Configures the color to highlight the called arrows

### Highlight attack style
Highlights the attack style called by your teammate

### Highlight attack style color
Configures the color to highlight the attack style

### Highlight called bait
Highlights bait called by your teammate

### Called bait color
Color to highlight the bait called by your teammate

### Show runner tick timer
Shows the current cycle tick of runners

### Show number of eggs collected
Displays current number of eggs collected

### Highlight called poison
Highlights poison food called by your teammate

### Called poison color
Configures the color to highlight the correct poison food

### Highlight incorrect notification
Highlights incorrect poison chat notification

### Notification color
Configures the color to highlight the notification text

### Show number of hitpoints healed
Displays current number of hitpoints healed

### Show teammate health bars
Displays a health bar where a teammate's remaining health is located

# Ground Items

### Barbarian Assault mode
Enables or disables the mode inside barbarian assault

### Highlight eggs
Highlight egg colors on the ground when performing the Collector role

The following gif loops between the available configurations:
1. Called only
2. Highlight all
3. Highlight none
4. Barbarian assault mode off/on
Barbarian assault plugin

### Highlight bait
Highlight bait dropped on the ground when performing the Defender role

### Highlight logs and hammer
Highlight logs and hammer when performing the Defender role

# Menu Entry Swapper

### Collection bag

Swap `Look-in` with `Empty` on the collection bag inside barbarian assault

### Collector horn
Swap `Use` with `Tell-defensive` on the collector horn inside barbarian assault

### Collector eggs
Swap `Use` with `Destroy` on eggs inside barbarian assault

### Get-rewards
Swap `Talk-to` with `Get-rewards` for the Commander Connad

### Commander Connad

Swap `Talk-to` with `Get-rewards` for the Commander Connad

### CODE REVIEW

**Comment by Adam-** [comment]
It might be preferred to put this on the pluginhub, since this looks like a very wide reaching and intrusive change.

**Comment by BegOsrs** [comment]
I initially had it setup as an external plugin. But the ground items highlighting was conflicting with the existing ground items plugin, with features (and code) having to be duplicated.
While being on pluginhub, is the conflict solvable at all?

**Comment by Adam-** [comment]
Highlighting ground items in a plugin is not too hard / it is not unreasonable to duplicate the code for that. It is basically an overlay + also hooking to the spawn/despawn events I think? and is not too much code; I would recommend just duplicating that.

**Comment by BegOsrs** [comment]
Code duplication was not that bad tbh, the main issue was it conflicting with the ground item plugin
Should i ask the users to manually put all items (hammer/logs, red/green/blue/yellow eggs) on its hidden item list?

**Comment by Adam-** [comment]
You could, or if you really wanted you could just append it to the hidden item list from your plugin (it is just a config opt of the grounditems plugin you could modify).

**Comment by BegOsrs** [comment]
I'll append it to the list then, thanks. The main issue i see is the hammer/logs that are also used outside barbarian assault
What about the new menu entry swaps? Should it go into the menu entry swap plugin, or the external plugin?

**Comment by Adam-** [comment]
I don't see why they can't just be in the external plugin?

**Comment by BegOsrs** [comment]
Requested pull request as an external plugin: runelite/plugin-hub/pull/639
Closing

**Pull request closed without merging**
