### PR TITLE
Add support for JSR 250 annotations

### PR DESCRIPTION
**Pull request by CC007**
This includes the annotations `@PostConstruct` and `@PreDestroy`

### CODE REVIEW

**Comment by Adam-** [comment]
Is there existing code which can be improved with this?

**Comment by CC007** [comment]
I have been using it in my branches and added it locally when I found out I needed it. I could have included it in the pull request of  the plugin that I am working on, but I wanted to make sure that this design choice would be accepted, before having to rewrite a lot of code.

**Comment by CC007** [comment]
It could also be beneficial for other developers, since you cannot use the injected variables in constructors without it.

**Comment by Adam-** [comment]
Generally for that you just inject the variables as parameters to the constructor.

**Comment by CC007** [comment]
That is true but that would create a local variable that you dont need. Also there are multiple other uses, like when you need to use the variable `this` in a method call during the setup of your object.

**Comment by deathbeam** [comment]
You can already do that with constructor as well. And, it is generally preferred to always use constructors for injection, to create mostly immutable classes (as the constructor is private, and injected fields final).

**Comment by CC007** [comment]
When Ivwas talking about `this` in constructors, I was talking about the following: http://www.javapractices.com

This is not a problem in a method with the `@PostConstruct` annotation

**Comment by deathbeam** [comment]
Do you have better link? That one is just poiting to jp homepage

**Comment by CC007** [comment]
My bad: http://www.javapractices.com/topic/TopicAction.do?Id=252

**Comment by CC007** [comment]
An example would be if you want to add a listener for a certain class automatically. You cannot safely do this from the constructor, because as my previous link states, it is not safe to pass `this` out of the constructor. That is no problem if you do it from the method with the `@PostConstruct` annotation, because there the object has already been properly instantiated, so it is safe to use the `this` keyword.

**Comment by CC007** [comment]
Comparison: 
Compile time using maven's compile goal with this change: 15.807 s
Compile time using maven's compile goal without this change: 46.594 s

**Comment by deathbeam** [comment]
Well the thing is I don't see how it would be useful in current codebase

**Comment by CC007** [comment]
Ok, lets leave it out until it is actually used in a pull request. I'll reopen the PR then.

**Pull request closed without merging**
