### PR TITLE
Remove duplicate progress bar from XP globes

### PR DESCRIPTION
**Pull request by deathbeam**
Remove progress bar that is duplicating already existing progress bar
around XP globes. This progress bar is just taking screen space and no
other clients have it.

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Adam-** [comment]
I seem to recall this specifically being a feature request.. but I can't seem to find it. I think some people like it. Maybe a conf opt if you really want it removed?

**Comment by deathbeam** [comment]
Looks like it was added in https://github.com/runelite/runelite/pull/133. I dont think anyone ever requested that feature and having the progress bar there feels silly when there is already one.

**Comment by deathbeam** [comment]
Any update @Adam- ? Noone ever wanted this and it is useless, so can I remove it?

**Comment by deathbeam** [comment]
To not lose data, moved % to next level after skill level (in format "{level} ({progress}%)"

**Comment by deathbeam** [comment]
Closing in favour of #5856 what is solving the % issue a lot better

**Pull request closed without merging**
