### PR TITLE
Implement loot tracking for MLM

### PR DESCRIPTION
**Pull request by Jimpix-svg**

### CODE REVIEW

**Comment by Adam-** [comment]
IMO this seems out of scope for the loottracker since this is essentially a skilling resource and isn't really "loot".

**Comment by Jimpix-svg** [comment]
> 
> 
> IMO this seems out of scope for the loottracker since this is essentially a skilling resource and isn't really "loot".

There isn't currently a way to track the ores received in terms of currency. How about adding the profit into the MLM Plugin Overlay?

**Comment by Adam-** [comment]
There already is an overlay which shows what ores you found. I guess you could add price to that.

**Comment by Nightfirecat** [comment]
Per Adam's comment, this can be implemented as a price line added to the MLM ores overlay.

**Pull request closed without merging**
