### PR TITLE
Added Offenders

### PR DESCRIPTION
**Pull request by vitorebom**
Created a list of Offenders which can be updated for more offenders and updated if statements to include them. Tested and it works as intended:
- Using a special attack will add the counter
- Using another special attack on the same boss will update the counter
- Attacking one of the offenders will not reset the counter
- Using a special attack on one of the offenders will not update the counter
- Attacking another npc will reset the counter

### CODE REVIEW

**Comment by Adam-** [comment]
Do you know what this `dark core` npc is?

**Comment by vitorebom** [comment]
My bad, thought the Dark Energy Core had more Ids, just tested and both of there are not the actual NPC Corp spawns:
- DARK_CORE
- DARK_CORE_388
Only the DARK_ENERGY_CORE is the one that's supposed to be in the Offenders list

**Comment by Adam-** [comment]
I've taken this pr and made https://github.com/Adam-/runelite/commit/589a362d140b098a08316ddbed81512a2ee4b998 instead, can you test that?

**Comment by vitorebom** [comment]
On your version, specing one of the ignored npcs will still add to the counter but not remove it

**Comment by Adam-** [comment]
> 
> 
> On your version, specing one of the ignored npcs will still add to the counter but not remove it

hmm do you see why? It should be just resetting the counter and counting the new spec instead. Did you test it and get this behavior?

**Comment by vitorebom** [comment]
LN177  if (!wasSpec && IGNORED_NPCS.contains(interactingId))
With this logic the ignored npcs will only matter for normal hits that aren't specs, let me test removing the spec part completely

**Comment by Adam-** [comment]
..? My intent is if you *spec* one of the ignored npcs it still counts. Since that doesn't happen normally. Right? Except maybe for the dummy...

**Comment by vitorebom** [comment]
You are correct, and honestly, the dummy only mattered for Trailblazer as a make-do ornate pool.
I can't think of any other scenarios when we would Spec one of the Ignored NPCs

**Comment by Adam-** [comment]
If the dummy is to be included then probably the `!wasSpec` should be removed. Maybe there is some niche use for it now or in future leagues.

**Comment by Adam-** [comment]
added in aa1cd2c7ff79e368db6769d1c09f6b8a11c917d9

**Pull request closed without merging**
