### PR TITLE
Clue Scrolls: Centralize Spade Reminder Method

### LINKED ISSUE #8151: Spade reminder for strange device clues
**Problem**
It is easy to forget a spade when getting a Jorral (strange device) clue

**Describe the solution you'd like**
Leverage the existing spade-reminder functionality of the client to remind you in this situation

**Describe alternatives you've considered**

**Additional context**
I can work on this new feature

### PR DESCRIPTION
**Pull request by xDemoN**
Closes #8151

### CODE REVIEW

**Comment by Nightfirecat** [comment]
It might be worth adding some central method in the plugin to add those two lines instead of copying that code around each time.

**Comment by xDemoN** [comment]
Are you requesting that it be implemented with this commit or raised as a separate enhancement (issue)?

**Comment by Kamielvf** [comment]
He mean that, because this is duplicate code from [other clues](https://github.com/runelite/runelite/blob/ba706e98caedf745522afc1cecbc97a8b8f0801f/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java#L218~L225), the method for checking/displaying a missing spade should be generalized somewhere that it can be reused to avoid duplicate code in multiple files.

**Comment by xDemoN** [comment]
I know what he suggested. I'm asking if he would like me to work it into this commit now or raise it for a future enhancement to all of the clue plugin.

**Comment by Kamielvf** [comment]
Woops, Should be fine incorporated into this PR.

**Comment by Nightfirecat** [comment]
As a separate commit on this PR would be fine imo

**Comment by xDemoN** [comment]
Is this what you were looking for in terms of centralizing a spadeReminder method? Also, I got a little carried away on CrypticClue with spelling

**Comment by Nightfirecat** [comment]
Yes, though the commit history looks a bit weird now. I'd envision this PR being two commits--the first being adding a `static spadeReminder` method like you did and applying it where it would already be used throughout the plugin, then the second commit adding it to hot/cold clues.

**Comment by xDemoN** [comment]
I'm just going to submit a new PR because my commit history is a shitshow...

**Pull request closed without merging**
