### PR TITLE
 Add a config setting for the game's size

### PR DESCRIPTION
**Pull request by UniquePassive**
Adds a "game size" setting to the client's own config panel. I didn't want to split it up into a standalone plugin because it feels more like a completely client feature.

Unfortunately the input fields are not reset to their minimum/maximum when you go outside the bounds, because of missing functionality in the config system that I don't feel like adding because it can probably get a bit big.

Solves #390

### CODE REVIEW

**Comment by vwboy** [comment]
Just tested it out, looks good for me. I've got a suggestion, can the size be for the game window itself not counting the plugin sidebar.

**Comment by Adam-** [comment]
Would it be better to just make it resize to whatever previous size it was instead?

**Comment by vwboy** [comment]
I dont think so, input is good because like me I like to set it to 1200x800

**Comment by UniquePassive** [comment]
@vwboy I changed it so you specify the actual game's size instead of the frame since I agree with you that it's better to change the game's size than the frame's size.

One limitation is that the side panel expands inwards when the game size is big, but a simple workaround for that is just to have the side panel open all the time.

**Comment by vwboy** [comment]
@UniquePassive , doesnt seem to be working for me :/ , the game size is 1200x800, but it should be 1400x800. Am I doing something wrong ?

https://gyazo.com/5318f8de7e64c71efe0431269a623d8a

**Pull request merged**
