### PR TITLE
Add music list plugin with filtering and search

### LINKED ISSUE #8473: add ability to hide musics that aren't unlocked yet.
**Is your feature request related to a problem? Please describe.**
Yes because you can't currently see easier what songs you have unlocked yet and which you have and rather you need to scroll through 600 songs to see which you haven't unlocked yet.

**Describe the solution you'd like**
Similar button to quest page but it would hide the unlocked songs and leave only the ones that you haven't unlocked.

**Describe alternatives you've considered**
hides the ones that you haven't unlocked yet and leaves the ones that you have.

**Additional context**
Search to search the songs that you want to play.

### PR DESCRIPTION
**Pull request by Atrolantra**
Can now filter the music list on Unlocked/Locked/All in the same way as already exists for quests.
Also added search functionality for music.
Closes #8473

### CODE REVIEW

**Comment by Adam-** [comment]
Do we want this?

**Comment by ShaunDreclin** [comment]
The search would be very nice for the new music clues, it's very fiddly trying to scroll to the right track

Would the filtering have the same issue as #8390?

**Comment by rherms** [comment]
Also fixes https://github.com/runelite/runelite/issues/8601

**Comment by Adam-** [comment]
This functionality was added in #8779

**Pull request closed without merging**
