### PR TITLE
Properly shutdown everything on window close

### PR DESCRIPTION
**Pull request by deathbeam**
- Properly shutdown applet on window close
- Properly remove system tray icon on close
- Shutdown executorService on shutdown
- Stop all plugins on shutdown

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Adam-** [comment]
This makes it so it takes ~5 seconds to close the client.

**Comment by deathbeam** [comment]
Most of that time is shutdown time of the applet, I cannot do anything about it.

**Comment by deathbeam** [comment]
!22 in internal needs to be merged before I can continue working on this @Adam-

**Comment by deathbeam** [comment]
Updated the PR to instead of Applet#destroy call GameEngine#shutDown()

**Pull request merged**
