### PR TITLE
Drop tracker plugin

### PR DESCRIPTION
**Pull request by yoyo421**
This is a drop tracker plugin, this plugin use the settings from the ground item plugin and can show drops in 2 ways:
one without the settings = 
image
one with the settings = 
image

in the ground setting i put hide things under 100 gp, and didn't change anything else.
it is also work with the highlight items & hide items as well.

in the config file =
image
you can set if you want to follow the settings from the ground config.
hide drops if they are 0 gp.
the limit on how many drops the tracker will track before deleting them.
the ability to remove drops with shift + clicking on them.

The are 2 problems with the plugin:
first the plugin can't track on npcs like zulrah / vorkath / kraken because the drop is not where they are standing.
sec is if in the same tick the npc despawn as item spawn under him it will count it as the npc drop.

*Edit*: When i have time (probably on the weekend) I will work on fixing the tracker for those bosses.

*I did not knew that woox was working on similar thing, sry woox

### CODE REVIEW

**Comment by yoyo421** [comment]
@MESLewis and how I do that (I'm not very familiar with how to work with github)

**Comment by MESLewis** [comment]
[Here](https://github.com/mockito/mockito/wiki/Using-git-to-prepare-your-PR-to-have-a-clean-history) is a guide that can help. The basics are to do an interactive rebase.

**Comment by Juzzed** [comment]
you can run checkstyle localy. See:
https://github.com/runelite/runelite/wiki/Checkstyle-with-IntelliJ-IDEA

**Comment by yoyo421** [comment]
know*, not now

**Comment by yoyo421** [comment]
@Juzzed It didn't work, maybe next time

**Comment by Nightfirecat** [comment]
```
git reset --soft <commit-SHA-before-your-first-commit>
git commit
```

The above will condense all of your commits into one. Otherwise, you can do the following if you want to reorder or split commits rather than commit in one go.

```
git rebase -i <commit-SHA-before-your-first-commit>
# follow directions from there
```

**Comment by yoyo421** [comment]
@Nightfirecat I'm afraid to do git reset and all that stuff because i already lost 2 projects from messing around with git.

**Comment by Nightfirecat** [comment]
`git checkout -b branch-backup` first so you don't lose it? :)

**Pull request closed without merging**
