### PR TITLE
tile indicators: fix phantom clicks

### LINKED ISSUE #9179: Tile Indicators Highlight hovered tile phantom clicks
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Clicking on a wall with void behind or clicking out of range doesn't produce any input until the cursor hovers a tile in range.

**To Reproduce**
1. Enable **Tile indicators** and **Highlight hovered tile**
2. Go to POH and walk all the way to the border to see the void
3. Click the void
4. Move the cursor onto a tile in range
5. Now the click in the void registers, producing unexpected behavior.

**Expected behavior**
When clicking the void, nothing at all should happen, resulting in the same behavior as not having the Highlight hovered tile enabled.

**Screenshots**
RuneLite_012L3rnVZS

**Environment (please complete the following information):**
 - OS:  Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.0

### PR DESCRIPTION
**Pull request by Hydrox6**
Closes #9179

### CODE REVIEW

**Comment by deathbeam** [comment]
This is also used in PartPingOverlay

**Comment by Hydrox6** [comment]
Pinging doesn't cause any phantom clicks, so adding it there would be unneeded

**Comment by deathbeam** [comment]
Did you actually tested that? Because it's using literally the same code

**Comment by Hydrox6** [comment]
I went and tested it, and it doesn't cause Phantom clicks

**Comment by deathbeam** [comment]
Well, it should. You need to actually be in party, or remove the checks around, and also receive pings, or remove that check as well, to verify it.

**Comment by Adam-** [comment]
fixed in a3e9b790dd92d8fe7eb12d35de6db250f1f78328

**Pull request closed without merging**
