### PR TITLE
fix(timetracking): s/Giant/Big/g

### PR DESCRIPTION
**Pull request by levex**
It's called a Big Compost Bin:

https://oldschool.runescape.wiki/w/Big_Compost_Bin

NB: I didn't want to replace the variable names, just renamed what is displayed on the UI.

### CODE REVIEW

**Comment by levex** [comment]
Hi @Nightfirecat can we merge this?

**Comment by levex** [comment]
ping @Nightfirecat ?

**Comment by Adam-** [comment]
All of the enum names which reference the giant compost bin should also be renamed.

**Comment by levex** [comment]
Thanks @Adam- I'll do that.

**Comment by levex** [comment]
Done @Adam- @Nightfirecat

**Pull request merged**
