### PR TITLE
fix prayer enhance timer

### PR DESCRIPTION
**Pull request by winterdaze-rs**
the current timer starts at 4 mins 50 seconds, but the enhance wears off at the 15 second warning. this means the actual timer is 4 mins 35 seconds. [reference](https://imgur.com/a/NUMe7)

### CODE REVIEW

**Comment by Kamielvf** [comment]
This looks to me like a bug.. might be worth reporting to jagex.

**Comment by Adam-** [comment]
It looks like it was only changed once before: https://github.com/runelite/runelite/commit/39206502462852b1d3a69041a9b12b77c207c7f1. This seems like a drastic adjustment...

**Comment by winterdaze-rs** [comment]
I'm certain as of right now that it's 4 mins 35 seconds consistently, not sure why it would have changed from its previous length though

**Comment by MagicfTail** [comment]
it looks like they removed the "your prayer enhance is about to expire" message and just had it run out at that point instead

**Comment by l2-** [comment]
prayer enhance (+) timer is 290. [wiki](http://oldschoolrunescape.wikia.com/wiki/Prayer_enhance_(%2B)?diff=5906785&oldid=3553472)
[gif](https://streamable.com/1tci3) as you can see the new timer falls short exactly 15 seconds which shows this pr is invalid

**Comment by winterdaze-rs** [comment]
well we don't know who made that wiki edit--it was added to the wiki the same day the first prayer enhance fix was merged into RuneLite. [new timer gif](https://imgur.com/a/hOnxE) looks like it's accurate to about 2 seconds which imo is better than being 15 seconds off

**Comment by winterdaze-rs** [comment]
the only other thing I could think of is maybe the vespula enhances are different from the other raids enhances, since it doesn't award points towards the cap? but that would be odd if they made enhances have inconsistent timers with other enhances :/

**Comment by Kamielvf** [comment]
I think it just works to the nearest minute and then adds x minute duration.. so it's most likely not consistent.

**Comment by winterdaze-rs** [comment]
[mutadile enhance gif](https://imgur.com/a/wfwIN) is also accurate to ~2 seconds. also check out the number of points I had lol

**Comment by l2-** [comment]
How is it even possible i can reproduce 290 seconds enhance and you can reproduce 275 seconds enhance. The enhance in my gif was an enhance (+) from tekton. Honestly from all the raids im doing i've yet to see a 275 seconds enhance. 290 seconds is accurate within a second for me so far.

**Comment by winterdaze-rs** [comment]
I am not sure, the enhances I was using are also enhance (+) from vespula and muttadile respectively. tekton enhances vs enhances you make from planting buchus vs muttadile/vespula enhances should all be the same, right? and the timer doesn't scale by team size? it is quite odd

**Comment by Kamielvf** [comment]
I tried to say earlier, the timers might be not consistent since it works towards the nearest minute when you're close to it. This would result in the enhance lasting longer because you sip it at say 0:50 and the timer does 1:00 + enh timer.

**Pull request merged**
