### PR TITLE
ZoomConfig: Update Bounds for Ctrl Zoom Value

### PR DESCRIPTION
**Pull request by rlw0014**

### CODE REVIEW

**Comment by raiyni** [comment]
This is needed to prevent the client from crashing at certain window sizes

**Comment by Nightfirecat** [comment]
What's the purpose of this commit/PR? Why should this be merged?

**Comment by Adam-** [comment]
He spoke on discord and said max should be the inner limit max, which is what the code bounds the config to.

**Comment by Adam-** [comment]
The code which uses this value is: `Ints.constrainToRange(zoomConfig.ctrlZoomValue(), zoomConfig.OUTER_LIMIT_MIN, INNER_ZOOM_LIMIT);` which bounds it to -400 to 1004. This should match the `@Range`, so one of them is wrong.

**Pull request merged**
