### PR TITLE
Alternate keybind option for Ground Item priority UI

### PR DESCRIPTION
**Pull request by cherrydipped**
Addresses user issue #3826  . Added an option in the Ground Item plugin config menu to allow for users to elect to switch from using L-Alt, to L-Shift to activate the Item Priority UI (The +/- signs brought up when pressing alt).

### CODE REVIEW

**Comment by Adam-** [comment]
#3854 is working on configurable keybinds, so this should just wait for that.

**Comment by cherrydipped** [comment]
@Adam- Yeah, I did this before he even started his projecct. I'm planning on waiting to implement it into a couple of different plugins. I really only did this because people complained about misclicking and turning the camera.

**Comment by Nightfirecat** [comment]
Not sure why this issue was closed; it's still an issue. @cherrydipped, please feel free to re-open.

**Comment by Nightfirecat** [comment]
@Caia-OSRS #3826 is still open for tracking this issue, so we will still address it at some point.

**Pull request closed without merging**
