### PR TITLE
Disable screenshots on login screen

### PR DESCRIPTION
**Pull request by GibsDev**
First time contributing to a project on GitHub. Hopefully I'm doing this correctly. I definitely did not automatically upload a fully filled out login screen to imgur by accident to come up with this idea...

### CODE REVIEW

**Comment by SomeoneWithAnInternetConnection** [comment]
Is there any case where someone would actually *want* to be taking a screenshot of the login screen? It seems like a good idea to just never allow screenshots to be taken while the client's at the login screen.

**Comment by Adam-** [comment]
I agree, I would just unconditionally block login screen screenshots.

**Comment by GibsDev** [comment]
Seems that playing around with my configuration for line separators made the diff check a bit messy...

**Comment by GibsDev** [comment]
That took way more git voodoo then I have ever played with before, but it is finally done

**Pull request merged**
