### PR TITLE
Ancient staff prayer bonus

### PR DESCRIPTION
**Pull request by lund8619**
Add ancient staff to prayer items list

### CODE REVIEW

**Comment by lund8619** [comment]
Could one of the admins please unblock me from the dev channel? I'm having some git trouble I'd really like to ask about in there.

**Comment by lund8619** [comment]
Discord name is IronMosiah.

**Comment by lund8619** [comment]
This is worse than what I imagine playing as a UIM would be. So... permban from the dev page?

**Comment by Nightfirecat** [comment]
It looks like you just need to rebase and drop the first three commits. Something like `git rebase -i HEAD~4` and marking the first three commits as `drop` should do the trick.

**Comment by lund8619** [comment]
Awesome. I was able to rebase and then had to do a force-push. When reviewing the code, everything looks the way I want it. Now I can't reopen because I did a force-push I guess? Do I have to make a new PR since I did a force-push?

**Comment by Nightfirecat** [comment]
You can do that, or reset to the previous state, force-push, re-open the PR, then repeat the steps you followed. At this point, opening a new PR is probably easier.

**Pull request closed without merging**
