### PR TITLE
Add Shantay buy-pass option, switch Travel and Trade swapping order.

### PR DESCRIPTION
**Pull request by inewman**
In reference to https://github.com/runelite/runelite/issues/1821

### CODE REVIEW

**Comment by SoyChai** [comment]
I love this swap, but it definitely shouldn't be enabled under the `Travel` setting, since this is a purchase action and not a transportation one.

**Comment by inewman** [comment]
Thanks for your input! I figured it was close enough to the Phasmatys and Al-Kharid gate fees to qualify, but I can see why someone might think it would differ.

Should it be given its own config option or is there an existing category that would be better suited?

**Comment by SoyChai** [comment]
I was leaning towards the `Trade` category, but I see that Shantae actually has a Trade option already, so I think a separate `Buy Shantae pass` category would be fine.

**Comment by inewman** [comment]
Done. Yeah, if you check the issue you'll see that I opted to reorder the actual swaps for Trade and Travel to produce the expected behavior.

**Comment by Adam-** [comment]
Since this appears to have begun relying on swapping order now we should probably add a test for it. Otherwise it will probably get lost quickly.

**Comment by inewman** [comment]
I'm not sure how to set up a test 😥

**Comment by deathbeam** [comment]
Closing as this is very old PR now and has a lot of merge conflicts, reopen if you want to re-implement it.

**Pull request closed without merging**
