### PR TITLE
Slayer counter synchronization improvement for certain tasks

### LINKED ISSUE #1046: Monsters left on slayer task completely useless when barraging
When bursting/barraging slayer monsters you stack them and kill multiple at the same time. This results in multiple monsters dying in the same tick, giving only one slayer xp drop, and the counter only counting one monster dying. This throws it off, making i unusable when bursting slayer tasks.

### PR DESCRIPTION
**Pull request by iguaan**
Starting to fix #1046, currently it's pretty basic only working for Suqah, Dust Devils and Smoke Devils. More tasks could be added, but that requires creating exceptions for each task and each NPC type.

### CODE REVIEW

**Comment by deathbeam** [comment]
You can most likely get data for this from npc_health.json already, no need to specify them.

**Comment by deathbeam** [comment]
Hmmm, why that happens. Isnt the slayer xp based on HP?

**Comment by MagicfTail** [comment]
It's probably the xp multiplier, someone created an issue yesterday with the formula

**Comment by deathbeam** [comment]
Oh, so probably using npc health and then adding multipliers to affected monsters would work.

**Comment by deathbeam** [comment]
Yeah, well I meanth something similar here. But i guess the multipliers are different

**Comment by iguaan** [comment]
Issue is none of the slayer superiors are defined in npc_health, Since it's under target and being ignored, I dont think I can PR for it.

`"Crushing hand_45": 55,
  "Chasm Crawler_68": 64,
  "Screaming banshee_70": 60,
  "Giant rockslug_86": 77,
  "Cockathrice_89": 95,
  "Flaming pyrelord_97": 126,
  "Monstrous basilisk_135": 172,
  "Screaming twisted banshee_144": 220,
  "Malevolent Mage_162": 172,
  "Insatiable Bloodveld_202": 380,
  "Vitreous Jelly_206": 190,
  "Cave abomination_206": 130,
  "Vitreous warped Jelly_241": 220,
  "Abhorrent spectre_253": 275,
  "Choke devil_264": 300,
  "Insatiable mutated Bloodveld_278": 411,
  "Nuclear smoke devil_280": 240,
  "King kurask_295": 420,
  "Nechryarch_300": 320,
  "Night beast_314": 640,
  "Repugnant spectre_335": 390,
  "Greater abyssal demon_342": 400,
  "Marble gargoyle_349": 270"Crushing hand_45": 55,
  "Chasm Crawler_68": 64,
  "Screaming banshee_70": 60,
  "Giant rockslug_86": 77,
  "Cockathrice_89": 95,
  "Flaming pyrelord_97": 126,
  "Monstrous basilisk_135": 172,
  "Screaming twisted banshee_144": 220,
  "Malevolent Mage_162": 172,
  "Insatiable Bloodveld_202": 380,
  "Vitreous Jelly_206": 190,
  "Cave abomination_206": 130,
  "Vitreous warped Jelly_241": 220,
  "Abhorrent spectre_253": 275,
  "Choke devil_264": 300,
  "Insatiable mutated Bloodveld_278": 411,
  "Nuclear smoke devil_280": 240,
  "King kurask_295": 420,
  "Nechryarch_300": 320,
  "Night beast_314": 640,
  "Repugnant spectre_335": 390,
  "Greater abyssal demon_342": 400,
  "Marble gargoyle_349": 270`

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/resources/npc_health.json

**Comment by iguaan** [comment]
Since this now utilises npc_health, it also depends on #2183, because with HP being set at incorrect value, it will always count it as two kills, plus it'd be unable to retrieve the health for superiors.

I think this is mostly done for now and ready for a review.

**Pull request closed without merging**
