### PR TITLE
Make background color of panel components configurable

### LINKED ISSUE #11435: Infobox Opacity
Screenshot (138)

It would be nice to have the option to increase the opacity of infoboxes to be solid so that they are easier to see when placing them at various different places on the client.

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
Closes #11435 

w28Qor6T6e

### CODE REVIEW

**Comment by TheStonedTurtle** [comment]
I have removed the Units (`/255`) from this option per discord feedback.

6sQDsmMPgb

**Comment by deathbeam** [comment]
Imo it would be better if it would be simply color picker, and apply to all panel overlays. Adding configuration option specifically for infoboxes just because someone wants to see them better over their inventory is pretty dumb reason imo.

**Comment by TheStonedTurtle** [comment]
I've updated this PR to use a Color picker for the infobox background colors

image

I'm not sure how to apply the RuneLite config color to all PanelComponent background colors (that aren't being manually set by a plugin like MLM sack) so i added this just for info boxes.

**Comment by makingcomment** [comment]
I don't understand why the opacity configuration had to be _replaced_ with the background color configuration in this PR. Why not add both?

**Comment by TheStonedTurtle** [comment]
The color picked includes an Alpha (opacity) option.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayPanel.java#L65

**Comment by TheStonedTurtle** [comment]
> 
> 
> https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayPanel.java#L65

How would I access the RuneLite config inside this method?

**Comment by TheStonedTurtle** [comment]
PR has been updated so OverlayPanels get the color from the RuneliteConfig.

image

I've left this as a separate commit so its easier to review

**Comment by deathbeam** [comment]
Pushed small change, can you retest @TheStonedTurtle

**Pull request merged**
