### PR TITLE
Skill Calculator: Wyrm Agility XP and icons

### PR DESCRIPTION
**Pull request by evilgenious448**
- Update Colossal Wyrm Basic and Advanced XP to match [09/10/2024](https://secure.runescape.com/m=news/a=13/wintertodt-updates--varlamore-drop-rates?oldschool=1) game update.
- Update Shayzien and Colossal Wyrm icons to match the formats used for other courses with multiple "tiers" (same icon for all tiers).

### CODE REVIEW

**Comment by evilgenious448** [comment]
Oh, I wasn't expecting the Herblore stuff to be included in this PR also, not sure how I did that. 
Hope it's not an issue.

**Comment by YvesW** [comment]
You can probably just drop those herblore commits on this branch and force push.

Also, one of those herblore commits might have failed PMD/checkstyle? Idk, the github app is shit, but there's a red X at least. You should probably take a look at it.

**Comment by evilgenious448** [comment]
> Also, one of those herblore commits might have failed PMD/checkstyle? Idk, the github app is shit, but there's a red X at least. You should probably take a look at it.

Yeah I messed up the ordering of the skill actions, I fixed it in the commit after it.

**Comment by evilgenious448** [comment]
@YvesW Nice, dropped the herblore commits from this one! Thanks for showing me the Git Log in IntelliJ. Didn't know that was a thing before, but its super useful. 👍

**Pull request merged**
