### PR TITLE
entityhider: make hidden entities not occupy the tile they're on

### LINKED ISSUE #1979: If there is entity under hidden entity the entity will be hidden as well
When selected to **not** render players, if there is an NPC underneath of them the NPC will also not render.

### PR DESCRIPTION
**Pull request by devLotto**
Fixes #1979 

Only works internally until it's merged.

Result: https://gfycat.com/EverlastingLargeAlbino

### CODE REVIEW

**Comment by AppleSocks** [comment]
A large part of competitive castlewars is being able to quickly rightclick explode/bucket/tinder barricades underneath players the tick after they're set. If this is merged, players could toggle the "Hide Players" option to make these actions a leftclick, massively reducing the skillcap. 

Instead, maybe `shouldDraw` could return true if this NPC is in a blacklist of NPC ids? (inside a mixin so its not editable?)

**Comment by devLotto** [comment]
I might be able to make it so nothing is hidden if you're inside Castle Wars. Would that be fine?

**Comment by AppleSocks** [comment]
If you figure that'd be less expensive or hacky then yeah that'd work

**Comment by devLotto** [comment]
Updated so that it disables the hiding if you're in a Castle Wars game.

**Pull request merged**
