### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by tr33s**
Refactor FriendManager + Name

### CODE REVIEW

**Comment by devLotto** [comment]
Is there a reason for importing it into the api (RSFriendManager), as it isn't used?

**Comment by tr33s** [comment]
@devLotto It's for a plugin, I was just doing the refactoring separately.

**Comment by devLotto** [comment]
I see 👍

**Comment by devLotto** [comment]
What's the plugin you're making, and are you going to contribute it later on?

**Comment by tr33s** [comment]
@devLotto I want to make it so you can shift right click menu to add/ignore someone.

**Comment by devLotto** [comment]
Hmm.. I see. Is it possible you can leave the imports out until you contribute that feature? (but leave the Exports)

**Pull request merged**
