### PR TITLE
Add theoretical boost to item stat overlay

### PR DESCRIPTION
**Pull request by bmoyer**
This addresses the feature request made in issue #455.

When the Item Stats plugin is set to 'Relative' or 'Both', this change causes the 'theoretical' boost amount to be displayed along with the relative boost amount. I think it makes sense to display this if the user wants to see the relative boost, but let me know if you'd prefer it to be a standalone toggle which can be used with either 'Relative', 'Absolute', or 'Both'.

Using 'Relative':
image

Using 'Both':
image

Wasn't sure on the best text formatting, I think this is clear enough but I am happy to change it if there are any better suggestions.

### CODE REVIEW

**Comment by Abextm** [comment]
I would like to see a toggle on this. I would use the following states:

| | |
|--|--|
|Relative|+5|
|Relative\|Theoretical|+5/10|
|Absolute|100|
|Absolute\|Relative|+5 (100)|
|Absolute\|Relative\|Theoretical|+5/10 (100)|

If you can think of a good way to include a Absolute|Theoretical feel free to do so, but I cannot come up with a way that would not be confusing.

**Comment by bmoyer** [comment]
Sounds good. Do you think it would make sense to just expand the drop-down menu to have each of those combinations then? I also don't see a good way to include Absolute|Theoretical.

**Comment by Abextm** [comment]
If we had all of the Absolute|Theoretical I would change it to check boxes, but since Abosolute|Theoretical is an invalid state I would just add a bit to the enum to expand the drop-down.

**Comment by bmoyer** [comment]
As per our discussion on Discord, I've removed the original drop-down and implemented each mode as a checkbox instead, with the output you suggested. So any permutation of Absolute, Relative, and Theoretical modes can be used. Here's an example of the output for every permutation.

| Absolute  | Relative | Theoretical | Output Example  |
| ------------- | ------------- | ------------- | ------------- |
| 0  | 0 | 0 | |
| 1  | 0 | 0 | 100 Run Energy |
| 0  | 1 | 0 | +0 Run Energy |
| 0  | 0 | 1 | /10 Run Energy |
| 1  | 1 | 0 | +0 (100) Run Energy |
| 0  | 1 | 1 | +0/10 Run Energy |
| 1  | 0 | 1 | 100 (/10) Run Energy |
| 1  | 1 | 1 | +0/10 (100) Run Energy |

Let me know if you think this works or any formatting should be different.

**Comment by Abextm** [comment]
Thinking about it more, I would prefer Absolute|Theoretical to `/+-10 (100)` so that the absolute is always added in the parenthesis, and order is always the same.

**Comment by bmoyer** [comment]
Done. Also made it so that the `+` after the `/` will always show for positive boosts.

**Pull request merged**
