### PR TITLE
Improve boss respawn timer

### PR DESCRIPTION
**Pull request by Alexsuperfly**
Improve the accuracy of the boss respawn timer by starting it when the boss despawns.
Added KQ boss to boss list per request #2630
Fixed Vet'ion timer to start after 2nd phase death instead of first per request #3017

### CODE REVIEW

**Comment by Adam-** [comment]
The adding of the KQ should be in a separate commit from the changing to use despawn.

**Comment by Adam-** [comment]
@MagicfTail brought up in Discord that this would cause the timer to go off when the npc despawns for any reason... so this is probably actually broken.

**Comment by MagicfTail** [comment]
Kraken, Thermy, Cerb, and Deranged Arch also need to have their respawn timers changed as they were timed after the old system. See #2838

**Comment by Adam-** [comment]
I tested this, and it did not start the timer after the first phase.

**Comment by Alexsuperfly** [comment]
i made sure to test that because i thought the same thing

**Pull request merged**
