### PR TITLE
emojis: add moyai

### PR DESCRIPTION
**Pull request by masonhobbs**
Added the moyai emoji just because I felt like he needed to be in. Triggered via "B|" since its kinda similar to expressionless.

Here's how it looks in-game:
image

### CODE REVIEW

**Comment by masonhobbs** [comment]
add moyai 🗿

**Comment by masonhobbs** [comment]
add moyai 🗿

**Comment by PacosMartini** [comment]
add moyai 🗿

**Comment by masonhobbs** [comment]
mark as spam but no hiding from moyai 🗿

**Comment by masonhobbs** [comment]
for real though whats up with the delay this is a simple glance and approve PR

**Comment by Nightfirecat** [comment]
Because we haven't discussed whether we want to add this emoji, simple as that. It's not about whether it's a big change, it's about whether we want this change (which again, we haven't discussed/decided)

**Comment by masonhobbs** [comment]
I don't know what there is to discuss, I mean ye got eggplant in there, what kind of questions come with including this? This was a fun side-project to get a hang of modifying RL source but if its this much red tape, that's a serious headache.

**Comment by masonhobbs** [comment]
one line PR with no updates - exactly my point. Can't even imagine how much trouble it must be to contribute for a complicated PR that requires updates. Dumb.

**Comment by masonhobbs** [comment]
just dont ask for moyai

**Pull request closed without merging**
