### PR TITLE
Convert item variations to json and add support for trident, slayer helm and same-name different id items

### PR DESCRIPTION
**Pull request by deathbeam**

### CODE REVIEW

**Comment by deathbeam** [comment]
@raiyni can you check this please?

**Comment by Abextm** [comment]
Shayzien armour should probably be excluded from this

**Comment by deathbeam** [comment]
Well, things like (t) dhides are included, and this sort of falls into same category. And as it is optional to use, simply supporting it sort of makes sense. And for shift-click config if for some reason you want to configure shift-click action for it, it makes sense too it will apply to all shayzien armour

**Comment by Abextm** [comment]
I would expect that it doesn't alias completely different items.

**Comment by deathbeam** [comment]
Well they are not different, just weaker variations of it (if you mean the one that is used for shamans)

**Comment by Abextm** [comment]
Should it alias a normal defence potion to a super defence potion?

**Comment by deathbeam** [comment]
Dumper is now here: <https://github.com/deathbeam/runelite/tree/item-variations-dumper>. I am not removing shayzien armour because 1. too annoying to filter, 2. it is already in master

**Pull request merged**
