### PR TITLE
Raids plugin: Display whitelisted layout/rotation in green

### PR DESCRIPTION
**Pull request by Kamielvf**
image

This will show rotations and layouts in green on the overlay if they are whitelisted ones.

### CODE REVIEW

**Comment by Kamielvf** [comment]
@deathbeam I've replaced the method and it doesn't search for partially matching rotations anymore (since this is basically useless, those raids will be skipped anyway). This fixes the bug but requires me to also change the overlay rendering code due to it no longer returning an amount of bosses.

**Comment by deathbeam** [comment]
Can this be merged now @Adam- ?

**Comment by deathbeam** [comment]
Needs rebase?

**Comment by deathbeam** [comment]
This looks quite abandoned, closing. Reopen when it will be needed

**Pull request closed without merging**
