### PR TITLE
Add plugin to display high alch values in price checker

### LINKED ISSUE #8502: High Alch Price on Built-in Price Checker
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...] Not really a problem per se but it would be nice if the in game price checker (accessed on the gear tab) could show alch value as well as ge value

**Describe the solution you'd like**
I would like to request to have the high alch value of items added to the aforementioned interface as well as the GE value. (could possible be a toggle between the two - and would probably need a toggle on off for those that don't want it)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered. I don't know of an alternative solution. Possibly making loot tracker show alch value (this seems to have been done before but not implemented into the build.) but i don't think that would be a  good fit since you couldnt just pull loot out of your bank and check its combined alch value.

**Additional context**
Probably more helpful for ironmen than it would be for mains.

### PR DESCRIPTION
**Pull request by SuperRonJon**
closes #8502 
This is my first time working with this project so let me know any issues or things that can be improved
This plugin will display the High Alchemy value next to the GE value on the built in Guide Price checker.

The plugin will show the High Alch value for each item, alongside the total High Alch value for all items in the price checker.

Without plugin
java_2019-04-15_12-37-28

With plugin
java_2019-04-15_12-37-08

The display will change automatically when toggled on/off with the Price Checker open

### CODE REVIEW

**Comment by JacobThompson** [comment]
Yes this is a great idea.

**Comment by raiyni** [comment]
This cleaned up-ish can be cherry picked here.

https://github.com/raiyni/runelite/commit/a41d7cad56ebd182c8dcec7c1486703019adb284

Maybe include a config and resetting to default. Default might not be needed because it recalculates on container change. Maybe that can be triggered?

**Comment by KasparRosin** [comment]
Is there an option for this in the current runelite version and that's why this wasn't merged? Just found this pull request from an early reddit post.

**Comment by whartd** [comment]
@SuperRonJon Are you still around / would you be willing to touch this up if it needs to be updated? Or should someone else take over it?

**Pull request closed without merging**
