### PR TITLE
Added the Skeletal Wyvern stairs to the Agility Shortcut plugin

### LINKED ISSUE #6415: Add the Skeletal Wyvern stairs to the Agility Shortcut plugin
image

### PR DESCRIPTION
**Pull request by MaxBartlett**
Closes #6415 

Image below:

### CODE REVIEW

**Comment by MaxBartlett** [comment]
> You're going to want to have each individual addition for the agility shortcuts in its own branch, e.g. A branch and pull request for the Burgh De Rott Shortcut, a branch and pull request for the Taverly shortcut, etc. if you're solving one issue.

Just realized this mistake - working on it atm 👍

**Comment by Adam-** [comment]
If all of the commits are related to one issue (adding missing shortcuts) I don't see anything wrong with 1 pr with separate commits.

**Comment by critzd** [comment]
Ah, my bad then. I was going off of what I was told in discord.

**Comment by MaxBartlett** [comment]
@Adam- @critzd Thank you for being patient with me, I'm honestly still pretty new to the ins and outs of version control. This should look better at #6420

**Pull request closed without merging**
