### PR TITLE
Remove pet from minimap in barrows

### PR DESCRIPTION
**Pull request by Berry-95**
Fixes: #6672
Also adds a helper function in NPC called isPet, which returns true if an NPC is a pet.
I could be modify this to simply hide NPCs with undefined combat level if my NPC isPet method is not desirable.

### CODE REVIEW

**Comment by Adam-** [comment]
There is a flag for whether or not npcs show on minimap, maybe we could use that instead?

**Comment by Berry-95** [comment]
> There is a flag for whether or not npcs show on minimap, maybe we could use that instead?

I was thinking about that, I'd have to test that they're not all set to false in barrows though, as you're not supposed to see them on the vanilla minimap.

**Comment by Adam-** [comment]
It is already exported as `isMinimapVisable` so its worth checking

**Comment by Berry-95** [comment]
> It is already exported as `isMinimapVisable` so its worth checking

Not got membership at the moment, so might be a while before I can confirm it myself.

**Comment by Berry-95** [comment]
I'm going to do some testing now that I've got some time, however my only pet is a cat...
Thinking of fiddling with isMinimapVisible or confirming all NPCs in Barrows have a combat level, so that a pet (with no combat level can be hidden).
Any other potential solution suggests/ideas worth testing feel free to let me know.
I'll also be investigating #6918 further.

**Pull request closed without merging**
