### PR TITLE
Actually add special case for Grotesque Guardians

### PR DESCRIPTION
**Pull request by MagicfTail**

### CODE REVIEW

**Comment by Adam-** [comment]
Has anyone tested this?

**Comment by MagicfTail** [comment]
Tested and actually works this time

**Comment by Kamielvf** [comment]
So is `DUSK_7888` completely redundant at this point here?

**Comment by MagicfTail** [comment]
It looks like it isn't necessary, but same as with normal gargoyles, he changes into another npc during his death animation, and gargoyles have both ID's in there. So i would keep it there unless someone can confirm it isn't necesserary for gargoyles either.

**Pull request merged**
