### PR TITLE
Improves Idle Notifier Plugin

### PR DESCRIPTION
**Pull request by Whired**
Maybe a discussion point, but I've removed the ScheduledFuture / interval as we have access to knowing when a character goes from animation to idle, we just need to know which animations to subscribe to.

### CODE REVIEW

**Comment by Adam-** [comment]
This is what I had originally thought, but @abelbriggs1 says in the event of lag the animations will stop playing and erroneously trigger the notification, which is why it is how it is currently. I don't know if it is really that much of a problem or not though.

**Comment by Whired** [comment]
@Adam- @abelbriggs1 WAIT_DURATION can still be modified to account for lags /etc - this only removes the loop that is checking for changes instead of subscribing to them

**Comment by Adam-** [comment]
This looks to me like this wouldn't work if you started some action and quickly finished, prior to DURATION, and then didn't do anything else (or stand near anything else) that caused the animation of anything to change.

**Comment by Whired** [comment]
Aside from `WAIT_DURATION` being changed to 0, Abel's logic has not been modified

There was a loop checking for `client.getLocalPlayer().getAnimation() == IDLE` obscenely often

These changes simply subscribe to `onAnimationChanged` to listen for that same `IDLE`  value instead of brute-force checking for changes

**Comment by Whired** [comment]
Reverting back to a task that will run to check to see if the player is idle to account for scenarios in which no further animation events are received after `WAIT_DURATION` has passed. Reverted `WAIT_DURATION` back to 2500ms to account for lag / etc

**Comment by Whired** [comment]
Closing this for now to remove some noise

**Pull request closed without merging**
