### PR TITLE
Fix glsl errors

### PR DESCRIPTION
**Pull request by deathbeam**
- Rename common.glsl to comp_common.glsl -Otherwise IntelliJ complains about reserved word
- Add default return statement to count_prio_offset - Otherwise intellij complains
- Move return statement to end of priority_map -IntelliJ complains about no return statement when it is in switch { default } case.

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Adam-** [comment]
I don't think any of these fixes are actual problems.

**Comment by deathbeam** [comment]
That is why I labeled them as enhancement and not bug, its just so intellij stops complaining. Even though, honestly, just looking at `count_prio_offset` it makes no sense, unless GLSL has implicit returns.

**Comment by Adam-** [comment]
Priority must be 0-17

**Comment by deathbeam** [comment]
Yeah, but the function returns nothing unless priority is 0

**Comment by Adam-** [comment]
As far as I can tell, none of these are actual errors.

**Comment by deathbeam** [comment]
As I stated before, IntelliJ is complaining about it

**Pull request closed without merging**
