### PR TITLE
Add clue hint arrows for clues

### PR DESCRIPTION
**Pull request by deathbeam**
Add hint arrows for clue locations, NPCs and GameObjects.

Depends on #1282 

Preview:
peek 2018-04-07 19-02

peek 2018-04-07 18-52

### CODE REVIEW

**Comment by D4N3-777** [comment]
Is there a way to disable this feature in the clue plugin?

**Comment by deathbeam** [comment]
No, why would you want to disable it?

**Comment by D4N3-777** [comment]
For veteran players who would find it annoying. A toggle would be perfect.

**Comment by deathbeam** [comment]
I see, yeah, reasonable. Can you open issue for it?

**Pull request merged**
