### PR TITLE
Add support for hiding the sidebar

### LINKED ISSUE #656: Add ability to hide the sidebar
Would be nice to be able to hide the sidebar that holds the config settings, hiscore lookup, xp tracker etc.

### PR DESCRIPTION
**Pull request by deathbeam**
- Add button to titlebar for showing/hiding it
- When custom chrome is disabled, disable hiding of sidebar too
- Preserve last opened panel when toggling sidebar
- Expand sidebar when something expands side panel and sidebar is hidden

Fixes #656

Preview:
peek 2018-04-20 14-45

### CODE REVIEW

**Comment by ShaunDreclin** [comment]
This button looks like it will cover up the logout button while in resizable mode. Maybe change it to a rightclick option on the X?

**Comment by deathbeam** [comment]
Yes it will but in that case you can just expand sidebar again. And this can't depend on client api, so can't add it as right-click option to the x button.

**Comment by deathbeam** [comment]
Cleaned up the commits and code and changed sidebar to work without the custom executor (so removed the sidebar hiding functionality from non-custom window chrome).

peek 2018-04-20 14-45

**Comment by ShaunDreclin** [comment]
If the button isn't gonna be visible with non-custom window chrome then it def needs a hotkey assigned to it

**Comment by deathbeam** [comment]
I don't want to add more hotkeys without any hotkey manager with it's own UI and good API. So, it can always be added later, but I am not adding it in this PR.

**Comment by Kamielvf** [comment]
This would all be solved by having a menu bar when its not inlined with custom chrome.

**Comment by ShaunDreclin** [comment]
I don't think that's the best solution, the whole point of being able to hide the sidebar is to remove clutter from the window.

What about hovering your mouse over the right side of the screen for half a second?

**Comment by Kamielvf** [comment]
There are people who prefer having a menu bar with the ability to hide the sidebar over having a sidebar which you can't hide. If you don't want the menubar you can inline it using custom chrome.

**Comment by deathbeam** [comment]
What if you are on operating system where you never have title bar without custom chrome? I definitely don't want title bar back even if I decide that I don't want it.

**Comment by ShaunDreclin** [comment]
Inlining the menu bar into custom chrome doesn't solve the issue, cause then you've got the custom chrome cluttering your screen. When you're using native window borders it's much easier to remove them using tools like windowed borderless gaming.

**Comment by Kamielvf** [comment]
Osb does this, it works. No one complains.

**Comment by ShaunDreclin** [comment]
It doesn't work and people do complain, but osb doesn't really take community suggestions.

**Comment by deathbeam** [comment]
I heard quite a few complains on that. Also plenty of people do not want titlebar.

**Comment by Kamielvf** [comment]
1) people request hiding the sidebar
2) people request having the sidebar on the other side
3) people request having a menu bar 

I guess osb's "solution" is their hotkey to hide the menubar/sidebar.

**Comment by deathbeam** [comment]
People requested to have the sidebar as menubar, not have the sidebar and menubar.

**Comment by ShaunDreclin** [comment]
I think the best thing to do here is when custom chrome is disabled, keep moving the buttons into the bottom of the sidebar, and if the sidebar is hidden have some way to un-hide it like either a mouse gesture or a hotkey or something.

**Comment by ShaunDreclin** [comment]
But yeah the hotkey/gesture can be done in another PR

**Comment by Kamielvf** [comment]
We just have terrible UX, pretty much.

**Comment by deathbeam** [comment]
Adding titlebar just because of 1 button makes it even worse :P

**Comment by Saer-Dev** [comment]
Looking forward to seeing this merged!  😃 

Also, it's really cool that this is open-source and managed on GitHub so people can make changes they want to see themselves and have them put into the client.

**Comment by deathbeam** [comment]
Fixed the sidebar and panel issues, and made the keybinding work without the need of using --no-rs

**Pull request merged**
