### PR TITLE
Enterchat keybinds

### PR DESCRIPTION
**Pull request by GibsDev**
Gives users the ability to bind extra keys for arrow keys and f keys. Toggled with the ability to use the chatbar. Also respects interfaces that require keyboard input. (There are probably several more that need to be identified)

There were a few unnecessary changes in WidgetInfo and WidgetID due to auto-format.

### CODE REVIEW

**Comment by deathbeam** [comment]
I would remove all rebinding from here, you can do it from outside, and it is mostly... unrelated to enter to chat at all?

**Comment by deathbeam** [comment]
Or just add option for switching the F keys and arrows to 1-9 and WASD when having enter to chat enabled. Having them customizable is way too much and do not makes sense.

**Comment by GibsDev** [comment]
Its more about the rebinding than the enter chat. The enter chat is what enables the ability to rebind the keys in a clean and controlled way. Perhaps renaming the plugin?

**Comment by deathbeam** [comment]
I dont think there is need to add our custom rebinding to client. Also, its enum, what is terrible way to do the customizable bindings, the config system needs to be extended. As I said, just add toggle for the remaps for 1-9 and WASD.

**Comment by GibsDev** [comment]
I agree the config system needs to be extended, I just was not looking to go that deep into modifying the client for this. I don't really want to lock people into specific key binds either. I'm not sure I understand why its bad to have the ability to change them.

**Comment by deathbeam** [comment]
Because it can be done from outside. You can just fire up AHK and start remapping.

**Comment by deathbeam** [comment]
Also, the 1-9 and WASD will be the most common use case, and probably the only one.

**Comment by Jalopyy** [comment]
If this would allow me to remap the hotkeys for prayer/spells/etc to something like 1-9 or WSAD I'm down.

**Comment by GibsDev** [comment]
This allows you to map (almost) any key to arrow keys and f keys.

**Comment by Mamboosun** [comment]
How do I get this onto my client?

**Comment by joelwmale** [comment]
Is it possible to separate the keybind remapping and enter to chat? I know for myself personally - I like moving the player camera with WSAD, rather then holding down middle mouse button or using arrow keys. So I would 100% be on board with enter to chat.

But as for keybind remapping that is something I most likely won't use. So if we could separate these, that would be great IMO.

**Comment by Adam-** [comment]
Is this still relevant with #4874 ?

**Comment by deathbeam** [comment]
Looks like this was implemented, and is also quite old and has merge conflicts.

**Pull request closed without merging**
