### PR TITLE
Daily task reminders corrected for "Relog" message

### LINKED ISSUE #8308: Daily task reminders incorrectly say "Requires relog"
The buckets of sand daily notifications says "(Requires relog)"; this is incorrect. Code change should be easy & I would do it myself, but I'm not sure if any of the others also have the text that don't need it, and I don't want to do a half-assed pull request.

### PR DESCRIPTION
**Pull request by ksergio39**
close #8308

### CODE REVIEW

**Comment by ksergio39** [comment]
Everything except for Essence did not need the user to Relog

**Comment by xDemoN** [comment]
I'm fairly certain the staves require a relog

**Comment by ksergio39** [comment]
The staves were checked and it didn't require a relog.

**Comment by nateisonfire** [comment]
> I'm fairly certain the staves require a relog

Can confirm this is not the case. I'm always waiting at the barrel when they magically pop up.

**Comment by Adam-** [comment]
@ksergio39 did you verify all of these do not require relogging ingame?

**Comment by ksergio39** [comment]
@Adam-  Yes, they were all checked and all except for Essence did not require relogging ingame.

**Comment by ksergio39** [comment]
@adam would you like a Screen recording showing that they don`t need a relog?

**Pull request merged**
