### PR TITLE
Make boost overlay to change to yellow at threshold 

### LINKED ISSUE #6243: The "STAT is getting low" notification plays one level before the stat shows "below threshold" color
It seems like it should only play once the stat would display in the yellow "below threshold" color.

### PR DESCRIPTION
**Pull request by Brodan**
Fixes #6243.

### CODE REVIEW

**Comment by deathbeam** [comment]
I think it would be better if the notification was fixed (and that is about what is the issue talking about). This just makes both events consistent and incorrect.

**Comment by Brodan** [comment]
Ah okay, I misunderstood if the notification was supposed to be _at_ or _below_ the threshold. Will update the PR asap. Consistency is a good first step at least!

**Comment by Brodan** [comment]
@deathbeam Updated.

**Comment by deathbeam** [comment]
Hmm actually, i take what I said back, current behaviour is pretty confusing, just make the boost yellow indicator indicate at threshold

**Comment by raiyni** [comment]
to be honest, I would like this without a notification

**Comment by deathbeam** [comment]
Same, but, that is not related to this PR. the notification on boost seems annoying but the yellow indicator is nice

**Pull request merged**
