### PR TITLE
Cooking plugin

### PR DESCRIPTION
**Pull request by jorisrs**
Hereby I present a cooking plugin. It contains an overlay with some basic information.
image

### CODE REVIEW

**Comment by jpabeem** [comment]
Nice addition.
You might want to remove the 'Cooked/hr' row and just place its text behind the 'Cooked' amount. This would give you: `Cooked: 6 (66 h/r)`.

**Comment by jorisrs** [comment]
Here's the updated UI:
image
Also; the width is slighty wider to make all the text fit nicely.

**Comment by deathbeam** [comment]
This is like 4th "session" related plugin, maybe there should be some common structure added, because now it is just duplicate code all over the place, or maybe even have them all in 1 plugin imo.

**Comment by SoyChai** [comment]
Aw, when I read "Cooking plugin" I started imagining a cookbook panel.

**Pull request closed without merging**
