### PR TITLE
AgilityShortcut.java: Update Neitiznot Bridge agility requirements

### PR DESCRIPTION
**Pull request by robuhde**
Update Four Neitiznot bridges to 1 Agility requirement, only northeast bridge to the center island mine requires 40 agility

### CODE REVIEW

**Comment by Adam-** [comment]
1 agility is the same as no requirement - should these just be removed?

**Comment by robuhde** [comment]
yes

**Comment by Adam-** [comment]
Removing them also removes the clickboxes, so probably this is ok just changing it to 1.

**Comment by robuhde** [comment]
yeah clickbox is still valuable for these

**Comment by robuhde** [comment]
It is actually a 0 agility requirement technically. I just checked it.

**Pull request merged**
