### PR TITLE
BossTimerPlugin: Find bosses based on id instead of name

### PR DESCRIPTION
**Pull request by MagicfTail**
Add support for multi-phase bosses such as Kalphite Queen

### CODE REVIEW

**Comment by Alexsuperfly** [comment]
How did decide which of the 7 ids for KQ to use, and why are there 7 to begin with?

**Comment by Infinitay** [comment]
Why not use the api `NpcID`?

**Comment by MagicfTail** [comment]
I do not know

**Comment by Alexsuperfly** [comment]
You'll need to use the VETION_REBORN id or else the death timer will start after first phase instead of when the boss actually dies.

**Comment by MagicfTail** [comment]
I even had the correct id before 🤦‍♀️

**Comment by deathbeam** [comment]
Needs rebase

**Comment by MagicfTail** [comment]
Rebased and added a few goodies

**Pull request merged**
