### PR TITLE
Ground item timers

### LINKED ISSUE #2383: Item drop despawn and visibility timers
Suggestion
- Ability to track the time remaining until an item on the ground despawns
- Ability to track the time remaining until an item becomes visible to other players
- Ability to limit tracking to only certain items by name or by type
  - For example tracking only food and pot despawns

Things to discuss
- How to go about displaying the counter 
  - Pie chart or maybe inline with ground indicator information
  - Want to minimize clutter
- How to handle stacks of the same item
- Special Cases that affect timers
  - Items dropped in an instanced area
  - Items dropped on death
  - Are there other special circumstances that effect item despawns?

This would be very helpful for juggling items in areas such as GWD where you might have gotten more supplies from drops than you can actually hold

### LINKED ISSUE #4535: Ground Item Timers
When doing safe spot combat, it kind of sucks running out to grab loot from the ground every time something nice drops. It would be wonderful if players could have the option to see a timer next to the ground item labels that tell the player how long until the items despawn. This could potentially be limited to items that are above (x) threshold. Doing this would allow player to only have to go pick things up once they are close to despawning.

### LINKED ISSUE #4609: Dropped item timer
Hello,

Can we please get a dropped item timer, maybe switches colors or something to show when the item is visible to public? 

Example:
Blue from 1:59 to 1:01 and red from 01:00 till it disappears at zero?

Thank you.

### PR DESCRIPTION
**Pull request by ms813**
Closes #2383 and closes #4535 and closes #4609 

Known issues:
* items already on ground when you see them assume the public timer starts from 60 seconds and may disappear before that
* wilderness not handled correctly
* items dropped under you by another player are assumed to be yours so show the private timer instead of the public timer
* items dropped on player death show the 1 min public timer instead of a 1 hour timer
* stacks of items that are dropped one at a time (e.g when shift dropping an inventory) are not handled well

### CODE REVIEW

**Comment by ms813** [comment]
Green = only visible to you
Yellow = visible to everyone
Colours are customisable in settings.
Can set it so that timers are visible Always, When Hotkey is pressed (alt), or Never
Clue scroll is untradeable and green timer lasts 150 seconds
image

**Comment by Popedigoz** [comment]
Is this live?

**Comment by forsco** [comment]
> Is this live?

Hasn't been reviewed as of yet and not merged.

**Comment by azzawoody** [comment]
is this in the works for up coming updates plz add asap Keep up the good work

**Comment by JacoboMoral** [comment]
Any progress on this plugin? Really interested on it

**Comment by Adam-** [comment]
No. There are a lot of edge cases mentioned in the OP. In addition to those it also:

1) incorrectly marks static spawns as despawning when walking into a scene
2) incorrectly marks static spawns as despawning when they respawn
3) shows the incorrect time when walking into a scene with an item already on the ground

I do not think it would be that well received if we released something as incorrect as this.

Maybe if we reduced it to only show timers for things that are more likely to be correct such as:

1) items you drop yourself
2) items you get from killing a npc or player

It would be better?

**Comment by Popedigoz** [comment]
> 
> 
> No. There are a lot of edge cases mentioned in the OP. In addition to those it also:
> 
>     1. incorrectly marks static spawns as despawning when walking into a scene
> 
>     2. incorrectly marks static spawns as despawning when they respawn
> 
>     3. shows the incorrect time when walking into a scene with an item already on the ground
> 
> 
> I do not think it would be that well received if we released something as incorrect as this.
> 
> Maybe if we reduced it to only show timers for things that are more likely to be correct such as:
> 
>     1. items you drop yourself
> 
>     2. items you get from killing a npc or player
> 
> 
> It would be better?

Yes release plugin with only those and if and when possible just update to have the edge cases

**Comment by Adam-** [comment]
added by #9423

**Pull request closed without merging**
