### PR TITLE
Clue Scrolls: Add spadeReminder to HotColdClue

### LINKED ISSUE #8151: Spade reminder for strange device clues
**Problem**
It is easy to forget a spade when getting a Jorral (strange device) clue

**Describe the solution you'd like**
Leverage the existing spade-reminder functionality of the client to remind you in this situation

**Describe alternatives you've considered**

**Additional context**
I can work on this new feature

### PR DESCRIPTION
**Pull request by xDemoN**
Closes #8151 
Supersedes #8301 (Closed PR)

**Note:** Thank you to those on discord for the tips. Through restarting from scratch, I realized what I did wrong to cause so many commits in the first place.

### CODE REVIEW

**Comment by Adam-** [comment]
What about making `ClueScroll` contain whether or not it is a spade requiring clue and having `ClueScrollOverlay` add it to the panel?

**Comment by xDemoN** [comment]
That's the plan. I just haven't had time in the last week to update this.

**Comment by Adam-** [comment]
Can you test https://github.com/Adam-/runelite/tree/clue-spade ?

**Comment by xDemoN** [comment]
Testing now

**Pull request closed without merging**
