### PR TITLE
Add Quest Points chat command

### PR DESCRIPTION
**Pull request by rbbi**
Adds the QUEST_POINTS local player variable (id: 101) and !qp chat command to print the local player's quest points

qp-command

### CODE REVIEW

**Comment by Hydrox6** [comment]
What's the point of this? It only gets the local player's quest points, so everyone will appear to have the same quest points as you do.

**Comment by rbbi** [comment]
> What's the point of this? It only gets the local player's quest points, so everyone will appear to have the same quest points as you do.

Ah, thanks for letting me know - this shouldn't be the case! :)

**Comment by Adam-** [comment]
Added in ecd0f7dce3180df996bdf1a3e11374d0f746f848

**Comment by rbbi** [comment]
Thanks @Adam-

**Pull request closed without merging**
