### PR TITLE
Fix color of text in the NMZ absorption infobox

### LINKED ISSUE #606: Nightmare zone NMZ absorption counter is hard to read (white on light blue)
It can be quite hard to see how many points you have left! 

image

### PR DESCRIPTION
**Pull request by Fire-Proof**
* Changed the default text color to green
* If the absorption points goes below the threshold, the text becomes red
* Added config fields to change the color if needed

Fixes #606

### CODE REVIEW

**Comment by Fire-Proof** [comment]
I'm not sure about using the green color as a default, since it's still kinda hard to read, but it seems better than before.

**Comment by lulwut** [comment]
Could you maybe move the number to the right, will clip less with the icon.

**Comment by deathbeam** [comment]
The positions of text in infoboxes are fixed to be in center, so I dont think that is doable without making it look weird. Maybe making the text yellow instead of green would be better?

**Comment by Fire-Proof** [comment]
Couple of different colors:

Black: 


Yellow: 


Blue: 


Brown: 


Yellow might be the best, the only color that really contrast is red, but I'm using that for when it goes below a set threshold

**Comment by MothOtter** [comment]
I just tried out Nightmare Zone for the first time using the client and I have a real hard time reading the absorption number even though I've tried multiple colors. Would it be possible to get an all text config option, maybe just add "Absorption: " under the "Points: " in the list? The overload text is fine because the potion is black, but it could be an option as well. Thanks.

**Pull request merged**
