### PR TITLE
Added two new cow emojis

### PR DESCRIPTION
**Pull request by Woodse07**
Emojis taken from Twemoji.

### CODE REVIEW

**Comment by makingcomment** [comment]
... Why?

Also: Those triggers aren't very cow-like. I could definitely see someone typing them and not expecting a cow replacement.

**Review by dekvall — CHANGES_REQUESTED** [review]
The client can't handle semi-transparent pixels. I have a twemoji repo you can get them from or you can modify these and threshold alpha at 50%

**Comment by Woodse07** [comment]
> The client can't handle semi-transparent pixels. I have a twemoji repo you can get them from or you can modify these and threshold alpha at 50%

Cool thanks, I've changed them to use the emojis from your fork.

**Comment by Woodse07** [comment]
> ... Why?
> 
> Also: Those triggers aren't very cow-like. I could definitely see someone typing them and not expecting a cow replacement.

There's gorillas, acorns and aliens, why not a cow ¯\_(ツ)_/¯

Do you have any better ideas in mind for the triggers?

**Review by dekvall — APPROVED** [review]

**Comment by dekvall** [comment]
Needs rebase.

**Comment by Nightfirecat** [comment]
I don't think we really need both cow emojis--just one would be fine, though I'm not sure which would be more immediately recognizable from the image.

**Pull request merged**
