### PR TITLE
cannon: add recommended spots for dagganoths and increase overlay distance

### LINKED ISSUE #13503: cannon plugin: Add recommended spot for dagganoth in Jormungand prison
It is a pretty good task, comparable to Lighthouse. I prefer cannoning them in the western room. Not sure which tile is optimal.

### PR DESCRIPTION
**Pull request by TalSk**
Adds two Dagganoth cannon spots in Jormungand's prison which closes #13503 
One spot it to the West and enjoys more low-level Dagganoths which are better due to their nonexistent Ranged defence, and one to the East which is more open and therefore has more targets to shoot at. The positions themselves are relatively optimal in terms of cannon range and respawn positions but may possibly be altered based on more concrete data.

Also took this opportunity to combine the max rendering distance for both cannon overlays (cannonballs left, double-hit spots when the cannon is placed and the optimal positions when the cannon is not placed) which were for some reason separate but almost identical. Also increased the distance itself to somewhere around the maximal distance in which you can also interact with the cannon itself based on some testing (couldn't find it there's a known figure for that).

### CODE REVIEW

**Comment by Nightfirecat** [comment]
These changes (dag spot and extended overlay distance) should be added in separate commits.

**Comment by TalSk** [comment]
Right, would you prefer both to be committed over current master as HEAD or on top of each other?

**Comment by Nightfirecat** [comment]
They can be in the same PR

**Comment by TalSk** [comment]
Great, done

**Pull request merged**
