### PR TITLE
attack styles: Assign weapon type enum names, general cleanup

### PR DESCRIPTION
**Pull request by Nightfirecat**

### CODE REVIEW

**Comment by Ben-Colwell** [comment]
Hey, i've rebased weapon type and weapon damage type into the api on my fork. Also, I did some digging and it seems that the names/order you have assigned are incorrect. Godsword doesnt exist and polearm is 25. Crystal halberd doesnt have its own category, it falls under polearms. See https://github.com/Erishion-Games-LLC/runelite/commit/cd5d109d2f6936d707227c01d725ea2021600abc

**Comment by Nightfirecat** [comment]
Upon what are you basing this? I've tested with a real godsword and crystal halberd ingame

**Comment by Ben-Colwell** [comment]
Huh, I don't have the items so I had a friend look at it and it didn't say crystal Halberd, just polearm. I guess they either lied to me or looked at the wrong item. My apologies

**Comment by Nightfirecat** [comment]
In the case of crystal halberd, the weapon type displayed in the combat styles interface is the same as that for other polearms, but is a separate var. I'll change the name of that one too `POLEARM_CRYSTAL_HALBERD` or something of the like

**Comment by Skretzo** [comment]
Where is the [blaster category](https://oldschool.runescape.wiki/w/Weapons/Types#Blaster)? Possibly removed?  
blaster

**Comment by Nightfirecat** [comment]
> Where is the [blaster category](https://oldschool.runescape.wiki/w/Weapons/Types#Blaster)? Possibly removed?

Good question, no idea! It's not referenced [in the combat interface script](https://github.com/Joshua-F/cs2-scripts/blob/5ee4a00d170375fc0056cee97a3078ad2e7f1985/scripts/%5Bclientscript%2Ccombat_interface_setup%5D.cs2) at all, so it must have been removed pretty thoroughly since that holiday event.

**Comment by Nightfirecat** [comment]
This PR is obsolete as of ffe16454ba894d673db91e2d1fd8d3c4c265b2c7

**Pull request closed without merging**
