### PR TITLE
Add Puro Puro static spawn locations and fix dynamic spawns

### PR DESCRIPTION
**Pull request by Juzzed**
Fixes the dynamic spawns for implings and adds static spawns. 

Todo:
- [x] Add static impling spawns
- [x] Add dynamic imling spawns
- [x] Hide static spawns

dd

fe4c4620f2a21ba8c69a531b94ddfd05

Fixes:
#2087

### CODE REVIEW

**Comment by SomeZer0** [comment]
Isn't the dynamic one Nature-Lucky?

This looks really nice btw. Will help for farming eclectics and looking for dragon imps.

**Comment by Juzzed** [comment]
True. Ill change that

**Comment by Adam-** [comment]
Unless OSB is showing the dynamic spawns already I would prefer to not have the plugin show them.

**Comment by SomeZer0** [comment]
Adam we already show the dynamic spawns (except its bugged)

**Comment by Kamielvf** [comment]
@Adam- IMO showing dynamic spawns isn't OP. If an impling spawns from these it will be highlighted by the plugin anyway, and it's not giving the user any advantage since these spawns are still very rng based.

**Pull request closed without merging**
