### PR TITLE
Add support for quick startup via Spring boot

### PR DESCRIPTION
**Pull request by deathbeam**
## Add support for quick startup via Spring boot

- Move the data source and runelite-related properties to spring boot
application.yml
- Add support for building runnable .war by default
- Add support for running the .war with Tomcat embedded from command line
- Add sample initialization script to repository

## Remove need for custom MySQL function in XpTracker

- Remove usage of custom MySQL functions
- Replace the values calculated from custom MySQL functions with plain
data from HiScore API
- Remove virtual value for overall_xp and replace it with plain data due
to the virtual column length limit

## Move initialization of session db to service

- Instead of need to initialize session db manually, do it from session
service.

## Move the API endpoints configuration to props

- Move the hardcoded API and websocket endpoints from RuneliteAP
property file for easier manipulation of them.

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

# Running the API locally

To run API locally, just change:

```diff
diff --git a/http-api/src/main/resources/runelite.properties b
index d664f60f5..d42bb779f 100644
--- a/http-api/src/main/resources/runelite.properties
+++ b/http-api/src/main/resources/runelite.properties
@@ -1,4 +1,4 @@
 runelite.version=${project.version}
 rs.version=${rs.version}
-url.http=https://api.runelite.net/runelite-${project.version}
-url.ws=wss://api.runelite.net/runelite-${project.version}
+url.http=http://localhost:8080
+url.ws=ws://localhost:8080
```

then build the project and run http service like executable .jar:

```
java -jar http-service/target/runelite-*-SNAPSHOT.war
```

## Configuring tomcat and deploying

```
~/apache-tomcat-8.5.29
$ cat conf/context.xml | \grep --color=auto Parameter
    <Parameter name="spring.config.location" value="/runelite-application.yaml" />

~/apache-tomcat-8.5.29
$ ls -lh conf | \grep --color=auto runelite
Alias tip: ll conf | \grep --color=auto runelite
-rw-r--r-- 1 vagrant vagrant 1.4K Apr 30 18:18 runelite-application.yaml
```

To deploy
```
mvn clean tomcat7:deploy -Drunelite.tomcat.url="http://localhost:8080/manager/text"
```

### CODE REVIEW

**Comment by shuhaowu** [comment]
Does changing the runelite.properties file require a rebuild? If so, can #2129 be merged into this?

**Comment by deathbeam** [comment]
Hmm yes it does. But environment variables might be better. Or, some property that is set during build time to maven, depends on your deployement setup.

**Comment by shuhaowu** [comment]
IMO it would be neat to be able to run the official binary from runelite AND run a local API server. Having something like an environment variable might be better for that.

Furthermore, if you have a development environment running with a local test server, it would be nice to use environment variable so you don't have a unstaged diff always hanging out that you have to avoid during a `git add`.

**Comment by deathbeam** [comment]
1. I don't think it should be possible to un-tie client with API, because it is always possible that there will be breaking change between API and client, and simply changing the used API and using client of different version sounds probably like something you don't want to do.

2. That is why I suggested build property, e.g something like `mvn clean install -Dapi.url='foo' -Dapi.ws='bar'`

**Comment by shuhaowu** [comment]
Oh I didn't mean to untie the API from the client. I simply mean to run both an official API war file and an official client jar locally without modifications.

Build property could be good as well.

**Comment by shuhaowu** [comment]
@deathbeam Did you also find that you had issues with the server trying to save data.
 
I see that in the code base we have a bunch of try-with-resource blocks wrapping SQL statements. However, I don't see any `conn.commit()` in the code base, such as [here in `ItemService`](https://github.com/runelite/runelite/blob/301676090f43c5f5371071f85e20c8532f5a3b73/http-service/src/main/java/net/runelite/http/service/item/ItemService.java#L183-L195). Looking at the [sql2o docs on transactions](https://github.com/aaberg/sql2o/wiki/Transactions), it says you have to call `commit` at the end of a `try` block otherwise it will rollback.

Now I ran mysql locally with `general_log = ON` so I can log all the queries, indeed I see that most statements are getting automatically rolled back, which is why I'm getting some foreign key constraint violations for price histories.

Now I do see that we do have some commit(), just not everywhere (see 301676090f43c5f5371071f85e20c8532f5a3b73). Am I missing something?

**Pull request closed without merging**
