### PR TITLE
Fix ROF off by one error

### LINKED ISSUE #12725: Wrong charge count on ring of forging after it melts
**To Reproduce**
1. Equip a ring of forging
2. Smelt 140 iron bars
3. See error

**Expected behavior**
Displayed charge count is 140

**Actual behavior**
Displayed charge count is 139

**Additional context**
This is the same bug we used to encounter with expeditious/slaughter bracelets, where the count would be incorrectly set due to multiple chat messages being received in an unexpected order. See below logs:

```
2020-10-30 21:58:59 [Client] DEBUG client-patch - Chat message type SPAM: You smelt the iron in the furnace.
2020-10-30 21:59:01 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: <col=7f007f>Your Ring of Forging has melted.</col>
2020-10-30 21:59:01 [Client] DEBUG n.r.c.plugins.examine.ExaminePlugin - Got examine without a pending examine?
2020-10-30 21:59:01 [Client] DEBUG n.r.client.config.ConfigManager - Setting configuration value for itemCharge.ringOfForging to 140
2020-10-30 21:59:01 [Client] DEBUG client-patch - Chat message type SPAM: You retrieve a bar of iron.
2020-10-30 21:59:01 [Client] DEBUG n.r.client.config.ConfigManager - Setting configuration value for itemCharge.ringOfForging to 139
```

### PR DESCRIPTION
**Pull request by olligobber**
Fixes #12725 

The issue is that when a ring breaks, the client sends the message for the ring breaking, followed by a message that the ring has been used. Consequently, we need to set the number of charges one higher when we get the break message, so that when the use message arrives and we decrement the number of charges, we end up with the correct amount.

The test for this has been redesigned to send both the break and use messages, simulating actual client behavior, and tests we end up with the correct number at the end.

### CODE REVIEW

**Comment by Adam-** [comment]
You've changed the behavior of the plugin, and the test tests the behavior of the plugin, and so the test is failing. It is possible the test is incorrect and testing the wrong behavior, in which case the test would need to be updated. Offhand I do not know if either the test is right or your change is right.

**Comment by olligobber** [comment]
I have updated the test so that it should be correct, but it is still failing.

**Comment by Alexsuperfly** [comment]
#15288 at least explains why the change is being made and has a correct test

**Comment by olligobber** [comment]
I feel like the comments in my code explain why the change is being made. The way they fixed the test is unsatisfactory, as it does not emulate the actual behaviour of the client, so I opted to do the test this way. If #15288 does this better, then we should merge that instead.

**Comment by dogdogcatdog** [comment]
The test is expecting the value 140, but 141 is returned. Because your change of adding + 1 to `MAX_RING_OF_FORGING_CHARGES`. Though I don't think this is the right solution. A conditional to subtracting in the first place I think is more suitable such as skipping if `RING_OF_FORGING_USED_TEXT` is after `RING_OF_FORGING_BREAK_TEXT`.

**Comment by olligobber** [comment]
I don't know why 141 is returned, if you look at the modified test, the ring is used after it is broken, same as in the client, so it should return 140.

I made this change to imitate the way necklaces of binding are coded, so if we make this change to rings of forging, we should make the same change to necklaces of binding

**Pull request merged**
