### PR TITLE
bank tags: Add alphabetic sorting option for bank tag tabs

### PR DESCRIPTION
**Pull request by StephanBijzitter**
Fixes #16923

### CODE REVIEW

**Comment by raiyni** [comment]
1. This is misleading with dragging and dropping
2. I think onus is on the user to organize their tabs

**Comment by StephanBijzitter** [comment]
Yeah dragging and dropping gets reset by this, but I wanted to keep this minimal (at least until the first review) before going all-out.

As for the user sorting it themselves... that's a massive pain in the ass with the current behaviour of switching tabs, rather than inserting between tabs. Let's say you got 100 tabs and create a new one, which you want at the tob, you'd have to drag&drop 100 times

**Comment by raiyni** [comment]
It follows the Swap/Insert setting of the bank

**Comment by StephanBijzitter** [comment]
> It follows the Swap/Insert setting of the bank

Oh. My. God.

Yeah then it's probably a better idea to make a third party plugin with multiple sorting options that just rewrites `banktags.tagtabs`. Even with inserting between tabs, sorting them at the click of a button is still nice for everyone who already has a large amount of tabs

**Pull request closed without merging**
