### PR TITLE
Equipment Viewer plugin

### LINKED ISSUE #4353: As a addition to the inventory viewer can we get a worn equipment viewer?
title

### PR DESCRIPTION
**Pull request by MJHylkema**
Fixes #4353

Refactored the existing inventory viewer plugin to support an equipment tab viewer too. Changed the plugin to "Tabs Viewer" rather than "Inventory Viewer". Able to display either or both overlay at the same time.

img

### CODE REVIEW

**Comment by MagicfTail** [comment]
If you add Fixes #4353 it will auto close the issue when merged

**Comment by Nightfirecat** [comment]
It looks like your current code doesn't make the panel match the spacing of the ingame equipment screen. You posted a screenshot before that did--why did that change?

**Comment by MJHylkema** [comment]
@Nightfirecat If you take a look at the screenshot in the referenced issue, having a gap set was not correctly setting the height of the panel which meant the bottom slots were hitting the border. I decided to just remove the gaps and make it a more compact panel.

**Comment by raiyni** [comment]
This has been added as an external plugin `Equipment Inspector`

**Comment by septicsalmon** [comment]
> 
> 
> This has been added as an external plugin `Equipment Inspector`

Does not allow me to have my own equipment viewable on screen so no this has not been added by it

**Pull request closed without merging**
