### PR TITLE
Replace timer-based usages of Instant.now() with System.nanoTime()

### LINKED ISSUE #999: Time-related plugins depend on the system clock
The report button plugin / idle notifier plugin currently make use of Instant objects to get and make use of the system clock for time based calculations.

If a user modifies their system clock, these time-based calculations will be thrown off and in some cases can cause exceptions to be thrown. Time-based calculations should use the current system up-time (System.nanoTime()) which cannot be easily modified.

idea64_2037-03-17_13-27-14

### PR DESCRIPTION
**Pull request by SoyChai**
This resolves #999. Don't be scared by the title, the code changes are actually very simple.

Summary of the problem:
> Several plugins currently make use of Instants to store past or future moments, and then later compare those Instants against `Instant.now()` for things like timers, idle warnings, etc. This is a risky design choice because it assumes the user will never change their system time, and as FrozenState pointed out, can cause timing misbehaviour and even exceptions.

>Instead of referring to the system clock, we can use `System.nanoTime()` to return the elapsed system uptime in nanoseconds, which can be relied upon to not jump forwards or backwards unexpectedly. `System.currentTimeInMillis()` can't be used for this purpose since it returns epoch time, which suffers from the same problem.

I've replaced all timer-based `Instant` fields with a `long` representing a moment in system nanoseconds. Any code which checked whether an `instant == null` now simply checks if a `nanoTime == 0`, and lengths of nanoseconds are generally abstracted into Duration objects.

### CODE REVIEW

**Comment by SoyChai** [comment]
I found the [pull request](https://github.com/runelite/runelite/pull/1027) where @FrozenState fixed this issue in the report button plugin. If that gets merged, my changes for the overlapping files can be discarded.

**Comment by Adam-** [comment]
I probably do not want to fix this. I consider the advantage of using java.time > the benefit of fixing this edge case.

**Comment by SoyChai** [comment]
Understandable, though the power of the java.time classes allows them to handle raw units like this pretty seamlessly. Do you reckon it'd cause problems somewhere?

**Comment by deathbeam** [comment]
Closing as this is very old PR now and has a lot of merge conflicts, reopen if you want to re-implement it.

**Pull request closed without merging**
