### PR TITLE
Fix setting of hiscore stats after combat level

### PR DESCRIPTION
**Pull request by AlexKolpa**
`result.getSkill(null)` throws an IllegalArgumentException, which meant the hiscores were never set beyond combat level.

Introduced in https://github.com/runelite/runelite/pull/3035/files#diff-63f5372602c8f4a5d59848b8189532adR467

### CODE REVIEW

**Comment by AlexKolpa** [comment]
Hang on, not a fan of this flow actually as it's not clear what's happening (previous if-elseif didn't help). Will see if I can rework it into a simpler flow.

**Comment by AlexKolpa** [comment]
Okay, reworked the flow so it's more similar to how it was before, as the `else if` introduced some confusion. Given that 'combat' is a pretty special case (in that it's not actually an actual lookup, but a derivation), I've left it in the `if` block. The `else` block now contains all logic for the 'normal' hiscore skills, which do follow a proper lookup flow.

**Comment by xaviergmail** [comment]
Tested and works. Weird that cb/total/bh/clues are treated as skills!

**Comment by psikoi** [comment]
It is really weird, I spent way too much time trying to understand the code, tried leaving comments wherever I could.

**Pull request merged**
