### PR TITLE
Change default bank tag searching prefix

### PR DESCRIPTION
**Pull request by awphi**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Why?

**Comment by jerwuqu** [comment]
Why not? I know I'd prefer typing a single character like `!` instead of `tag:` every time I need to access tagged items. 

I don't understand why customizability would be a bad thing.

**Comment by SoyChai** [comment]
I think jerwu's suggestion is a much cleaner realisation of the idea behind this pr. Why don't we just use a shorter prefix by default?

**Comment by jerwuqu** [comment]
Changing the default would also be alright. 

I think `#` would make the most sense to most people (as in `#barrows`, `#ring`, etc. when searching for them).

**Comment by AWPH-I** [comment]
Basically agree with jer but changing the default works just as well for most cases I guess. Though it's mostly useless I'm not sure why it's a bad thing to give another simple option that could help a handful of users.

**Comment by AWPH-I** [comment]
Understandable - that's a big issue with other clients and one of the reasons I switched to this. I'll go ahead and close this.

**Comment by deathbeam** [comment]
There was no need to close this, you could've just changed the PR to set the default tag to `#` (basing on the discussion that is the most friendly prefix).

**Comment by SoyChai** [comment]
(And you still can, if you want!)

**Comment by SoyChai** [comment]
Looks good now, I think everyone will be happy with this change. The next step is to squash all of the commits in this PR down to just one, to simplify the git history after it gets merged. The earlier commits effectively never happened since you've reverted them 👻

**Comment by Adam-** [comment]
The other clients all use tag: do they not?

**Comment by deathbeam** [comment]
Yeah, both OSB and Konduit afaik.

**Comment by Adam-** [comment]
I do not want to change the behavior of tag: since the other clients use it. Using both tag: or # would be fine.

**Comment by SoyChai** [comment]
Would anyone honestly prefer to type `tag:` instead of just `#` after learning how it works in RuneLite, though?

**Comment by deathbeam** [comment]
Closing as this is very old PR now and has a lot of merge conflicts, reopen if you want to re-implement it.

**Pull request closed without merging**
