### PR TITLE
gpu: add scene anti-aliasing

### PR DESCRIPTION
**Pull request by devLotto**
**Off:**

no_aa

**MSAA x8:**

msaa_x8

### CODE REVIEW

**Comment by devLotto** [comment]
Should work now @MP2E 
There was a stray ``glDeleteBuffer(gl, uniformBufferId);`` that appeared when rebasing onto master that broke everything.

**Comment by MP2E** [comment]
Works perfectly now, thanks!

**Comment by devLotto** [comment]
Waiting for #6639

**Comment by tyler27** [comment]
> Waiting for #6639

Will this fix the issue in fixed mode?

**Comment by devLotto** [comment]
Updated

**Pull request merged**
