### PR TITLE
Add projectile indicators

### PR DESCRIPTION
**Pull request by Toocanzs**
This adds projectile indicators in the same way that Konduit has them.

Vasa, Shamans, and Tekton have indicators, and Shamans only show inside raids as that is how Konduit's work.

The indicator is only 1 tile large and does not show the radius.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
This was added before, then rolled back at Jagex's request: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

Is there something new about this implementation which is fine, which wasn't fine with the previous implementation?

**Comment by BopOSRS** [comment]
What ever happened to this?

**Comment by ATimmeh33** [comment]
Would like to see this get added, currently the only reason I use Konduit for

**Comment by BopOSRS** [comment]
^Same, this is the only reason I still use Konduit for raids and not Runelite.

**Pull request closed without merging**
