### PR TITLE
Added alternatives for chat commands

### PR DESCRIPTION
**Pull request by failip**
Implements the feature requested in #5294

### CODE REVIEW

**Comment by raiyni** [comment]
This and https://github.com/runelite/runelite/pull/5801

look like blatant copy and paste for hacktoberfest, they are even split out into 2 prs.

**Comment by failip** [comment]
Where exactly did I copy this from?

**Comment by NathenSample** [comment]
Both this PR, and #5801, when combined together, implement the same changeset that #5303 attempts to introduce.

Your modifications of `ChatCommandsPlugin` are incredibly close to the modifications #5303 makes, but you use sets rather than regex, which could be pure coincidence.

However in #5801 it is painfully obvious that `BossAbbreviations.java` is a direct copy and paste from #5303 which draws further attention to the similarities that this PR has to how it was performed there.

**Comment by failip** [comment]
I know you guys wont believe me for whatever reason but I actually just looked at #5294 and the replies, where Unmoon suggested to do the boss names like the SkillAbbreviations (I just compared mine and the one I 'copied' and I actually changed a subtle spelling mistake which I definitely wouldn't have noticed if I just copy pasted). 

I split the PRs into two separate ones because I though that would be the proper way to do it, as this is my first time contributing to an OSS. 

Just found it a bit rude to imply ill intent, if I just wanted PRs I could've just opened my own public repo.

So should I combine the two PRs? And any actual comments :D?

**Comment by Nightfirecat** [comment]
Per comments on #5294, we're not looking to add this feature anymore in order to maintain consistent cross-client command names.

**Pull request closed without merging**
