### PR TITLE
Add configurabe goals to XP tracker plugin

### PR DESCRIPTION
**Pull request by ChaoticConundrum**
I wanted configurable goals in the XP tracker plugin, so here's what I have. I opted to just add to the existing UI. I know about #507, but I figured I'd write the feature first and figure out the exact UI later.

So the two UI changes are the addition of the "Set Goal.." button and a secondary progress bar when a goal is set on a skill tracker. When a goal is set, the second bar has the original behavior, showing the progress within the current level. (there is a config option to disable this bar)

screenshot_20180301_010341

Also the new dialogs for setting a goal:

screenshot_20180301_010204
screenshot_20180301_010228

### CODE REVIEW

**Comment by deathbeam** [comment]
Hmm, I feel like this is feature that OSRS client have and we are just re-implementing it at different place.

**Comment by ChaoticConundrum** [comment]
What do you mean? Is there an existing visual goal tracking plugin?

**Comment by deathbeam** [comment]
Yes, in the client directly, it's not plugin. Right click the XP icon, you can set goals there etc.

**Comment by ChaoticConundrum** [comment]
Wow, no kidding. I didn't know about that. I think the plugin version is a bit easier to work with, and more information could be added to it. But good to know.

**Comment by ChaoticConundrum** [comment]
Made some changes based on feedback. No more dialogs, the Set Goals.. button toggles a panel below the info panel that lets you set goals:

screenshot_20180304_050302

This also now supports XP goals as well as level goals.

**Comment by ChaoticConundrum** [comment]
Closing this PR, it suffered from scope creep when I went to make the goals persistent and synced between clients. If I were to pick this up again, it may be more useful to just augment Jagex's goal tracker interface, maybe connecting that to the xptracker panel.

**Pull request closed without merging**
