### PR TITLE
Replace manual checks with `isEmpty()`

### PR DESCRIPTION
**Pull request by tygyh**

### CODE REVIEW

**Comment by abextm** [comment]
Please stop opening machine generated spam prs

**Comment by tygyh** [comment]
> Please stop opening machine generated spam prs

Other than the IDE finding the issues I do everything by hand.
Do you want me to make larger PRs instead of several smaller ones?

**Comment by LlemonDuck** [comment]
PRs that only change style without any functional purpose are not helpful, whether "manual" or not (although an IDE recommendation is also not "by hand"). 

This change doesn't make any of the code easier to read, nor is it "more correct".

**Comment by tygyh** [comment]
> This change doesn't make any of the code easier to read, nor is it "more correct".

Why would Sun Microsystems spend time on implementing an `isEmpty` function in Java if it has no benefit?

**Pull request closed without merging**
