### PR TITLE
Add support for resizable overlays

### LINKED ISSUE #1716: Allow customization of default overlay font
Since last update (1.3.5) the "small font" toggle was only applied to dynamic overlays. There should be another option for the regular overlays to allow changing these fonts too.

Requested several times on discord.

### LINKED ISSUE #3916: Make overlays resizable
Since you have the ability to change the size of the infoboxes and dynamic overlays , I think the overlays like: opponent info, raids scout overlay, etc... should have the ability to do this aswell.

### PR DESCRIPTION
**Pull request by deathbeam**
Add mostly complete support for resizable overlays.

Closes #3916
Closes #1716

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview:
peek 2018-07-26 21-02

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Behavior looks good! How difficult would it be to change the cursor to one of the resizing cursors when hovering edges/corners? That would help usability a lot.

**Comment by deathbeam** [comment]
hmm, probably doable

**Comment by deathbeam** [comment]
Done and updated

**Comment by Nightfirecat** [comment]
Is there a way to reset an overlay's size to its default? (alt+right-click border maybe?)

**Comment by deathbeam** [comment]
alt + right click resets overlay, so it resets also size

**Comment by deathbeam** [comment]
Should be good now, everything works

**Pull request closed without merging**
