### PR TITLE
Add ability to move LMS info box

### LINKED ISSUE #9818: Make LMS rank overlay movable
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
https://imgur.com/VIkIr8V
this menu at lms is extermely inconvient since in middle of screen cant see someone running at u or your own prays.. 

**Describe the solution you'd like**
please make it moveable like exilent has it. it came with jagex new update today
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
able to take it away completely?
**Additional context**

### PR DESCRIPTION
**Pull request by dabolink**
dynamic LMS infobox

closes #9818

### CODE REVIEW

**Comment by abextm** [comment]
`ThatGamerBlue: theres a different widget id inside lms too`

**Comment by dabolink** [comment]
ah missed that as I don't play the minigame. added.

**Comment by Adam-** [comment]
Looks like this got moved back now, is it still needed?

**Comment by Nightfirecat** [comment]
It seems like it'd be a nice feature to have regardless of where it is by default ingame.

**Comment by deathbeam** [comment]
Can someone retest this?

**Pull request merged**
