### PR TITLE
Add Ring of Visiblity emote clue requirement for Smoke Dungeon

### PR DESCRIPTION
**Pull request by Timmy-Jim**
Add Ring of Visiblity to list since it is needed to enter dungeon.  Correct typo in hot/cold clue

### CODE REVIEW

**Comment by deathbeam** [comment]
Well, you made it worse...

**Comment by Timmy-Jim** [comment]
@deathbeam  I'm not understanding then - you said separate commits.  They are separate now aren't they? Or do you mean my titles are worse?

**Comment by deathbeam** [comment]
Well you made 4 instead of 2 so you did not improved the commit history at all. Anyway, I fixed it for you

**Comment by Timmy-Jim** [comment]
@deathbeam  Mind telling me how you did that so I know in the future?

**Comment by deathbeam** [comment]
`git reset master`

recommited the changes separately and then

`git push --force`

**Pull request merged**
