### PR TITLE
Changed exception handling to log warning instead of swallowing

### PR DESCRIPTION
**Pull request by qbolt**
Changed exception handling to log warning instead of swallowing exception by returning false

### CODE REVIEW

**Comment by Adam-** [comment]
Why? This is not really an error, terminal-notifier is allowed to not be available.

**Comment by qbolt** [comment]
It's not an error - It's just seemingly inconsistent with the rest of the code base which seems to log errors instead of swallowing them - just a minor enhancement to adhere to better practices for exception handling.

**Comment by qbolt** [comment]
Ok, great point! - I'll update PR.

**Comment by Adam-** [comment]
Probably I would do debug + also pass the exception to slf4j.

**Comment by qbolt** [comment]
Ok fair enough - I'll close.

**Pull request closed without merging**
