### PR TITLE
Add 'Disable left-click' for the placeholder toggle in bank

### LINKED ISSUE #14961: Add 'Disable left-click' for the placeholder toggle
This added config should work the same way as the ones for depositing your inventory or equipment do--when enabled, left-clicking the "Toggle placeholders" button (with the :lock: symbol) should force a minimenu to pop up.

---

### Discussed in https://github.com/runelite/runelite/discussions/14943

<div type='discussions-op-text'>

<sup>Originally posted by **Memebeams** May 12, 2022</sup>
Currently, the bank plugin allows you to avoid accidental deposits by disabling left-click on deposit buttons:
image

Sometimes, I will remove items from my bank without realizing that the placeholder button was turned off and mess up my bank arrangement. This button would make it harder for dingbats like me to turn placeholders off</div>

### PR DESCRIPTION
**Pull request by Fiffers**
Closes #14961

### CODE REVIEW

**Comment by geheur** [comment]
Now there are 2 PRs XD https://github.com/runelite/runelite/pull/14997

**Comment by sjpfeiffer** [comment]
I swear I looked for another PR in that post. Sorry, I'll close this one.

**Comment by geheur** [comment]
idk if it has to be closed, just thought it was funny. maybe yours will be better than the other one.

**Comment by Fiffers** [comment]
Reopened #14975

**Pull request closed without merging**
