### PR TITLE
Hide cannon spot overlay if player lacks the cannon.

### PR DESCRIPTION
**Pull request by psikoi**
**CannonPlugin**
- Added `hasCannon()` that returns true if the player has 4 cannon pieces on their inventory. 
- Added a int set `cannonParts` containing the item ids for the cannon parts.
- Added a `QueryRunner` attribute for checking inventory items.

**CannonSpotOverlay**
- Added a check (using `hasCannon()`) to prevent the plugin from displaying the cannon spot if the player lacks the cannon pieces.

### CODE REVIEW

**Comment by SoyChai** [comment]
Note that this produces a slight side-effect: even if you are carrying your cannon, you can no longer see any of the cannon spots once you build it on the ground.

**Comment by psikoi** [comment]
Is that a problem? Once you place your cannon, why do you need to see others spots (until you have to pick it up and move it elsewhere)?

This is to prevent regular players from seeing the plugin for no reason.

**Comment by SoyChai** [comment]
Just a feeling, seeing the cannon spots at all times is kind of a quality-of-life feature too. Maybe you could add a config toggle for this purpose?

**Comment by psikoi** [comment]
I did add a toggle for this new feature.

**Comment by deathbeam** [comment]
You should probably split the addition of new config value and the reorder of the entire config in separate commits, right now the diff is super confusing.

**Comment by psikoi** [comment]
Will do.

**Pull request closed without merging**
