### PR TITLE
Fix screenshot with hidpi scaling with GPU plugin

### LINKED ISSUE #12463: Screenshot size issue with GPU and Stretched Mode plugins on Linux
Note: [11403](https://github.com/runelite/runelite/issues/11403) is the same issue for Windows, not Linux.

**Describe the bug**
When using RuneLite on Linux with GPU and Stretched Mode plugins, screenshot functionality only captures ~25% of the game window.

**To Reproduce**
1. Use RuneLite on Linux
2. Enable GPU plugin
3. Enable Stretched Mode plugin
4. Take screenshot

**Expected behavior**
Full-size client screenshot of entire window.

**Screenshots**
[https://imgur.com/a/j29YI4B](https://imgur.com/a/j29YI4B)

**Environment (please complete the following information):**
 - OS: Pop!_OS 20.04
 - RuneLite version: 1.6.26.1
 - Launcher version: 2.1.3

**Additional context**
I am using the .jar file on a 4K monitor with 200% desktop scaling.

### PR DESCRIPTION
**Pull request by jacobmischka**
The ClientUI changes are somewhat gross and non-DRY, but it seemed better than overengineering more abstractions.

Fixes #12463

### CODE REVIEW

**Comment by jacobmischka** [comment]
Ah whoops, sorry about those checkstyle fails.

**Comment by Adam-** [comment]
This should probably look something similar to what `glDpiAwareViewport` looks like.

**Comment by jacobmischka** [comment]
Ah nice, I missed that bit. You're right, that is cleaner and better.

**Comment by Adam-** [comment]
Are you able to reproduce this problem currently, and are you using Linux?

**Comment by jacobmischka** [comment]
Yes, and I am, yes. Both of the following screenshots were taken with GPU and Stretched plugins enabled, on Linux, with GDK_SCALE=2.

Before this change:



After this change:

**Comment by jacobmischka** [comment]
I don't have a Windows machine to test right now, but I imagine this should also fix #11403.

**Comment by Adam-** [comment]
I've tested this some and this breaks Windows with UI scaling on. I will look into it more.

**Comment by jacobmischka** [comment]
Oh darn, breaks how?

**Comment by Adam-** [comment]
So master is broken on Windows with scaling, but this PR is also broken, but they are broken differently. Which is odd.

This pr does:



and master does:

**Comment by jacobmischka** [comment]
Interesting. I'll try to get a Windows machine set up and look into it soon.

**Comment by Adam-** [comment]
For additional levels of confusion, *release* on *release launcher* works correctly, as well as master on release launcher and this PR on release launcher. I believe this is due to https://github.com/runelite/launcher/commit/123bb6590643e6e645dbd1cd070f00b1a8c16cae which is what allows RuneLite to UI scale on Windows as an application (the commit removes the dpi awareness flag from the RuneLite.exe manifest, resulting in Windows thinking RuneLite isn't DPI aware). This is due to the Java 8/11 DPI awareness stuff being some combination of completely missing or not working and we can't really change it regardless. 

So we can maybe merge this since it doesn't seem to break anything more. It would be nice to make this work outside of the launcher I suppose but I think it might be some other issues.

**Pull request merged**
