### PR TITLE
hiscore: use a builder to build the tooltips

### LINKED ISSUE #6368: More information on tooltips for hiscore entries
I, like a lot of newer players; are not 100% familiar with all of the entries on the hiscores, and some entries have no information as to what the rank is. (The bottom two ranks and the second to bottom right rank)

All other entries say the skill name of the entry, for consistancy and to save players the trouble of going to the hiscores to try and find out what those are, perhaps the tooltip could read: 
"Last man standing"   
"Rank: X"                   
etc
image

### PR DESCRIPTION
**Pull request by adwitkow**
- instead of using a raw html string to build the tooltips, we can use builder components and convert them on return
- hiding the elements based on availability is easier now (instead of showing three null values for a tooltip - `rank: unranked`, `xp: unranked` and `remaining xp: unranked` for some reason - we can just omit anything but `rank: unranked`)
- clue scrolls are still bad but they have a title now
- I am not sure how the `closingTags` ever worked
- also, closes #6368 because titles were added

I am still learning lombok so pls no bully

### CODE REVIEW

**Comment by raiyni** [comment]
What do we need this for to build swing tooltips?

**Comment by adwitkow** [comment]
I dunno, feel free to actually take a look at the PR instead of posting unhelpful comments.

**Comment by raiyni** [comment]
I did, that is why I am asking. It looks like it is specially wrote for the high scores panel.

**Comment by Nightfirecat** [comment]
Titles were added in 2f85f574875f13ad60317ecfc2a4a79727ccef04. Given that and the inactivity here, I am closing this PR.

**Pull request closed without merging**
