### PR TITLE
Prifddinas world map icon updates

### PR DESCRIPTION
**Pull request by Alexsuperfly**

### CODE REVIEW

**Comment by SebastiaanVanspauwen** [comment]
There's a few more things that should be included to complete the whole update I think:

- Rename Elf Camp Teleport to Iorwerth Camp Teleport (not sure if that's the name before quest aswell)
- Farming patch east side in Prifddinas (Allotment/Flower) (3289, 6100, 0)
-  Both Crystal seed teleports LLetya  (2331, 3171, 0) and Prifddinas (3263, 6068, 0)

**Comment by dekvall** [comment]
The Gwenith maples and Arandar agility shortcuts exist on both the surface world and and Prifddinas map so I believe we need to add them twice.

 - Maple:  (3233, 6179)
 - Low cliff: (3369, 5052)
 - Medium cliff: (3361, 6040)
 - Advanced cliff: (3361, 6005)

**Comment by Alexsuperfly** [comment]
I wanted to add those but i couldnt figure out how to get the tile location for them, thanks.  Also if you know the location for the charter ship on the prif map that would be nice.

**Comment by SebastiaanVanspauwen** [comment]
Charter ship on inside is (3180, 6083)

**Comment by dekvall** [comment]
I think the charter ship is at (3180, 6083) on that map

**Pull request merged**
