### PR TITLE
MenuEnterySwapper Dark Mage

### LINKED ISSUE #2806: Menu Swapper for Dark Mage
https://i.imgur.com/uvPVooo.jpg

Move 'Repair' to left click.

### PR DESCRIPTION
**Pull request by KasparRosin**
closes #2806
closes #3464
#5900 accident repair

### CODE REVIEW

**Comment by KasparRosin** [comment]
I thought they are organized by alphabet now?

**Comment by KasparRosin** [comment]
I have to submit a fresh one since I've deleted that repository. Or is there an another way?

**Comment by Nightfirecat** [comment]
I'm not sure there's an easier way if you've deleted your fork.

**Comment by KasparRosin** [comment]
Closing this PR and opening a new one.

**Pull request closed without merging**
