### PR TITLE
Test wilderness lever swap

### PR DESCRIPTION
**Pull request by josiahlund**
Wilderness lever menu swap. Accidentally closed the last pull request when I pushed a new name to my branch.

### CODE REVIEW

**Comment by lund8619** [comment]
For issue #5516

**Comment by hourfreedev** [comment]
Duplicate of #5593  and #5532

**Comment by Adam-** [comment]
I'd rather not swap this (and CERTAINLY not by default as this is doing) as people will just tele to the wrong place, get killed, and blame us.

**Comment by Nightfirecat** [comment]
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42

**Pull request closed without merging**
