### PR TITLE
Reorder Prayers Plugin

### PR DESCRIPTION
**Pull request by DevDennis**
- Adds https://github.com/runelite/runelite/issues/908
- Allows you to unlock the ability to drag prayers in new positions

image

### CODE REVIEW

**Comment by RyleeT** [comment]
Thank you for making this plugin. I wanted this feature so badly and your execution is perfect. I can't wait to try it!

**Comment by DevDennis** [comment]
I will add reordering for quick prayers later

**Comment by DevDennis** [comment]
Added quick prayer reordering
The plugin should be finished now

**Comment by Kamielvf** [comment]
Saw this the other day, looking good! I thought maybe it'd be possible adding a lock/unlock option on the right-click menu of the tab (the prayer icon). This would allow users to quickly setup their custom prayer book without having to go to the plugin.

**Comment by DevDennis** [comment]
Like this? 
image
@Kamielvf

**Comment by Kamielvf** [comment]
Yes! That's what I was talking about :+1:

**Pull request merged**
