### PR TITLE
emoji: Add shadow to spoon, fork-and-knife emojis

### PR DESCRIPTION
**Pull request by Nightfirecat**
Without a shadow, these emojis were nearly unreadable on the fixed chat background.
I wouldn't say it looks great now, but it's somewhat readable now, and looks fine in overhead text and on transparent chat backgrounds.

P.S. The image is not resized to allow for a row of shadow pixels below the emoji as that offset from the image resizing looked wrong in chat.

### CODE REVIEW

**Comment by Cyborger1** [comment]
I made some alternate utensil emojis if you want to consider these

fork_and_knife
spoon

**Comment by makingcomment** [comment]
Maybe a full border would be better? In the image you posted, the right side looks good but the left side is very hard to see.

**Comment by Nightfirecat** [comment]
I did compare with a full border, and it sadly looks very bad that way

**Comment by Nightfirecat** [comment]
I've replaced the images with those provided by @Cyborger1 as they look significantly better than my proposal

**Comment by Nightfirecat** [comment]
One last update to use a less wonky fork graphic and add shadowing to the utensils similar to the knife:

spoon
fork and knife
cutlery on fixed chat background
cutlery on transparent chat background

**Pull request merged**
