### PR TITLE
Menu Entry Swapper: Barbarian Assault QoL

### PR DESCRIPTION
**Pull request by dar097**
Features(sorted by configs):
1. Barbarian Assault Horns (default: true)
- Makes the first option on your horn always the one that you are suppose to call.
2. Barbarian Assault Helper (default: false)
- Global: Hides most interactions that are unnecessary for your role, such as non collectors having "take" option on eggs or non attackers having "attack" option on fighters/rangers.
- Healer: Healing vial only useable on players, Poisoned foods only usable on penance healers.
- Collector: Take option only available on the called egg color to pick.

---

Other:
added a remove method that can be used to remove menu entries.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
FYI I believe some of these features used to exist in the client and were removed at Jagex's request.

**Comment by MattyJacques** [comment]
@Nightfirecat I didn't see anything about this on rejected features wiki page

**Comment by Abextm** [comment]
We had a feature like this before, but we removed it on our own, worrying that it was too OP.

**Comment by Nightfirecat** [comment]
@MattyJacques 

> Barbarian Assault Plugin: Left-click calling removed (see #859)

This would be (1) from this PR.

I believe all items under (2) from this PR would be fine.

**Comment by deathbeam** [comment]
Yeah we dont want to add either of this features. 1. entry hiding is bad. 2. left click call was determined OP.

**Pull request closed without merging**
