### PR TITLE
Added ability to toggle on/off the item weight tooltip in the Item Status plugin.

### PR DESCRIPTION
**Pull request by Adelaidian**
Added ability to toggle on/off the item weight tooltip in the Item Status plugin.

### CODE REVIEW

**Comment by raiyni** [comment]
This needs to be ran through the formatter

**Comment by Adelaidian** [comment]
> 
> 
> This needs to be ran through the formatter

Fixed the formatting issues and have now commited them 👍

**Comment by Adelaidian** [comment]
Finally fixed all formatting/style issues.

**Comment by xdesr** [comment]
As previously stated, duplicate #6977

**Comment by Adam-** [comment]
Added in #6977

**Pull request closed without merging**
