### PR TITLE
Further deobfuscate the RuneScape client

### PR DESCRIPTION
**Pull request by rbbi**
Rotation added to Actor,
Base37 decoding/encoding,
Skills & Experience

### CODE REVIEW

**Comment by Joshua-F** [comment]
Any method you rename has to be marked with `@Export` otherwise it means nothing.

**Comment by rbbi** [comment]
Will add `@Export` annotations

**Comment by MESLewis** [comment]
Parameters will not be renamed either. I was working on adding parameter support to the mapper but I haven't had time recently. Hopefully this summer I'll get it working and we can start having meaningful parameter names.

**Comment by deathbeam** [comment]
Deobfuscated client was removed.

**Pull request closed without merging**
