### PR TITLE
 highlight basalt rocks to lighthouse

### LINKED ISSUE #11721: Agility obstacles of Rellekka Lighthouse
**Is your feature request related to a problem? Please describe.**
The stepping stones from the barbarian outpost -> lighthouse do not have the green agility boxes.

**Describe the solution you'd like**
The correct path on the stepping stones should be pathed with green boxes

image

Using devtools in runelite, I found the right stones and tried to add them in the same style, but I'm new to Java and based on some errors, I'm probably doing something I shouldn't. I believe that these lines should be added to the [Obstacles file](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java) below the additions for Prif.

```
		// Rellekka lighthouse
		BEACH_4550, BASALT_ROCK_4551, BASALT_ROCK_4552, BASALT_ROCK_4553, BASALT_ROCK_4554,
		BASALT_ROCK_4555, BASALT_ROCK_4556, BASALT_ROCK_4557, BASALT_ROCK_4558, ROCKY_SHORE_4559
```

### PR DESCRIPTION
**Pull request by JackRMartin**
close #11721 

image
[](url)

### CODE REVIEW

**Review by Nightfirecat — COMMENTED** [review]
These aren't really shortcuts. I'd prefer if this followed the approach of #11723

**Comment by JackRMartin** [comment]
> These aren't really shortcuts. I'd prefer if this followed the approach of #11723

The official Wiki lists them as shortcuts. https://oldschool.runescape.wiki/w/Shortcuts (3rd row). 

They seem to fit more as a shortcut, than as part of an agility course.

**Comment by Nightfirecat** [comment]
We're not really following the wiki's naming convention of agility obstacles/shortcuts/etc. If you'll refer to the PR I linked to, I didn't suggest denoting them as an agility course, I suggested putting the object IDs into `Obstacles` rather than `AgilityShortcut`. There's neither world map icons nor agility level requirements for these objects, so there's not really any purpose to define them individually in `AgilityShortcut`.

**Comment by Adam-** [comment]
added in 91bac5821a1adb172157bd45e2f0d6eae7185b04

**Pull request closed without merging**
