### PR TITLE
Add /OSRS client in name

### PR DESCRIPTION
**Pull request by gregh203**
At the begining of the file it says for runescape 2 when it is also called Oldschool Runescape

### CODE REVIEW

**Comment by Bartvhelvert** [comment]
Shouldn't it be just OSRS then?

**Comment by gregh203** [comment]
Do both so it pleases more people.

**Comment by Adam-** [comment]
Probably just "Old School RuneScape" is best. It matches the GitHub description.

**Comment by deathbeam** [comment]
The README was updated

**Pull request closed without merging**
