### PR TITLE
Add Equipment Inspector plugin

### PR DESCRIPTION
**Pull request by sean-duffy**
This plugin adds a "Inspect Equipment" option to the right-click player menu which opens a side-panel displaying the equipment that player currently has equipped.

[demo](https://gfycat.com/FantasticSnappyGrison)

I often find myself seeing some gear or some nice fashionscape and wondering what that player was wearing but I'm not able to find out because the player is afk or has public chat off. So I decided to create this plugin to address that issue.

I posted this in the Discord and received feedback that it could be potentially OP for PKing, particularly as it's possible to see item charges, durability for barrows armour etc. This could maybe be addressed by hiding charge/durability info or adding code to disable it in the wilderness. I'd be interested to hear other thoughts on this, as I myself am not a PKer so I'm not fully aware of how the plugin would be advantageous in those scenarios.

~~The plugin seems to work most of the time, but quite often it seems that players which are loaded and on screen are missing from the player cache and therefore the plugin is unable to get their equipment. Would be grateful if anyone could offer any guidance on this, not sure why this is happening.~~ **Fixed in f63143e**.

The plugin is disabled by default to avoid cluttering the sidebar for players not using this plugin.

### CODE REVIEW

**Comment by ShaunDreclin** [comment]
Small nitpick but I would change "Inspect Equipment" to "Inspect", to match the length of other right click ops on players

**Comment by deathbeam** [comment]
I dont think this plugin should be implemented, seems quite op for e.g scouts when pking.

**Comment by sean-duffy** [comment]
Yeah I abandoned this based on the consensus that it’ll never be added.

On 2 Sep 2018, at 7:37 pm, Tomas Slusny <notifications@github.com<mailto:notifications@github.com>> wrote:


I dont think this plugin should be implemented, seems quite op for e.g scouts when pking.

**Comment by ShaunDreclin** [comment]
Is it really that op though? It doesn't give you any info you cant get just by looking at the person. (As long as items with charges are all displayed as the fully charged version)

**Comment by deathbeam** [comment]
Well sometimes you can't see stuff like dboots under void etc, happens with plethora of items

**Comment by Unmoon** [comment]
IMO this is fine and the pros outweigh the cons, especially since it doesn't count risk and can't show ring and arrow slot. Most of the time people have switches in the wilderness, anyway.

**Comment by deathbeam** [comment]
Hmm maybe, its hard to evaluate. Either way, if we would decide to implement this imo it should be part of the hiscore plugin with just icons and names as tooltips probably.

**Comment by Unmoon** [comment]
I would like to see the official equipment interface (or similar in-game interface) be used for this, to be honest. Sidebar feels like the wrong place for this.

**Comment by deathbeam** [comment]
Ah right, yeah that would be even better

**Comment by Janzzze** [comment]
What if you could disable the feature in the wilderness and pvp worlds?  
this would prevent using it to see boots under void, quickly easily determine someone's risk and scouting.  
Checking if player is logged in to a pvp world should be doable, but no idea if you can check if other player is in the wilderness while localplayer is not to prevent it being abused from the other side of the ditch.

**Comment by Nightfirecat** [comment]
Now that [the plugin hub has been created](https://github.com/runelite/plugin-hub), this is a plugin which would be well-suited for inclusion there.

That aside, is the HEAD KitType change still valid?

**Comment by botanicvelious** [comment]
added to pluginhub https://github.com/runelite/plugin-hub/pull/105

**Pull request closed without merging**
