### PR TITLE
Add wilderness canoe icon to world map

### LINKED ISSUE #9339: Add icon for waka canoe wilderness diesmbark station
The title says it.

Tooltip could include wilderness level.

### PR DESCRIPTION
**Pull request by dekvall**
The wilderness canoe works like a portal teleport as it
is a one way transportation. I opted to use the normal transportation
icon in order to stay consistent with the other canoe stations,
though with a clarifying tooltip that no departures are to be made.

waka-canoe

Closes #9339

### CODE REVIEW

**Comment by Adam-** [comment]
Does this make sense if you can't actually travel from here?

**Comment by dekvall** [comment]
I can only speak for myself, but I have searched for the wilderness pond by looking for a canoe icon a numerous times. So it felt nice to add one. I feel it makes sense to keep it consistent with the other icons, even if you can't travel from there.

**Comment by deathbeam** [comment]
Needs rebase

**Comment by dekvall** [comment]
Done.

**Pull request merged**
