### PR TITLE
3920 hiscores lookup bug

### PR DESCRIPTION
**Pull request by ScottMCarr**

### CODE REVIEW

**Comment by Adam-** [comment]
I cannot reproduce the original issue of #3920

**Comment by ScottMCarr** [comment]
I could not either, so I believe it might be system dependent. This should fix the issue as it's shown in the image however without changing the functionality for anyone else as well.

**Comment by pettenge** [comment]
I still run into the bug with this change if I type characters in quick succession (basically pressing the keys the same type).

**Comment by Adam-** [comment]
Fixed in 30c3ce9dc17f799aec59a177d82360becf6a664b

**Pull request closed without merging**
