### PR TITLE
disable left click for placeholders bank button

### LINKED ISSUE #14961: Add 'Disable left-click' for the placeholder toggle
This added config should work the same way as the ones for depositing your inventory or equipment do--when enabled, left-clicking the "Toggle placeholders" button (with the :lock: symbol) should force a minimenu to pop up.

---

### Discussed in https://github.com/runelite/runelite/discussions/14943

<div type='discussions-op-text'>

<sup>Originally posted by **Memebeams** May 12, 2022</sup>
Currently, the bank plugin allows you to avoid accidental deposits by disabling left-click on deposit buttons:
image

Sometimes, I will remove items from my bank without realizing that the placeholder button was turned off and mess up my bank arrangement. This button would make it harder for dingbats like me to turn placeholders off</div>

### PR DESCRIPTION
**Pull request by orange-puff**
Closes #14961

### CODE REVIEW

**Review by OAGallo — APPROVED** [review]

**Review by Nightfirecat — CHANGES_REQUESTED** [review]
As written, this causes the right-click menu to be forced in places which are not the bank. An easy-to-access example is the scroll wheel zoom button in the settings menu. This should only apply while in the bank.

**Comment by orange-puff** [comment]
I've tested this and it appears to work, but this looks like a cleaner way to handle this. https://github.com/runelite/runelite/pull/14997 Maybe they can reopen their PR instead

**Comment by Fiffers** [comment]
I'll reopen once a separate PR of mine is reviewed, don't want to mix them up.

**Comment by Nightfirecat** [comment]
@Fiffers I definitely recommend learning to use git branches so you're not stuck maintaining only a single PR at a time.

**Comment by Fiffers** [comment]
> @Fiffers I definitely recommend learning to use git branches so you're not stuck maintaining only a single PR at a time.

Sounds good 👍

**Comment by Nightfirecat** [comment]
I agree #14977 was the better approach, I've squashed its commits and pushed 1ca54e0f75a519c3fe3dae3761644656082a31e6

**Pull request closed without merging**
