### PR TITLE
Update NPC health data

### LINKED ISSUE #1790: Wrong NPC queried when multiple variations of NPC exist
image

the lvl 135 varient of Rogues are detected by the client as the lvl 15 varient resulting in incorrect hp display. 

Reproduction:
fight the lvl 135 rogues in the northern part of rogue's castle

### LINKED ISSUE #3387: Goblin health in lumbridge
Havent tested with different locations, but it says they have 3 hp when they actually have 5

### PR DESCRIPTION
**Pull request by Kamielvf**
Only NPCs which have an "Attack" option were dumped.
- This updates the NPC health data to include all the NPCs that are in the cache as of the update on [August 09 2018](http://services.runescape.com/m=news/looting-bag-improvements-pid-changes-and-bounty-hunter-targets?oldschool=1).

The health information is gathered from the OSRS Wikia. This might cause some data to be inaccurate if the wiki is missing it or has the incorrect values.
For a list of currently missing NPCs: [missing.json](https://puu.sh/Befao/a874c774d2.json)

Closes #3387
Closes #1790
Closes #4364
Closes #4766

### CODE REVIEW

**Comment by deathbeam** [comment]
Would be nice to have this rebased and merged probably

**Comment by HSJ-OSRS** [comment]
if this gets rebased any raids 1 & 2 monsters should be removed as there hp scales based on party size and would be incorrect for example "7554": 1600, thats olms head and he only has 1600 hp in a solo

**Comment by Kamielvf** [comment]
Updated and removed raids 1/2 NPCs

**Comment by deathbeam** [comment]
Hmm this is still missing stuff like baby dragons and looks like it also has some incorrect data, like Monk lvl 3 should have 5 hp, I think.

**Comment by Kamielvf** [comment]
Oh, I redumped and I forgot that I had to do those baby dragons manually. As for the monk, I loaded the current npc health file we have and then if I could not find the npc on the wiki (monk lvl 3 in this case doesn't exist) it will use the health data from the old file, where it was already incorrect.

I kept track of NPCs it didn't manage to find health for in this file: https://puu.sh/BdjTR/762bdca1b6.json

**Comment by deathbeam** [comment]
Ah alright, seems good then.

**Pull request merged**
