### PR TITLE
Add Barrows loot calculator, puzzle solver, and overlay additions

### PR DESCRIPTION
**Pull request by Infinitay**
- ~~Sends a chat message with the price of your barrows loot~~ Already added in #2239
- Highlights the puzzle answer, _they're simple enough, but now you can click it faster!_
- Moved reward potential onto our `PanelComponent`, _highlights green when at best % for reward_
- Adds a star to the minimap to where the barrows chest is located

Puzzle solver
Reward %
Star on minimap

### CODE REVIEW

**Comment by Infinitay** [comment]
I thought that I posted this already, but I haven't my mistake:

The only _downside_ is that the chat message containing the loot price doesn't appear in the screenshot that gets taken when you open the chest. That's why you see `ItemManager#getItemPriceBatch` passing in `TRADEABLE_BARROWS_REWARDS`. I am attempting to _pre-cache_, if you will and for a lack of better terms, the price in hopes that the message gets sent ASAP. If anything, I might end up changing it to check if the player is in an instanced are and it's barrows, but I don't know if I can region check it because it is barrows (hence `onGameObjectSpawned`).

I really don't want to mess with the screenshot plugin because I don't want it to stop functioning or miss taking a screen shot because while it was waiting for the chat message, the player gets attacked and the interface closes before the screenshot is taken. One _hacky_ work around I can think of is saving a `BufferedImage` or such of the widget and overlaying it ontop of a screenshot **after** the chat message is sent, if possible.

**Comment by MESLewis** [comment]
This needs to be rebased. See https://github.com/runelite/runelite/wiki/Rebasing-your-branch-from-the-May-16%2C-2018-rebase

**Comment by Infinitay** [comment]
Finally got around to rebasing this PR. I removed the reward loot price as it's been added to the client already.

**Comment by Monsterxsync** [comment]
Would love to see the Potential reward feature implemented would solve this issue that i and i assume other players have who play re sizeable in a small window.

[https://www.youtube.com/watch?v=qOvSgj4gK0A&feature=youtu.be](https://www.youtube.com/watch?v=qOvSgj4gK0A&feature=youtu.be)

**Comment by pitchblac23** [comment]
i love this idea makes it a bit easier to enter the doors even tho they are easy to learn unfortunately its no longer working with current update would be nice to see an update or a way to make the puzzle answer show back ive changed the colors and turned the config on and off with no luck

**Comment by Infinitay** [comment]
Closing because #8552

**Pull request closed without merging**
