### PR TITLE
Java2D performance improvements

### PR DESCRIPTION
**Pull request by deathbeam**
- Create compatible BufferedImage for current render device when
creating buffer for stretched fixed mode
- Add configuration flag for enabling/disabling AA

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by devLotto** [comment]
I thought our elements were antialiased, for instance https://runelite.net/img/blog/1.3.1-Release/npc-tag.png where the hull looks like it is antialiased. What makes you think that it doesn't make a difference?

**Comment by deathbeam** [comment]
Ah true. After checking it again, here is how it looks without antialiasing:

screenie

The difference is very subtle, so imo it's still worth to stop enabling the AA for everything to slightly improve the performance.

**Comment by Kamielvf** [comment]
How do the hunter plugin/regen meters look without AA? I think those might use it too.

**Comment by deathbeam** [comment]
screenie

Noticable difference here. Might be worth moving the enabling of the AA to overlays that use it only.

**Pull request closed without merging**
