### PR TITLE
World Map - Split quest name and status from custom icons

### PR DESCRIPTION
**Pull request by Darkkgreen**
Transformed all the quest icons that weren't round, added a new config to turn off custom icons and made it work.

How it looks like:

QuestIcons

Should solve #10144

### CODE REVIEW

**Comment by makingcomment** [comment]
In terms of function, this looks awesome. Thank you for working on this!

(no comment on the code/implementation)

**Comment by raiyni** [comment]
I don't think it makes sense to have a toggle just to show the icons and tooltips separately. Plus these icons make it worse because you can't even see that it's a quest.

**Comment by makingcomment** [comment]
> I don't think it makes sense to have a toggle just to show the icons and tooltips separately. Plus these icons make it worse because you can't even see that it's a quest.

Please see #10144

**Comment by Darkkgreen** [comment]
TBF I guess I forgot to change the size, will do this later today.

@raiyni The overall idea is to discuss, that's why I made this pull request. Keeping all icons round made sense to me. IIRC this is the only icon that is overridden with those flags, making it easier to remember and you can toggle it off anyway.

I could try to make it more readable but I guess it will never be perfect since the icon is really small

**Comment by Nightfirecat** [comment]
I don't have much of an opinion on splitting the tooltip toggle from the quest progress icons, but the proposed new icons are much worse, to the point of being unrecognizable as quest icons in some cases.

**Pull request closed without merging**
