### PR TITLE
Remove duplicate tracking info in fishing/woodcutting overlays

### PR DESCRIPTION
**Pull request by bmoyer**
Resolves issue #501.

This PR removes the tracking of fish/logs and actions/hr from the fishing/woodcutting overlays, as this information is now displayed by the XP tracker and is duplicated in these overlays.

### CODE REVIEW

**Comment by SomeoneWithAnInternetConnection** [comment]
I don't think the MLM info is actually duplicated in the XP tracker? The tracker is counting "XP Drops(/hr)", but MLM is counting "Paydirt(/hr)", which, because washing paydirt also gets you mining XP, aren't the same. I hadn't realized that that issue listed MLM as well, or I'd've said something there, sorry.

**Comment by bmoyer** [comment]
Good call, easy to forget about the washing! Just reverted the MLM plugin changes.

**Comment by zeruth** [comment]
This really feels like it just complicates finding the information, while permanently removing a portion of the game screen while skilling all the time. I would love to see this reverted.

**Comment by deathbeam** [comment]
Idk I feel like it is still out of scope to be there. Maybe updating XP tracker to show trackers in game like Konduit does would be better solution than to have it like this in plugins.

**Comment by Adam-** [comment]
If we make the xp tracker expose actions and actions/hr we could show this still without the duplicated logic

**Comment by deathbeam** [comment]
But that will make plugin dependent on the another plugin. But global tracking service isnt bad idea as well, the Discord plugin would make use of it probably. I still like the idea of doing what Konduit does more I think, and add configuration to what to show on the on-screen trackers, like show exp bar, show exp/hr, actions/hr etc etc, so then you would be able to replicate the fishing/woodcutting to behave exactly same way (well, instead of fish/hr and fish caught it would be actions/hr and actions) and have it generalized for every skill, what would be neat.

**Comment by Adam-** [comment]
I think that there is nothing wrong with having well defined plugin dependencies. We just don't have any of them now.

**Pull request merged**
