### PR TITLE
Shift click customization

### LINKED ISSUE #799: Shift Click Reorder
Option to change the shift click option to one of the other options. 
Ex. Use Pouch ---> Empty Pouch

Extremely powerful function currently utilized on OSB/Konduit

### LINKED ISSUE #980: switch "teleport" and "teleport to POH" on construction cape?
Hi, i don't think many people actually use the teleport option on the construction cape, so could the options maybe be switched?

Regards, Cara

### PR DESCRIPTION
**Pull request by Kamielvf**
[Preview](https://puu.sh/zPKig/b77c7c4f0a.gif)

This plugin allows the user to set their own shift-click actions on (inventory) items.

- Removed the teleport/blessed sickle option from Menu Entry Swapper plugin since it is now redundant.
- Enabled the Menu Entry Swapper plugin by default, with some general options toggled
- Added WidgetInfo for the inventory tab stone

Fixes #799
Fixes #980

### CODE REVIEW

**Comment by ShaunDreclin** [comment]
fffffff I thought you were making this a separate plugin! Oh well, gonna have to merge my changes into this one then

**Comment by Kamielvf** [comment]
Fixes #980 
Fixes #1062

**Comment by Adam-** [comment]
1) inject a field into itemcomp for shift click index
2) replace shiftClickActionIndex with logic to account for injected field
3) hook ItemComposition#post to fire an event to populate shift click index

**Comment by alex-vincent** [comment]
This looks incredible, I really hope jagex is ok with this!

**Pull request merged**
