### PR TITLE
Use "Un-tag" and "Unmark" menu options for tagged NPCs and marked objects/tiles

### PR DESCRIPTION
**Pull request by Nightfirecat**
Closes runelite/runelite#1177

### CODE REVIEW

**Comment by deathbeam** [comment]
Can this be also extended for object markers etc?

**Comment by Nightfirecat** [comment]
Added a commit to make a similar change in the object markers plugin.

**Comment by Nightfirecat** [comment]
Added another commit for ground markers while I was at it.

**Comment by deathbeam** [comment]
Needs rebase

**Pull request merged**
