### PR TITLE
Add 2006 interface

### PR DESCRIPTION
**Pull request by raqes**
## Usage
This will add the 2006 interface for the fixed viewport for those who like era when there was combination between 2007 and 2005.

Lastly it will increase the 2005 inventory icon size to match the way it was in 2005, similar to the way the 2006 inventory icon is bigger.

### 2005 interface before
runelite_2018-05-27_19-46-09

### 2005 interface after

Closes runelite/runelite#7581

### CODE REVIEW

**Comment by MESLewis** [comment]
You should separate the two changes in this PR into two logical commits.

**Comment by UGot0wnedBS** [comment]
How would we get this into the client? I have it created. Would be nice to have it in the main RuneLite Client.

https://i.imgur.com/Nn3YS6U.png

**Comment by Palidino** [comment]
If this ever ends up being added I'd like to recommend the tab icons I've included. They more accurately reflect the correct locations for the icons as they were in 2006 (OP's icons aren't quite in the right spots on the tabs). See @UGot0wnedBS picture (icons I've included are those) to this picture of RS (https://img.fireden.net/vg/image/1463/39/1463390620282.png). It also includes the minimap sprite fix from #3501 and colored quest and magic tab icons (needs the raids icon).
[2006.zip](https://github.com/runelite/runelite/files/2161429/2006.zip)

**Comment by deathbeam** [comment]
It was not, we have 2005 and 2010

**Comment by aqquartz** [comment]
Please add this ^

**Comment by UGot0wnedBS** [comment]
Bumping this as maybe we can get this into the client.

If someone needs the images, I have a folder with the icons. https://i.imgur.com/92llFII.png

**Comment by Adam-** [comment]
I think the part of this which fixed the 2005 inventory icon has since been done. If someone wanted to rebase this with just the 2006 skin I wouldn't mind looking at it again.

**Comment by UGot0wnedBS** [comment]
Lovely bump D:

**Comment by Nightfirecat** [comment]
I'm working on rebasing this. Due to a busy weekend, I only expect to have this ready by Sunday

**Comment by Nightfirecat** [comment]
I've rebased this and tested the 2006 interface ingame and can confirm it looks "correct". (that is, it doesn't have any wonky positions that I can see)

**Comment by UGot0wnedBS** [comment]
> I've rebased this and tested the 2006 interface ingame and can confirm it looks "correct". (that is, it doesn't have any wonky positions that I can see)

Hope to see it soon :D

**Pull request merged**
