### PR TITLE
Fix hover inconsistency in screenmarker plugin

### PR DESCRIPTION
**Pull request by MagicfTail**
Thanks to FluffyRabbit for the image

### CODE REVIEW

**Comment by MagicfTail** [comment]
https://i.imgur.com/y3VyBhU.gifv

**Comment by Nightfirecat** [comment]
Isn't this new icon just a darker version of the existing icon? Use `ImageUtil.grayscaleOffset` for that instead of adding a new file.

**Comment by MagicfTail** [comment]
I assumed there was a reason that would work since fill_colour_icon is going the same thing, i'll look into it if it there isn't.

**Comment by deathbeam** [comment]
Any update on this?

**Comment by MagicfTail** [comment]
You can maybe get the exact same colour if you tinker a lot with it 🤷‍♀️ , but I couldn't get it the exact same

**Pull request closed without merging**
