### PR TITLE
Update menu swapper for birdhouses

### LINKED ISSUE #1379: Birdhouse left-click Empty.
Hello, a menuswap to left-click Empty birdhouses would be nice. Current left click `option` is Interact.
74ad61f897a3be61850fff14ecce919f

### PR DESCRIPTION
**Pull request by shmeeps**
Add option to swap "interact" with "empty" on birdhouses

Fixes #1379

### CODE REVIEW

**Comment by shmeeps** [comment]
Going to look at putting #1602 in here as well

**Comment by shmeeps** [comment]
Updated to address both #1379 and #1602

**Comment by shmeeps** [comment]
Update to address #1821 and #2806 as well

**Comment by Adam-** [comment]
Preferably, this would be four separate commits.

**Comment by shmeeps** [comment]
Reduced down to just the birdhouse options

**Pull request merged**
