### PR TITLE
Plug-in: Custom cursors (Resolves #2068)

### LINKED ISSUE #2068: Custom cursors
Is it possible to add custom cursors like osb/konduit has? Not a major update, but it just feels much better when your ingame cursor is different from normal mouse pointer.

### PR DESCRIPTION
**Pull request by Kruithne**
Adds a custom cursor plug-in, allowing uses to select from a variety of cursors. To begin with I only added a few cursors that I had seen requested; more can easily be added. Some examples below.

runelite_2018-05-11_21-52-36
runelite_2018-05-11_21-52-48
runelite_2018-05-11_21-52-55

These can be configured under the "Custom Cursor" plug-in settings. This PR resolves https://github.com/runelite/runelite/issues/2068

### CODE REVIEW

**Comment by deathbeam** [comment]
I don't think this should be implemented. Also, this either do not works at all or do not works properly outside of Windows, at least from my experience with OSB, what probably does same thing.

**Comment by Kruithne** [comment]
As requested by @deathbeam: Updated to be disabled by default. The default cursor will now be RS3 Gold when enabled, and the cursor will be reset to the system default when the plug-in is disabled.

**Comment by Adam-** [comment]
Having the ability to give it a custom cursor image might be neat. What is with the padding on the right hand side of the images?

**Comment by Kruithne** [comment]
Java requires, at least for most operating systems (Mac appears to be a little more lenient) that the images are 32x32. Anything else will be stretched to that, and causes distorted graphics.

**Comment by dappersnapper456** [comment]
can you add .ani files please. I just got a custom animated cursor working on mac with mousecape and was hoping you could add .ani support in your plugin?

**Comment by Kruithne** [comment]
Updated to work after the apocalypse.

**Pull request closed without merging**
