### PR TITLE
Improper highlighting of Yanille north wall shortcut fix

### LINKED ISSUE #8441: Agility Plugin: Yanille north wall shortcut highlighting improperly
**Describe the bug**
Two ends of the same agility shortcut are highlighted with different colors. (I am able to travel through it in both directions no problem)

**Screenshots**
screenshot

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.19-SNAPSHOT

### PR DESCRIPTION
**Pull request by ksergio39**
close #8441

### CODE REVIEW

**Comment by Adam-** [comment]
@ShaunDreclin can you check this?

**Comment by ShaunDreclin** [comment]
I don't think so, I'm out of the range of affected agility levels now. Somebody between 16 and 39 should test it. It should work though, seems like the issue was just mixing up the two Yanille shortcuts.

**Comment by ksergio39** [comment]
Yeah @ShaunDreclin whoever coded it mixed up the wall ID`s for the two shortcuts.

**Comment by Adam-** [comment]
@ShaunDreclin you can use `::setstat` to test this.

**Comment by ShaunDreclin** [comment]
Ohh right I forgot about that. Tested, this fixes it

**Pull request merged**
