### PR TITLE
Change logged-in redir to redirect to HTTPS

### PR DESCRIPTION
**Pull request by deathbeam**
Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Is there a reason we don't redirect all pages to https?

**Comment by deathbeam** [comment]
We do. But this should still point directly to https version.

**Comment by deathbeam** [comment]
@Adam- do you have https redirect handled in RL oauth app?

**Comment by Adam-** [comment]
Seems so https://github.com/runelite/runelite-oauth/blob/master/src/main/java/net/runelite/oauth/OAuthServlet.java#L49?

**Comment by deathbeam** [comment]
screenie

I meant on google apps

**Pull request merged**
