### PR TITLE
Fix MacOS retina support

### PR DESCRIPTION
**Pull request by khogeland**
Turns the viewport scaling back on for MacOS (once the rlawt fix is in)

Depends on https://github.com/runelite/rlawt/pull/2
Fixes https://github.com/runelite/runelite/issues/17575

### CODE REVIEW

**Comment by Adam-** [comment]
How does this affect the screenshot code in Hooks.java:475 (this only runs with GPU off, so maybe nothing?) or ImageCapture.java:116 (this runs regardless I think)

**Comment by khogeland** [comment]
> How does this affect the screenshot code in Hooks.java:475 (this only runs with GPU off, so maybe nothing?) or ImageCapture.java:116 (this runs regardless I think)

I don't think this affects anything that doesn't operate on the AWT/GL context. Screenshots are all high quality and well-aligned with or without the GPU plugin.

**Comment by khogeland** [comment]
Hold on, this still isn't rendering right.

**Comment by Adam-** [comment]
Please don't close and reopen PRs but instead just update this existing PR. If you want to mark it as a draft to show it isn't ready that is fine.

**Comment by khogeland** [comment]
Oh, ok, I see what happened! Maven overwrite my monkey-patched rlawt jar so I was looking at the old behavior, that confused me. Yes, specifically changing the resolution to one _with a different scaling factor_ causes it to misbehave, but it fixes itself when toggling the GPU plugin.

**Comment by Adam-** [comment]
added in 6dcbb05a40a937cfd864cb2efbb70b3a01395803

**Pull request closed without merging**
