### PR TITLE
Opponent freezes

### PR DESCRIPTION
**Pull request by devOSRS**
Added freeze timers similar to Exilent. This is a very rough PR for now. Looking for any constructive feedback.

For example, thinking of maybe using a Guava Cache instead of a map, making more efficient use of FreezeInfo class, better overlay design, etc.

I find this feature extremely useful and it's been heavily asked for! Hopefully we can work together.
Thanks!

### CODE REVIEW

**Comment by devOSRS** [comment]
ref: https://github.com/runelite/runelite/issues/2011

**Comment by devOSRS** [comment]
Very cool!
freeze-timers

**Comment by NathenSample** [comment]
Freeze timers are in the rejected list.
See: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by BrianJMRogers** [comment]
@devOSRS what ever happened to this? I see it in a list of "not being considered" but to me that doesn't mean it can't be added.

**Comment by Trevor159** [comment]
this falls under `Indicates how long an opponent is frozen for` in https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

**Pull request closed without merging**
