### PR TITLE
Supplies Tracker

### PR DESCRIPTION
**Pull request by DWhite72**
Rewrote detection method to use onMenuOptionsClicked and onInventoryChanged.
Everything seems to work fine other than if you quickly(same tick) decant a potion and spam click on the new potion it adds an extra dose to the tracker.

### CODE REVIEW

**Comment by forsco** [comment]
> Zamorak brew shares same event message as saradomin brew so appears as Sara brew.
> Antidotes all share same event message so they all show as antidote++.

Couldn't you just add a check for which item the player is using instead of utilizing chat box messages?

**Comment by DWhite72** [comment]
That would be better I was using what boost tracker. I'll stay rewriting plugin class

**Comment by DWhite72** [comment]
@psikoi @forsco onItemContainerChanged goes off everywhere. If you drop a manta and pick it up it will count as a manta used when dropped and not change when picked up.

**Comment by forsco** [comment]
Check the menu action used on the item

**Pull request closed without merging**
