### PR TITLE
Slayer Streak Bonus point notifier

### PR DESCRIPTION
**Pull request by robinwithes**
Added a chat notification when you are on a slayer streak ending with 9.
This allows the player to easilier switch to duradel for max slayer points
https://github.com/runelite/runelite/issues/5396

### CODE REVIEW

**Comment by forsco** [comment]
This could be improved to compare the local players combat level and slayer level to recommend their highest slayer master available to them and not just recommending Duradel.

**Comment by robinwithes** [comment]
> This could be improved to compare the local players combat level and slayer level to recommend the highest slayer master available to them and not just recommending Duradel.

Yeah i have a checkstyle error anyway. Ill implement it when i get home.

**Comment by deathbeam** [comment]
It should not reccomend any slayer master imo, just send notif that you are on close to 10th slay task

**Comment by robinwithes** [comment]
> It should not reccomend any slayer master imo, just send notif that you are on close to 10th slay task

Ok, ill do that.

**Pull request closed without merging**
