### PR TITLE
spec counter: add sire spawns and scions to ignore list

### PR DESCRIPTION
**Pull request by LlemonDuck**
Since the list is growing a bit, I took the opportunity to also add some comments.

### CODE REVIEW

**Comment by Adam-** [comment]
Is the sire spawns named `Abyssal sire`?

**Comment by LlemonDuck** [comment]
> Is the sire spawns named `Abyssal sire`?

Nope, sorry, that's a typo, should just be `SCION` and `SPAWN`. 

Pushed a fix.

**Comment by Adam-** [comment]
It would be cool if you tested this?

**Comment by LlemonDuck** [comment]
Just tested the current branch tip at Sire, worked for both the spawns and scions there.

**Pull request merged**
