### PR TITLE
Revert "Loot tracker - Add ability to ignore items (#5483)" due to client freezing when hiding large amounts of items

### PR DESCRIPTION
**Pull request by MagicfTail**
https://i.imgur.com/YupZhtu.gifv
Having a feature that can lock up the client for this long is unacceptable

This reverts commit 31d8e88099588a6d4a8e7ab19e275a1f0fd73c13.

### CODE REVIEW

**Comment by deathbeam** [comment]
What if you just comment out <https://github.com/runelite/runelite/pull/6135/files#diff-6a7f2b0ba476897b8e2a6a7c5288ddcfL114>? Did you even tried to debug this?

**Comment by psikoi** [comment]
Did you try finding the reason for the freezing? What's the background, what circumstances does it crash in?

**Comment by psikoi** [comment]
I found the origin issue, you should probably refer to it in this PR.

**Comment by MagicfTail** [comment]
See issue #6134.

This pr might not be the cause of the issue, but it enables a way of freezing the client for many times longer than what was possible before, in a way that would not be unexpected for an actual user to experience (hiding an item with a large backlog of loot already tracked)

**Pull request closed without merging**
