### PR TITLE
Vorkath

### PR DESCRIPTION
**Pull request by Hashes**
Shows the number of attacks before the next special phase, what's the next phase and a warning when a fireball is shot.

### CODE REVIEW

**Comment by LeviSchuck** [comment]
Could you provide screenshots of how this behaves in action?

**Comment by Hashes** [comment]
untitled

Yes, so the first image is when you arrive at vorkath.
The second is when vorkath fires a fireball.
The last one is to show the next phase coming and the text color changing, depending on the remaining attacks. The text will get red when at 2 and less remaining attacks.

**Comment by twoodward1** [comment]
It would be nice if a click-box for the scorpion spawn was added.

**Comment by deathbeam** [comment]
This should use images for the attacks instead of text, in similar fashion as cerb/jad plugin. Also, prbably using animations instead of projectiles would be better.

**Comment by xaviergmail** [comment]
@deathbeam Unfortunately Vorkath only has two attack animations; one for its firebreath / magic ball / ranged attack, and another animation for the fire bomb / zombified spawn / poison pool

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/pull/2689/commits/3a877094988af457f024f3069d30f1951ae9c0e1#diff-e944ecec9125a05f1728cf08074a7e09R40 this PR suggests otherwise.

**Pull request closed without merging**
