### PR TITLE
Add toggle option to show or hide EX label on ground items and bank

### PR DESCRIPTION
**Pull request by filiperoberto**
Added a toggle option to show or hide EX label on ground items and bank. Added some unit tests.

#1479

### CODE REVIEW

**Comment by deathbeam** [comment]
This implementation is pretty weird, having multiple toggles at various places just for hiding 2 characters. There must be better solution. Also, I think the EX should stay at all times anyway.

**Comment by nrodrigues0213** [comment]
What about having it automatically toggle the labels if the user disables the other setting, similar to OSBuddy. Example:
image

**Comment by filiperoberto** [comment]
I like this idea @nrodrigues0212

**Comment by deathbeam** [comment]
Closing as this is very old PR now and has a lot of merge conflicts, reopen if you want to re-implement it.

**Pull request closed without merging**
