### PR TITLE
Add Fight Cave wave overlay

### PR DESCRIPTION
**Pull request by Nightfirecat**
Closes runelite/runelite#3356
Closes runelite/runelite#5885
Closes runelite/runelite#6035

### CODE REVIEW

**Comment by Psyda** [comment]
I'd purpose an additional function. Keep Jad's Spawn marked.

**Comment by mwalker55** [comment]
Fight Caves plugin was removed yesterday.  This doesn't seem overpowered when compared to the Jad prayer helper.

**Comment by g9fam** [comment]
#Bringbackjadplugin

**Comment by mwalker55** [comment]
Ha, I do feel like the Jad plugin was somewhat abruptly removed by Adam despite a lack of clear consensus from the community on it but I understand his misgivings.

**Comment by 7ib** [comment]
hi i am partially deaf and the only way that i was able to face jad was using this plugin, i did not yet get to defeat him. is there going to be a plugin for fight caves coming in the future?

**Comment by ArmaLite15** [comment]
This is awesome

**Comment by robinwithes** [comment]
> 
> 
> I'd purpose an additional function. Keep Jad's Spawn marked.

This would actually be a pretty good feature.

**Comment by Mycrawsbow** [comment]
dont expect anything useful for fight caves to many people wanted to whine about a good thing

**Comment by Nightfirecat** [comment]
@Mycrawsbow As I said before, please keep discussion on this PR on-topic. I was part of the collective who was interested in the jad prayer plugin being removed.

**Comment by Trevor159** [comment]
This would be a good plugin-hub feature imo.

**Comment by Nightfirecat** [comment]
I've submitted this as an external plugin at runelite/plugin-hub#125

**Pull request closed without merging**
