### PR TITLE
TimeTracking: Add support for intuitive time notations like "1h 30m 10s"

### LINKED ISSUE #4921: Timers plugin should accept "0h", "0m", and "0h00m" style lengths for timers and stopwatches
**Is your feature request related to a problem? Please describe.**
When creating timers and/or stopwatches, you must specify a colon-separated length of time: "hh:mm:ss". This format is lengthy and is not easy to type (pressing and releasing shift to enter `:` between numbers)

**Describe the solution you'd like**
It would be more convenient and intuitive to input something like "2h" instead of "2:00:00", or "15m" instead of "15:00". This type of time specification is used across numerous sites (Youtube and Twitch for video timestamps, for instance) and is much easier to type.

### PR DESCRIPTION
**Pull request by jamyc**
Fixes #4921 

- Tries to parse the input using the ISO-8601 Durations format if it contains either `h`, `m` or `s`, else it defaults to the `hh:mm:ss` logic
- Supports notations like:
  - 1h 30m 20s
  - 1h30m20s
  - 3000s
- Does **not** support notations like:
  - 20s 20m

### CODE REVIEW

**Comment by Nightfirecat** [comment]
This seems like another opportunity to write some tests. Functionality looks good though! :+1:

**Comment by deathbeam** [comment]
Do you want to work on the tests @jamyc? I am fine merging this either way

**Comment by jamyc** [comment]
I'm afraid I won't be able to find time to do this in the upcoming days. I could submit a separate PR later this week with some tests.

**Comment by deathbeam** [comment]
Sounds good.

**Pull request merged**
