### PR TITLE
Fix loot tracker order on client reload

### LINKED ISSUE #9575: LootTracker: Loot Drops From Server are in Reverse Order
**Describe the bug**
When reloading the client the drops that are loaded from prev sessions are in reverse order

**To Reproduce**
1. switch loot tracker to individual kill
2. Kill a mob
3. kill another mob
4. restart runelite
5. open loot tracker and see drops have been reversed

**Expected behavior**
the loot tracker should always have the same order of drops

**Screenshots**
Kill Order: 
rabbit -> guard -> guard

Loot Tracker before reloading runelite:
image

Loot Tracker after reloading runelite:
image

Loot Tracker after killing imp after reload:
image

Expected:
(top -> bottom)
imp -> guard -> guard -> rabbit

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.30.1
 - Launcher version: 1.6.0

### PR DESCRIPTION
**Pull request by dekvall**
The panel is currently rebuilt with the earliest loots at the top.
For consistency's sake it should be the other way around.

Closes #9575

### CODE REVIEW

**Comment by Adam-** [comment]
`LootRecord` has a time, maybe it would be better to just do a sort by that?

**Comment by dekvall** [comment]
It's sorted by time in the when selected from the database though, so the result would be the same.

**Comment by Adam-** [comment]
Yeah but it would be less error prone to not rely on that. If we did, we could just reorder it in the query?

**Comment by dekvall** [comment]
I guess I just don't see a case where the query for the last N monsters killed would not rely on time.

**Comment by deathbeam** [comment]
I would just order this by time field on record like @Adam- said.

**Comment by dekvall** [comment]
Alright, will do.

**Comment by dekvall** [comment]
Updated to sort by timestamp instead of reversing

**Comment by deathbeam** [comment]
I think we set the time to -1 intentionally before, but I dont remember why :/

**Comment by Adam-** [comment]
It looks to me like `timestamp` isn't actually used? It was added in 4dd8322121e190cca16a22f0a865ecf721b36223 but I don't see it used there either..

**Comment by Adam-** [comment]
Can we just sort the `LootRecord` instead and then remove this timestamp field?

**Comment by dekvall** [comment]
Sorted the `LootRecord` entries and removed the timestamp field from `LootTrackerRecord`.

**Pull request merged**
