### PR TITLE
poh: Fix Altar of the Occult ID

### LINKED ISSUE #11868: Player owned house - Spellbook altar not showing
When you go to player owned house settings, you can click which stuff you want to show up on the minimap and the spellbook altar does not work for some reason.

1. Go to "configuration"
2. Click on "player owned house"
3. Scroll down to "show spellbook altar" and turn it on
4. It should show it on the minimap like it shows all other options in the "player owned house" but it doesn't 

 - OS: Windows
 - RuneLite version: 1.6.18.1
 - Launcher version: 2.1.0

### PR DESCRIPTION
**Pull request by Broooklyn**
`Show Spellbook altar` now properly displays an icon for the Altar of the Occult.

Screen Shot 2020-06-10 at 2 45 32 PM

Closes #11868

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The commit body should explain why this change is being made--that is, that the null object listed is used because it is a multiloc and is the only one which is seen spawning.

**Comment by Justleaved** [comment]
Im sorry to bother again but it still doesn't seem to show up for me? I deleted everything runelite or runescaped related off my pc and reinstalled it. I don't know what else it could be?

kind regards,

"Just Leave"

**Comment by Broooklyn** [comment]
@Justleaved You will need to wait for this code change to be merged, which will hopefully happen by next week's release. As it stands currently, the change is not in the release version of RuneLite.

**Comment by Justleaved** [comment]
oh i see sorry im not that good with all of this ;P

thx for your help! ;)

**Pull request merged**
