### PR TITLE
Add quest filtering plugin

### PR DESCRIPTION
**Pull request by Eadgars-Ruse**
https://streamable.com/ki0sc

This plugin allows for users to filter their quest list by type (f2p, members, & miniquests), as well as by progress status (completed, in progress, and not started). Any combination of the 6 filtering options is valid.

The filtering is done during the initialization of the quest list widget (script 1350.rs2asm AKA QuestListInit.rs2asm) and during the initialization of each quest list section (script 1351.rs2asm AKA QuestListItemInit.rs2asm). A side effect of this is that the quest list must be reinitialized in order for configuration changes to be applied. This can be done simply by switching to the achievement diary list and back to the quest tab list. Whenever a quest list filter is changed through the configuration menu, a text panel will appear and give reinitialization instructions to the user. Once the list is reinitialized, the text panel will disappear and the selected filters will have been applied.

### CODE REVIEW

**Comment by Adam-** [comment]
Is there a reason why you went with script modification instead of hiding the widgets? The scripts are rather fragile and this will break everytime a new quest is added etc.

**Comment by raqes** [comment]
I got a prototype for filtering quests that doesn't use RS2ASM scripts, but I think using a RS2ASM script is the way to go to do this. Because the it's not working well on resizable with side-panels and to make it decent on resizable I have to use GameTicks to update the widget. Lastly the slider won't adept as nicely. See https://github.com/raqes/runelite/tree/quest-hider

**Comment by Eadgars-Ruse** [comment]
I initially tried to do this by hiding widgets and changing positions around, but it seemed like there wouldn't be a clean way to do it. The quest list is split up into three separate widgets and a lot of the widget children - the quests - are out of order, so computing which quest list item goes where based on whats hidden would be a very messy calculation. And as raqes mentioned above, the scroll bar doesn't update nicely outside of the script.

The plugin would break whenever a quest is added, but the fix is pretty simple. Script 1351 hasn't been updated in the past 6 months, and based on the logic I can't think of any reason they would need to change it, so hopefully that wouldn't be a concern. And Script 1350 just has some hardcoded values updated whenever a quest is added. The ints holding the number of quests would have to be incremented by 1 and line at the bottom would have to be added for the new quest identifier.

**Comment by Gamer1120** [comment]
I love this addition! I have a small suggestion though. Isn't it possible to do this "live", such that a click on a checkbox in the plugin would immediately update the list? I would reckon that the list of quests on the screen is stored somewhere.

**Comment by Eadgars-Ruse** [comment]
Thanks! 

So the reason the changes don't update live is because the filtering is done within the code that the client runs whenever it initializes the quest list. The initialization script - 1350.rs2asm - has to be invoked in order for the filtering to be done. I know that script gets run every time the user switches back and forth between the diary list and quest list, so I thought that'd be a good way for it to get updated. 

A better way would be to invoke the script directly, but not knowing what parameters are needed for the invoke makes that tricky.

**Pull request closed without merging**
