### PR TITLE
timers: add farmer's affinity effect timer

### PR DESCRIPTION
**Pull request by SirWrain**
Enhancement on the timers plugin to add the Farmer's Affinity effect timer (going through wheat faster in Puro-Puro).

image

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Needs rebase

**Comment by Nightfirecat** [comment]
I'll review this if/when #16074 is merged, as it will simplify this PR's changes significantly.

**Comment by Nightfirecat** [comment]
I've rebased and rewritten this change as https://github.com/Nightfirecat/runelite/commit/5021e6db9ff63c6d54481151be6307840bfce6c1, can you test to make sure that commit works as expected? It seems to work fine for me.

**Comment by SirWrain** [comment]
Your commit works as expected on my end too! 👍 @Nightfirecat

**Comment by Nightfirecat** [comment]
Added in 5021e6db9ff63c6d54481151be6307840bfce6c1, thanks!

**Pull request closed without merging**
