### PR TITLE
runelite-client: Open window after plugins are started

### PR DESCRIPTION
**Pull request by Abextm**
#3668 reordered client startup to show the window before plugins are loaded, which makes the client startup about 600ms slower. Moving pack() later also gives us a noticeable improvement in startup time, totaling roughly 1000ms

### CODE REVIEW

**Comment by deathbeam** [comment]
600ms is not much when you have visual indicator sooner instead. But, simple reorder of the startup sequence causing slower startup do not makes much sense, any idea why that happens?

**Comment by Abextm** [comment]
I would assume its mostly redraw and relayout

**Comment by Abextm** [comment]
And #3497 is a much better way to show that something is happening than showing a partially built UI.

**Comment by deathbeam** [comment]
The only redraw happening should be sidebar and that one should be only partial and there should be no relayout, so that is kind of weird. Maybe but showing client ui sooner was less effort.

**Comment by Abextm** [comment]
I don't think moving the code to where it was before is much effort, and
even if it was more complicated that copy and paste I think it would still
be worth it.

**Comment by deathbeam** [comment]
No i mean showing the ClientUI sooner is less effort than adding loading screen :d Anyway, I tried this and its working, maybe it would solve the issue instead of partially reverting the change? 

```diff
diff --git a/runelite-client/src/main/java/net/runelite/client/ui/ClientPluginToolbar.java b/runelite-client/src/main/java/net/runelite/client/ui/ClientPluginToolbar.java
index fb7a112607..8e7c7b6539 100644
--- a/runelite-client/src/main/java/net/runelite/client/ui/ClientPluginToolbar.java
+++ b/runelite-client/src/main/java/net/runelite/client/ui/ClientPluginToolbar.java
@@ -66,7 +66,6 @@ public class ClientPluginToolbar extends JToolBar
                                add(component, index);
                        }

-                       revalidate();
                        repaint();
                }
        }
@@ -78,7 +77,6 @@ public class ClientPluginToolbar extends JToolBar
                if (component != null)
                {
                        remove(component);
-                       revalidate();
                        repaint();
                }
        }
```

**Comment by Abextm** [comment]
It still needs to be revalidated for when plugins add panels after startup

**Comment by deathbeam** [comment]
Well i tested adding panels after startup and it works even without revalidation,

**Comment by deathbeam** [comment]
Both #4479 and this PR have approximately same effect for me:

```
2018-07-24 19:06:23 [main] INFO  net.runelite.client.RuneLite - Startup time 2413
2018-07-24 19:06:35 [main] INFO  net.runelite.client.RuneLite - Startup time 2395
2018-07-24 19:06:45 [main] INFO  net.runelite.client.RuneLite - Startup time 2228
2018-07-24 19:06:56 [main] INFO  net.runelite.client.RuneLite - Startup time 2379
```

Both are measured using simple diff between 2 times in RuneLite in affected area:

```diff
+import java.time.Duration;
+import java.time.Instant;
 import java.util.Locale;
 import javax.annotation.Nullable;
 import javax.inject.Provider;
@@ -240,6 +242,8 @@ public class RuneLite
                // Load the session, including saved configuration
                sessionManager.loadSession();

+               Instant start = Instant.now();
+
                // Initialize UI
                clientUI.init(this);

@@ -275,6 +279,9 @@ public class RuneLite

                // Show the window
                clientUI.show();
+
+               Instant end = Instant.now();
+               log.info("Startup time {}", Duration.between(start, end).toMillis());
        }
```

**Pull request closed without merging**
