### PR TITLE
Limit the amount of stat boosts that can be shown at a time.

### PR DESCRIPTION
**Pull request by ThatGamerBlue**
GIF of the feature

### CODE REVIEW

**Comment by deathbeam** [comment]
I don't think this is useful at all, as you have 0 control on what is shown. The disabling of skill boosts is enough.

**Comment by ThatGamerBlue** [comment]
I think it's useful specifically at KBD because it drains all of your stats and makes the overlay go crazy, so instead of disabling it completely you can show a few. If you have any suggestions to how to cleanly add a config option to prioritize skills I'll add it.
I don't want to do this in the config:
skill one: <enum>
skill two: <enum>
etc

**Comment by GSchuringa** [comment]
How about a comma separated list in the form of a text input like used in the Ground Items plugin to hide or hightlight specific items?

**Comment by ThatGamerBlue** [comment]
@GSchuringa I like that idea. Anyone got any opinions on that one?

**Comment by deathbeam** [comment]
You can disable the skill boosts and then it will be just showing combat boosts being decreased at KBD. That will not make the overlay go crazy. As I said, there is no reason for this change.

**Comment by ThatGamerBlue** [comment]
Seeing as you clearly don't like it, I'll close this. I will say you can be a little more tactful however.

**Pull request closed without merging**
