### PR TITLE
Instance map: Open using shift+esc keybind

### PR DESCRIPTION
**Pull request by Kamielvf**
Enables the use of the `shift`+`esc` keybind to open up the instance map.

### CODE REVIEW

**Comment by Adam-** [comment]
Where did this keybind come from? What do other clients use?

**Comment by winterdaze-rs** [comment]
I don't think konduit has a keybind for opening instance map. Not sure about osb/runeloader. shift+esc seems like a nice option since it can be done with one hand and esc alone already closes the map

**Comment by Kamielvf** [comment]
Yeah, I don't know if runeloader has a shortcut but OSB/konduit don't. I figured shift+esc is easily pressed with one hand, but also not likely to be pressed on accident.

**Comment by deathbeam** [comment]
I believe with latest NPC indicators additions, using shift as modifier makes sense here, so our modifiers currently are only ALT and SHIFT (when alt cannot be used or do not makes sense).

**Pull request closed without merging**
