### PR TITLE
ToB Damage Counter

### PR DESCRIPTION
**Pull request by akarhi**
The plugin counts the damage you have done and will add in the extra healing the boss have done to itself. After the fight or after your death it will print out a message the amount of damage you have done in % form. Along with that it has an option to change the raid party setup to 3 to 5 man and few chat message to appear or not. The default value is 4 (group members in total) since its the most common group to do

Might include the total amount of damage you have done to the boss but will be set as "false" as a default value

Healing; Maiden is the only boss that is true healing, does not go off percent base. The other two bosses does go off percentage healing.

Output:
image

Options:
image

### CODE REVIEW

**Comment by Adam-** [comment]
I like the idea of a damage counter (this is basically #3894). However I don't like this approach. Specifically:

1) this should use the party system to share damages between clients
2) this should be able to easily support other things in the future (probably just cox?)
3) this should support any size tob party, not just 5 man

**Comment by akarhi** [comment]
1. Which party system the runelite function one or the ingame one?
2. Should be supportable between raids
3. It should be supportable by any size, currently figuring out to grab the party system and making it automatic

**Comment by pvmgod123** [comment]
Can anyone use this?

**Comment by Adam-** [comment]
The RuneLite one. I made a start at https://github.com/Adam-/runelite/tree/dps which works for simple bosses like corp.

**Comment by TheMursk** [comment]
I tested this and it's pretty neat. One thing you haven't taken into account is that Verzik is also healing when spawning crabs and during blood phaze. Maiden aswell ofc.

**Comment by akarhi** [comment]
I have accounted the healing for all the bosses. Maiden is the actually amount, nylo and verzik is percentage base

**Pull request closed without merging**
