### PR TITLE
Add spiritual creatures to task list

### LINKED ISSUE #2295: SlayerPlugin NullPointerException
Got a new assignment, received spiritual creatures, console kept giving me this error.
```
2018-05-03 08:57:51 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.slayer.SlayerPlugin.buildTargetsToHighlight(SlayerPlugin.java:431)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onGameTick(SlayerPlugin.java:237)
	at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:119)
	at client.ak(client.java)
	at bz.x(bz.java:366)
	at bz.copy$run(bz.java:320)
	at bz.run(bz.java:60)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by iguaan**
Adds spiritual creatures to task list and defines available targets to highlight, **should** also fix NPE when building target highlight list

fixes #2295

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Use the icon from the "Spiritual Fervor" extension entry? http://oldschoolrunescape.wikia.com/wiki/Slayer_reward_point#Extend

**Comment by iguaan** [comment]
for now the item ID is defined by its absolute value since it doesn't have a name associated to it, this doesn't feel like the best practice but it works for now.

**Comment by Nightfirecat** [comment]
Add the ID to ItemID.java in a separate commit? Would be handy to have defined for future reference. :+1:

```
	public static final int SPIRITUAL_MAGE = 11844;
```

**Comment by Abextm** [comment]
Do not add items to `ItemID.java`, as it is auto generated.

**Comment by Adam-** [comment]
We should regenerate ItemID then before doing this

**Pull request closed without merging**
