### PR TITLE
Add simple info log with startup time

### PR DESCRIPTION
**Pull request by deathbeam**
Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Adam-** [comment]
https://google.github.io/guava/releases/18.0/api/docs/com/google/common/base/Stopwatch.html

**Comment by deathbeam** [comment]
I dont think stopwatch is really necessary?

**Comment by Abextm** [comment]
Seems like it would be better to use `RuntimeMXBean::getUptime`

**Comment by deathbeam** [comment]
Doesnt that include also startup time of JVM? Never actually used that property and there is not much documentation for it.

**Comment by Abextm** [comment]
I would assume it includes jvm startup time. That is part of our startup time too.

**Comment by deathbeam** [comment]
So it would also include launcher startup time when the reflection launcher will be used, I am not sure that would be ideal. Mainly because when JVMLauncher will be used it will not account for that and so the results will vary.

**Comment by Abextm** [comment]
It seems like you want to measure init time, rather than startup time

**Comment by deathbeam** [comment]
I guess. I just want to measure how long it takes to create entire RuneLite module and start it.

**Comment by Abextm** [comment]
Both seem like useful metrics, so maybe it should be both.

**Comment by deathbeam** [comment]
Added also display of uptime

**Pull request merged**
