### PR TITLE
Add quest helper

### PR DESCRIPTION
**Pull request by Trevor159**
Example of what I currently have in action, this was recorded before I changed a few things and the Veos highlight at the end not working correct seems to be fixed: https://youtu.be/75QmQZKVA8k

Hopefully the structure isn't completely wrong, I tried to keep it small initially for better chance of review.

I tried to make it as simple as possible to add quests, basically how it works is each quests acts as its own "Plugin" as in it can Inject and subscribe to events like a plugin can. Each step can do this also. This was done to keep the plugin class as clean as possible once more steps get added and to increase simplicity when adding more.

To make a new quest all you do is need to make a map of a step for each value the quest var can be. If a quest isn't that simple they can override methods, create new steps etc to get what they want.

Right now there is no UI for starting or ending a quest helper which is something I want to do with an in game widget but adam/abex have been talking about an interface editor which would be nice :d Right now to start a quest helper you just click the quest in the current ingame quest menu. To stop it you restart the plugin.

I am waiting for Hydrox's arrow hint thing for those for no particular reason.

Something I definitely want feedback on is the binder/injector stuff, I am not 100% I did it right but I removed/added stuff and when I have seems to not be excessive and it works.

I suck with words and a lot of this is probably going to be wrong, please bear with me :d

Closes: #3749
Closes: #5042

EDIT: idk if I will ever have time to continue this. Feel free to take over if you want. The ernest the chicken stuff is very WIP and terrible.

### CODE REVIEW

**Comment by Coa7** [comment]
Is there anything I can help with? Don't know anything about code but with some proper guidance I can help map out quest maybe?? Would love to see this in action! Just wish it would've came out before I got 250 quest points lol

**Comment by Nightfirecat** [comment]
Generally, probably not. You have to have at least some programmatic understanding of how RuneScape advances quest states.

**Comment by james-munson** [comment]
Would be nice if you added a panel so people could help add quest, like they could add/remove/edit steps

**Comment by Reasel** [comment]
I am interested in helping. Hit me up on Discord: Reasel#0925.

**Comment by Zoinkwiz** [comment]
@Trevor159 Hi, I've been experimenting with a quest helper, and since finding this I've tried basing my core structure on it (https://github.com/Zoinkwiz/runelite/tree/quest-helper). Now that I'm starting to feel like I've got the hang of things, I'd like to work on trying to make this plugin a reality and get all quests done. Just wanted to check with you you're okay with that, or happen to know if there's any other work happening on a quest helper?

**Comment by Trevor159** [comment]
This is now on the plugin-hub

**Pull request closed without merging**
