### PR TITLE
Idle notifier fix combat notifications, reset notifications on interaction

### LINKED ISSUE #1614: Bug: Idle notifier sends notifications while attacking Pest Wars portals
title.

This also happens even if being attacked while attacking a the Pest Wars portal.

### LINKED ISSUE #5013: Do not send idle notification if a click occurred during idle delay
Currently when you enabled the 'send notifications when focused' option you will always receive a notification when your character starts idling (assuming you have idle notifications turned on). However, sometimes I'm looking at my character anyway, and notice the idling and already clicked to resolve this during the idle notification delay. In this scenario it's quite annoying to still receive an idle notification.

I suggest we add some logic to the idle notifier (possibly as an option if this breaks some people's workflow) that *if the game has received a click during the idle notification delay, the notification gets cancelled*.

### PR DESCRIPTION
**Pull request by deathbeam**
- To make the notifier more precise make combat idle notifier use
interacting changed.
- In order to make animation idle notifier work with timer resetting, make
it remember last animation.
- When someone logs out, reset all timers to not have sent the
notifications after they are no longer relevant.
- When player clicks in-game, he obviously changed his activity, so reset
all idle timers to default non-valid state.

Closes #1614
Closes #5013 

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I believe this fixes #1614.

**Comment by deathbeam** [comment]
Actually changed the mouseIdleTicks counting back to mouseManager listener because it was not working correctly (apparently they were correct only when window was focused/not changing focus).

**Comment by deathbeam** [comment]
Any update on this @Adam- ?

**Comment by deathbeam** [comment]
Reworked the PR to keep using AnimationChanged and moved the combat idle checks to interacting changed

**Comment by deathbeam** [comment]
+ Added tests

**Pull request merged**
