### PR TITLE
menu entry swapper: Swaps wield/release option for salamanders. 

### PR DESCRIPTION
**Pull request by bowlcutmullet**
The option is disabled by default.

Not sure if there is already another way to do this, but i couldn't find one. Makes hunting salamanders a bit more chill.

### CODE REVIEW

**Comment by Alexsuperfly** [comment]
you can sticky keys shift

**Comment by bowlcutmullet** [comment]
> you can sticky keys shift

Couldn't you then customize shift click to bury bones (for example) and then sticky key shift. I don't think many people know you can do that, it's quite unintuitive. 

Another solution would be to have a "customize left click" that works like customize shift click. But idk if that would be possible/allowed by jagex.

**Comment by deathbeam** [comment]
For this we have shift-click configuration. Most of remaining options in menu-entry swapper that swap inventory are mostly from before we had shift-click.

**Comment by Nightfirecat** [comment]
8944eb9be6d62ec8384e29484dab14c4c2858d9d was added to master, which sufficiently covers this use case.

**Pull request closed without merging**
