### PR TITLE
crowdsourcing: check for null ptr for username

### LINKED ISSUE #18111: [Crowdsourcing] NPE on Fight Caves NPC chat after relog
### Type

Other

### Operating System

None

### OS Version

_No response_

### Bug description

After logging in again in the middle of the fight caves, received a NPE for the dialog from the NPC `TzHaar-Mej-Jal` with the chat `You're on your own now JalYt, prepare to fight for your life!`

Trace:
```
java.lang.NullPointerException: null
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1427)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2126)
	at net.runelite.client.plugins.crowdsourcing.dialogue.CrowdsourcingDialogue.sanitize(CrowdsourcingDialogue.java:57)
	at net.runelite.client.plugins.crowdsourcing.dialogue.CrowdsourcingDialogue.onChatMessage(CrowdsourcingDialogue.java:142)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
```

### Screenshots or videos

_No response_

### RuneLite version

Runelite version: 1.10.35
Launcher version: 2.7.1

### Logs

_No response_

### PR DESCRIPTION
**Pull request by BBeeaarr**
Checks for a null pointer for logged in player's name
otherwise preserves the current behavior of sanitize() 
fixes #18111

### CODE REVIEW

**Comment by tylerwgrass** [comment]
Checked and this fixed it for me

**Comment by raiyni** [comment]
You could just return null?

**Comment by Adam-** [comment]
I think if there is no player name it would be better to either: not store the dialog at all, or not replace the username at all.

**Comment by BBeeaarr** [comment]
> You could just return null?
```
if (username == null)
			return null;

java.lang.NullPointerException: null
	at net.runelite.client.plugins.crowdsourcing.dialogue.CrowdsourcingDialogue.onChatMessage(CrowdsourcingDialogue.java:147)
```
Returning null causes another null pointer exception

**Pull request merged**
