### PR TITLE
make ground items plugin hotkey configurable

### PR DESCRIPTION
**Pull request by neeerp**
Added a config option so that the hotkey for the Ground Items plugin is no longer hardcoded. As someone whose `alt` key is reserved as their modifier key for their window manager, this is much needed.

Also, this partly addresses #7831.

### CODE REVIEW

**Comment by Adam-** [comment]
This doesn't work at all and trips at least one assertion

```
java.lang.AssertionError: null
	at net.runelite.client.config.Keybind.<init>(Keybind.java:72)
	at net.runelite.client.config.Keybind.<init>(Keybind.java:87)
	at net.runelite.client.plugins.grounditems.GroundItemsConfig.hotkey(GroundItemsConfig.java:461)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at net.runelite.client.config.ConfigInvocationHandler.callDefaultMethod(ConfigInvocationHandler.java:169)
	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:92)
	at com.sun.proxy.$Proxy98.hotkey(Unknown Source)
	at net.runelite.client.plugins.grounditems.GroundItemInputListener.keyReleased(GroundItemInputListener.java:80)
	at net.runelite.client.input.KeyManager.processKeyReleased(KeyManager.java:110)
	at net.runelite.client.callback.Hooks.keyReleased(Hooks.java:318)
```

**Comment by neeerp** [comment]
> This doesn't work at all and trips at least one assertion
> 
> ```
> java.lang.AssertionError: null
> 	at net.runelite.client.config.Keybind.<init>(Keybind.java:72)
> 	at net.runelite.client.config.Keybind.<init>(Keybind.java:87)
> 	at net.runelite.client.plugins.grounditems.GroundItemsConfig.hotkey(GroundItemsConfig.java:461)
> 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
> 	at net.runelite.client.config.ConfigInvocationHandler.callDefaultMethod(ConfigInvocationHandler.java:169)
> 	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:92)
> 	at com.sun.proxy.$Proxy98.hotkey(Unknown Source)
> 	at net.runelite.client.plugins.grounditems.GroundItemInputListener.keyReleased(GroundItemInputListener.java:80)
> 	at net.runelite.client.input.KeyManager.processKeyReleased(KeyManager.java:110)
> 	at net.runelite.client.callback.Hooks.keyReleased(Hooks.java:318)
> ```

I just cloned a fresh repo, rebased, rebuilt, and this is still working locally for me... I also signed out of Runelite and reran the client in case this was happening on default settings, but I couldn't reproduce.

Would you have any suggestion on how I can reproduce this?

**Comment by Adam-** [comment]
> > This doesn't work at all and trips at least one assertion
> > ```
> > java.lang.AssertionError: null
> > 	at net.runelite.client.config.Keybind.<init>(Keybind.java:72)
> > 	at net.runelite.client.config.Keybind.<init>(Keybind.java:87)
> > 	at net.runelite.client.plugins.grounditems.GroundItemsConfig.hotkey(GroundItemsConfig.java:461)
> > 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
> > 	at net.runelite.client.config.ConfigInvocationHandler.callDefaultMethod(ConfigInvocationHandler.java:169)
> > 	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:92)
> > 	at com.sun.proxy.$Proxy98.hotkey(Unknown Source)
> > 	at net.runelite.client.plugins.grounditems.GroundItemInputListener.keyReleased(GroundItemInputListener.java:80)
> > 	at net.runelite.client.input.KeyManager.processKeyReleased(KeyManager.java:110)
> > 	at net.runelite.client.callback.Hooks.keyReleased(Hooks.java:318)
> > ```
> 
> I just cloned a fresh repo, rebased, rebuilt, and this is still working locally for me... I also signed out of Runelite and reran the client in case this was happening on default settings, but I couldn't reproduce.
> 
> Would you have any suggestion on how I can reproduce this?

Do you have assertions enabled? You have to pass the `-ea` vm argument.

I think the issue here is the keybinds don't support binding only modifier keys, since it makes setting a keybind to something with a modifier impossible. Eg,  you can set a keybind to alt+f1, and it is actually one keypress despite it requiring you to pass two keys.

**Comment by neeerp** [comment]
I tried running with `-ea` and I'm still not noticing anything:

```
/usr/lib/jvm/java-11-openjdk/bin/java -ea -javaagent:/opt/intellij-idea-ultimate-edition/lib/idea_rt.jar=39799:/opt/intellij-idea-ultimate-edition/bin -Dfile.encoding=UTF-8 -classpath /home/david/runelite/runelite-client/target/classes:/home/david/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/david/.m2/repository/ch/qos/logback/logback-classic/1.2.9/logback-classic-1.2.9.jar:/home/david/.m2/repository/ch/qos/logback/logback-core/1.2.9/logback-core-1.2.9.jar:/home/david/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.1/jopt-simple-5.0.1.jar:/home/david/.m2/repository/com/google/guava/guava/23.2-jre/guava-23.2-jre.jar:/home/david/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0-no_aop.jar:/home/david/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/david/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/david/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/home/david/.m2/repository/net/runelite/pushingpixels/substance/8.0.02/substance-8.0.02.jar:/home/david/.m2/repository/net/runelite/pushingpixels/trident/1.5.00/trident-1.5.00.jar:/home/david/.m2/repository/org/apache/commons/commons-text/1.2/commons-text-1.2.jar:/home/david/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar:/home/david/.m2/repository/org/apache/commons/commons-csv/1.4/commons-csv-1.4.jar:/home/david/.m2/repository/net/runelite/archive-patcher/1.0/archive-patcher-1.0.jar:/home/david/.m2/repository/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar:/home/david/.m2/repository/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar:/home/david/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/david/.m2/repository/net/runelite/jogl/jogl-all/2.4.0-rc-20200429/jogl-all-2.4.0-rc-20200429.jar:/home/david/.m2/repository/net/runelite/jogl/jogl-all/2.4.0-rc-20200429/jogl-all-2.4.0-rc-20200429-natives-windows-amd64.jar:/home/david/.m2/repository/net/runelite/jogl/jogl-all/2.4.0-rc-20200429/jogl-all-2.4.0-rc-20200429-natives-windows-i586.jar:/home/david/.m2/repository/net/runelite/jogl/jogl-all/2.4.0-rc-20200429/jogl-all-2.4.0-rc-20200429-natives-linux-amd64.jar:/home/david/.m2/repository/net/runelite/jogl/jogl-all-natives-macosx/2.4.0-rc-20210117/jogl-all-natives-macosx-2.4.0-rc-20210117.jar:/home/david/.m2/repository/net/runelite/gluegen/gluegen-rt/2.4.0-rc-20200429/gluegen-rt-2.4.0-rc-20200429.jar:/home/david/.m2/repository/net/runelite/gluegen/gluegen-rt/2.4.0-rc-20200429/gluegen-rt-2.4.0-rc-20200429-natives-windows-amd64.jar:/home/david/.m2/repository/net/runelite/gluegen/gluegen-rt/2.4.0-rc-20200429/gluegen-rt-2.4.0-rc-20200429-natives-windows-i586.jar:/home/david/.m2/repository/net/runelite/gluegen/gluegen-rt/2.4.0-rc-20200429/gluegen-rt-2.4.0-rc-20200429-natives-linux-amd64.jar:/home/david/.m2/repository/net/runelite/gluegen/gluegen-rt-natives-macosx/2.4.0-rc-20210117/gluegen-rt-natives-macosx-2.4.0-rc-20210117.jar:/home/david/.m2/repository/net/runelite/jocl/jocl/1.0/jocl-1.0.jar:/home/david/.m2/repository/net/runelite/jocl/jocl/1.0/jocl-1.0-macos-x64.jar:/home/david/.m2/repository/net/runelite/jocl/jocl/1.0/jocl-1.0-macos-arm64.jar:/home/david/runelite/runelite-api/target/classes:/home/david/runelite/runelite-jshell/target/classes:/home/david/.m2/repository/com/fifesoft/rsyntaxtextarea/3.1.2/rsyntaxtextarea-3.1.2.jar:/home/david/.m2/repository/com/fifesoft/autocomplete/3.1.1/autocomplete-3.1.1.jar:/home/david/.m2/repository/net/runelite/client-patch/1.8.11-SNAPSHOT/client-patch-1.8.11-20220122.195337-6.jar:/home/david/.m2/repository/net/runelite/arn/http-api/1.0.0/http-api-1.0.0.jar:/home/david/.m2/repository/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar:/home/david/.m2/repository/com/squareup/okio/okio/1.17.2/okio-1.17.2.jar:/home/david/.m2/repository/net/runelite/discord/1.4/discord-1.4.jar net.runelite.client.RuneLite
2022-01-22 15:59:38 [main] INFO  net.runelite.client.RuneLite - RuneLite 1.8.11-SNAPSHOT (launcher version unknown) starting up, args: none
2022-01-22 15:59:40 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-01-22 15:59:40 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2022-01-22 15:59:40 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2004775688.22
2022-01-22 15:59:40 [main] INFO  n.r.client.account.SessionManager - No session file exists
2022-01-22 15:59:41 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-01-22 15:59:41 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-01-22 15:59:42 [main] INFO  net.runelite.client.RuneLite - Client initialization took 3687ms. Uptime: 4402ms
2022-01-22 15:59:42 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,822,113,1273x1032,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1273x1032,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@fa14f88,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-01-22 15:59:43 [pool-2-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Dave.
2022-01-22 16:00:38 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.ws.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@67cd0fa opened
2022-01-22 16:00:46 [pool-2-thread-1] ERROR n.r.c.e.ExternalPluginManager - Unable to download external plugins
java.io.IOException: Non-OK response code: 404
	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifest(ExternalPluginClient.java:89)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:183)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-22 16:00:46 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
2022-01-22 16:00:46 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6.0 NVIDIA 495.46
```

I can start the game, set the binding to either a single key, or a modifier + a key (in my case, I've tried both `Ctrl` and `Ctrl + s`, and `Alt + F11`) and the binding works and I can click to highlight items (can't click with `Alt + F11` because of my window manager, but it still shows hidden items).

**Comment by Adam-** [comment]
Try unsetting `grounditems.hotkey` completely first

**Comment by neeerp** [comment]
> Try unsetting `grounditems.hotkey` completely first

I was able to reproduce the assertion error if I reset the binding by either clicking on the label and then clicking reset, or resetting the entire plugin config via the reset button at the bottom of the config panel.

Oddly enough, if I unset the binding by clicking on it as though to set a new binding, and then clicking off of it, it successfully unsets with no assertion error.

Will look into this...

**Comment by neeerp** [comment]
Using the constant `Keybind.Alt` seemed to fix the assertion errors... my bad

**Comment by abextm** [comment]
this should use HotkeyListener

**Comment by neeerp** [comment]
> this should use HotkeyListener

By this you mean `GroundItemInputListener`, right? Do you suggest I split it into a `GroundItemMouseAdapter extends MouseAdapter` and `GroundItemHotkeyListener extends HotkeyListener`? Looks to me like the mouse and key parts don't interact, so that should be possible.

**Comment by abextm** [comment]
yes, yes

**Comment by neeerp** [comment]
Following up as it's been a couple weeks; is there anything else I ought to do?

**Comment by Adam-** [comment]
Usually we use anonymous classes for the hotkey listeners since it is a bit cleaner eg 
```java
	private final HotkeyListener hotkeyListener = new HotkeyListener(() -> config.toggleKeybind())
	{
		@Override
		public void hotkeyPressed()
		{
...
		}
	};
```
also would refrain from reaming GroundItemInputListener  since the git rename detection seems to not pick up the rename. Also don't remove licenses in the process of doing that.

**Comment by Adam-** [comment]
added in 43e8a57cadc232c151c002cbfe5a7e4dd95e8b53

**Pull request closed without merging**
