### PR TITLE
Fixing dishonest wording in the readme

### PR DESCRIPTION
**Pull request by VMpc**

### CODE REVIEW

**Comment by geheur** [comment]
You are violating Oxford comma styling. In the before (https://github.com/runelite/runelite/pull/18088/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L4), you can see that it is not using the Oxford comma between the adjectives "open source" and "OldSchool RuneScape". However, in your change (https://github.com/runelite/runelite/pull/18088/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4), it does use an Oxford comma.

**Comment by Nightfirecat** [comment]
Do you care to elaborate on this? I don't feel the readme is dishonest.

**Comment by deifactor** [comment]
I wouldn't call it *dishonest*, but when I first heard about RuneLite I heard "open-source client" and assumed that it was a complete reimplementation and didn't use any Jagex code.

**Comment by ivieedev** [comment]
compgeek1210 aka adam robertson was afraid to get sued therefore he closed source half the project

**Pull request closed without merging**
