### PR TITLE
Added config option in corp plugin for dark core spawn notification

### PR DESCRIPTION
**Pull request by robinwithes**
Closes https://github.com/runelite/runelite/issues/6146

### CODE REVIEW

**Comment by Adam-** [comment]
If you kill the core does it respawn later?

**Comment by MagicfTail** [comment]
Yes

**Comment by Adam-** [comment]
You can probably just notify whenever the npc spawns in - maybe with a distance check so that it doesn't notify when walking into range.

**Comment by robinwithes** [comment]
> You can probably just notify whenever the npc spawns in - maybe with a distance check so that it doesn't notify when walking into range.

The npc spawns in again each time it jumps.

**Comment by 15987632** [comment]
This probably isn't relevant to the way you coded this but if you kill the dark core in a way that the ashes do not drop(killing it with a cannon is the easiest way to do this) then it doesn't respawn for the rest of the kill.

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Adds additional visual or audio indicators of a boss mechanic`

**Pull request closed without merging**
