### PR TITLE
Slayer bracelet overlay

### PR DESCRIPTION
**Pull request by Reasel**
# Slayer Bracelet Overlay
This will track the charges of the slayer bracelets and update their counter when they are changed or broken.

java_2018-05-08_15-08-55

Things to add moving forward would be an info box of its own instead of only overlay on items/equipment.

### CODE REVIEW

**Comment by Kamielvf** [comment]
What about having infoboxes for these? Most of the time you have them equipped and I think infoboxes are nicer than cluttering the inventory.

**Comment by Reasel** [comment]
Yeah I want to get that out at some point, but I have to query for the item every tick I think so I was hesitant

**Comment by Adam-** [comment]
This looks okay. Can you extend the slayer plugin test for it?

**Comment by Reasel** [comment]
Okay @Adam- I think I have added the tests.

**Pull request merged**
