### PR TITLE
Display current world ping

### PR DESCRIPTION
**Pull request by gregg1494**
Capture

Plugin to display ping in the corner of screen under fps. Currently it pings the players current world once every minute.

### CODE REVIEW

**Comment by SRLJustin** [comment]
I feel once every minute is too long for a refresh, would be nice to have an option in the plugin to change the ping timer with a minimum value enforced

**Comment by gregg1494** [comment]
Ya I have to talk to some others about the frequency in which the ping should happen.

**Comment by deathbeam** [comment]
You should move the ping code from world plugin to some common place instead of copying it

**Comment by gregg1494** [comment]
Ya I wanted to but didn't know where it would go. If someone knows where it should go I'll be happy to move it.

**Comment by deathbeam** [comment]
i would just put it to `net.runelite.client.ping`, e.g new package

**Comment by gregg1494** [comment]
Implemented into world hopper. #8871

**Pull request closed without merging**
