### PR TITLE
Omit empty strings in NPC indicators

### LINKED ISSUE #5012: NPC Indicators config has an issue with trailing commas
If your list of NPCs ends with a comma, Dairy cows get a small triangle under them highlighted.

screenshot

### PR DESCRIPTION
**Pull request by deathbeam**
Do no try to parse the list to strings including empty names.

Closes #5012

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Seems like this would be good to write a few tests for.

**Comment by Nightfirecat** [comment]
Seems like we should add a test for empty strings then. It currently doesn't check that.

**Comment by deathbeam** [comment]
I will add some tests for NPC indicators later today probably then

**Comment by deathbeam** [comment]
Added the test

**Pull request merged**
