### PR TITLE
Update MapImageDumper to use BigBufferedImage.

### PR DESCRIPTION
**Pull request by Explv**
Update MapImageDumper to use BigBufferedImage.

This reduces memory consumption significantly. 

Also added a main method so that the dumper
can be called independently.

### CODE REVIEW

**Comment by Adam-** [comment]
Is there another version of this that is licensed under a free software license?

**Comment by Explv** [comment]
> Is there another version of this that is licensed under a free software license?

It's released under Creative Commons CC0, is that sufficient for use here?

**Comment by Adam-** [comment]
> > Is there another version of this that is licensed under a free software license?
> 
> It's released under Creative Commons CC0, is that not sufficient for use here?

I don't know, this is why I was asking.

**Comment by Explv** [comment]
> > > Is there another version of this that is licensed under a free software license?
> > 
> > 
> > It's released under Creative Commons CC0, is that not sufficient for use here?
> 
> I don't know, this is why I was asking.

It should be fine :)

https://creativecommons.org/publicdomain/zero/1.0/

```
The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.

You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.
```

**Comment by Adam-** [comment]
> > > > Is there another version of this that is licensed under a free software license?
> > > 
> > > 
> > > It's released under Creative Commons CC0, is that not sufficient for use here?
> > 
> > 
> > I don't know, this is why I was asking.
> 
> It should be fine :)
> 
> https://creativecommons.org/publicdomain/zero/1.0/
> 
> ```
> The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.
> 
> You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.
> ```

based off of http://www.gnu.org/licenses/license-list.html#NoLicense I think this is okay then. What you've linked is not actually the license text but is instead their interpretation of the license. https://creativecommons.org/publicdomain/zero/1.0/legalcode is the full license.

**Comment by Adam-** [comment]
Fix up your commits so they don't contain a bunch of random changes and I will check it out

**Comment by Explv** [comment]
> Fix up your commits so they don't contain a bunch of random changes and I will check it out

Done

**Comment by Adam-** [comment]
added in 8748b12205cd2daefc48437d33c4b501b3311544 and 879e2973b287c5828c11975f14f915db2cf67aee

**Comment by Adam-** [comment]
had a bit of a mixup and had to push this out, will revisit later

**Comment by abextm** [comment]
in as 75e23b9a3ec26053f427ee5fd0c81d89bf4b2086 & 54da56e7b142fcd5317497bec5344ff5ec0e2e6a

**Pull request closed without merging**
