### PR TITLE
max cape teleports swap

### PR DESCRIPTION
**Pull request by orange-puff**
This is related to https://github.com/runelite/runelite/issues/14353
The max cape teleport menu entry wasn't being swapped with wear by the plugin because it has a `Teleports` entry rather than a `Teleport` entry.

### CODE REVIEW

**Comment by Adam-** [comment]
If anything I would expect the `Teleports` to be part of the existing `Teleport` swap?

**Comment by orange-puff** [comment]
Since I don't have a max cape I have no ability to test this. But according to the issue author the original plugin is not swapping the menu entries

**Comment by Adam-** [comment]
My question is: why is "Teleports" not swapped with the existing Teleport item swap, and instead a new option is being added?

**Comment by orange-puff** [comment]
Good point. Updated

**Comment by orange-puff** [comment]
Updated to use the existing `Teleport` swap rather than an additional option

**Comment by alizan** [comment]
Hi, I can see there was an update to the Max Cape being added to teleport item in menu entry swapper as per request in this case. 

However this is not ideal for some people that want to left-click wear for Max Cape, while keeping other teleport items left-click teleport as it was before recent update. Would it be possible to add toggable option for Max Cape similar to other teleport capes, as suggested in [https://github.com/runelite/runelite/issues/14353](url) ?

**Comment by Nightfirecat** [comment]
8944eb9be6d62ec8384e29484dab14c4c2858d9d was just added to master, which would allow you to override the general teleport items swap on the max cape (or any other teleport items/jewellery).

**Pull request merged**
