### PR TITLE
Add button to sync local config with remote

### LINKED ISSUE #1281: Account plugin: Local settings are wiped after account creation
Anecdote from a user on discord. The plugin is supposed to retain local settings separately, but it seems these aren't restored after logging out. We probably need more details.

### PR DESCRIPTION
**Pull request by deathbeam**
Add button to info panel that will show when you are logged in to sync
local configuration with remote.

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Closes #1281

### CODE REVIEW

**Comment by deathbeam** [comment]
Preview

screenie

**Comment by deathbeam** [comment]
New icon! (thanks to @psikoi for pointing me to correct direction)

screenie

**Comment by ConradMelcher** [comment]
Unless I'm misunderstanding, shouldn't it be either "Export local settings to remote Runelite account" or "Import local settings from remote Runelite account". Not sure what the function is, but it seems unclear the way it's typed.

**Comment by deathbeam** [comment]
I think its clear enough

**Comment by deathbeam** [comment]
Changed `Import` to `Export` in UI, and added it to next milestone because people really need something that provides this functionality (mainly with new stuff coming up + already existing loot tracker)

**Comment by deathbeam** [comment]
@Adam- Can you check this PR?

**Pull request merged**
