### PR TITLE
Skill Calc - ComboBox skill list

### PR DESCRIPTION
**Pull request by psikoi**
UI components provided by @TheStonedTurtle.

This UI element was originally included in @TheStonedTurtle's skill calc revamp PR, I have wanted this UI improvement in the client for a while now so I asked him to PR it seperately and he asked if I could do it myself.

However there was an annoying dotted "focus paint" effect with it that I resolved by disallowing focusing on the combobox.

Also, more importantly, **a bug in the original skill calc** code was causing some of the skill's calcs to over estimate their panel size, as shown above before and after this correction:

This was quickly fixed by limiting the individual list items' heights to 45px.

### CODE REVIEW

**Comment by TheStonedTurtle** [comment]
You may want to reorder the `CalculatorType` enum file so the drop down is in alphabetical order

```
	AGILITY(Skill.AGILITY, "skill_agility.json"),
	CONSTRUCTION(Skill.CONSTRUCTION, "skill_construction.json"),
	COOKING(Skill.COOKING, "skill_cooking.json"),
	CRAFTING(Skill.CRAFTING, "skill_crafting.json"),
	FARMING(Skill.FARMING, "skill_farming.json"),
	FIREMAKING(Skill.FIREMAKING, "skill_firemaking.json"),
	FLETCHING(Skill.FLETCHING, "skill_fletching.json"),
	FISHING(Skill.FISHING, "skill_fishing.json"),
	HERBLORE(Skill.HERBLORE, "skill_herblore.json"),
	HUNTER(Skill.HUNTER, "skill_hunter.json"),
	MAGIC(Skill.MAGIC, "skill_magic.json"),
	MINING(Skill.MINING, "skill_mining.json"),
	PRAYER(Skill.PRAYER, "skill_prayer.json"),
	RUNECRAFT(Skill.RUNECRAFT, "skill_runecraft.json"),
	SMITHING(Skill.SMITHING, "skill_smithing.json"),
	THIEVING(Skill.THIEVING, "skill_thieving.json"),
	WOODCUTTING(Skill.WOODCUTTING, "skill_woodcutting.json");
```

**Comment by psikoi** [comment]
Makes sense

**Comment by deathbeam** [comment]
Why is this better than "tabs" we currently have now?

**Comment by psikoi** [comment]
Occupies like a fourth of the UI room

**Comment by deathbeam** [comment]
But it looks worse

**Comment by psikoi** [comment]
It guess it's goodbye

**Pull request closed without merging**
