### PR TITLE
dulling removed to prevent difficult to see markers

### LINKED ISSUE #7170: xptracker: hunter immediate markers are almost invisible
https://twitter.com/Bearistdk/status/1080853514115375106

### PR DESCRIPTION
**Pull request by JAnken123**
closes #7170

### CODE REVIEW

**Comment by Spedwards** [comment]
Would you like to post screenshots of what this now looks like?

**Comment by JAnken123** [comment]
Markers are the same colors as foreground (the skill colors). Instead of 30% more dull as it were previously. I dont think a picture is necessary as it is straight forward to imagine what it looks like, but I can add one tomorrow.

**Comment by Nightfirecat** [comment]
A picture of the difficult-to-see skill colors in question (hunter in this case) would be good.

**Comment by JAnken123** [comment]
Hunter looks like this.
image

**Pull request merged**
