### PR TITLE
Add clue text for stealing from ardougne chest after SotE completion …

### LINKED ISSUE #10854: skill challenge clue: steal from ardougne chest
looking through logs for a support issue i noticed `2020-02-22 14:16:31 [Client] WARN  n.r.c.p.cluescrolls.ClueScrollPlugin - Encountered unhandled clue text: Steal from a chest in Ardougne Castle.`

the current skill challenge clue file has [this](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java#L131) listed, so either the text changed from some update or a new one came out thats very similar.

to fix this just add that clue text from the log to the [SkillChallengeClue.java](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java) file

### PR DESCRIPTION
**Pull request by BrandtHill**
closes #10854 
…(spoiler alert)
Details: https://github.com/runelite/runelite/issues/10854

I haven't completed Song of the Elves but apparently a certain castle changes ownership, and the clue text to steal from its chest is changed accordingly.

### CODE REVIEW

**Comment by Alexsuperfly** [comment]
place `closes #<issue_number>` in the pr description to link the pr to that issue and have the merge auto close it.

also, i think just the text of the current clue changed instead of a totally new one being added.

**Comment by Adam-** [comment]
The wiki still has the old one listed, so it might still be valid? Does anyone know?

**Comment by BrandtHill** [comment]
> The wiki still has the old one listed, so it might still be valid? Does anyone know?

Shall I re-add the old clue text to be safe? Let me know

**Comment by Adam-** [comment]
If noone has seen a `Steal from a chest in King Lathas' castle in East Ardougne.` then the wiki is probably just wrong and we should edit that. Especially if you haven't done sote yet and still see it.

**Comment by Nightfirecat** [comment]
@BrandtHill Did you get this clue on your account which hasn't completed SotE?

**Comment by BrandtHill** [comment]
@Nightfirecat No, just cutting teeth on open source and went off what the linked issue said

**Comment by Adam-** [comment]
I guess we can try this and see if we get any complaints.

**Pull request merged**
