### PR TITLE
UI: Add a clear button (×) to IconTextField

### PR DESCRIPTION
**Pull request by SoyChai**
Simple little addition to all searchbars. If anyone wants to style it better, just ask for push access.

Updated:

image

The PR originally looked like this:

image

### CODE REVIEW

**Comment by psikoi** [comment]
Can it be grey or orange? :s

**Comment by SoyChai** [comment]
We could use grey. I feel like orange wouldn't make sense though since it represents "enabled" in our theme, and red is a lot more visible.

**Comment by deathbeam** [comment]
Grey would blend too much with the design imo. Red is good fit because it represents this functionality in other applications too.

**Comment by psikoi** [comment]
Okay makes sense, i don't like the hover effect, cant you just change the icon's color?

**Comment by psikoi** [comment]
Check the screen markers naming in master

**Comment by SoyChai** [comment]
Done. The (×) just changes its colour now. It also passes hover events to the searchbar so that can highlight too, instead of having a weird dead zone over the button.

I turned it into a JLabel because the mouse listener makes JButton unnecessary.

**Comment by psikoi** [comment]
i think PINK might be a weird choice tho, doesn't RED.brighter() work just as well? might be more subtle

**Comment by SoyChai** [comment]
I thought of it, but I had to stack `brighter()` about three times just to see any difference. PINK feels like a nice contrast balance since it's already a very subtle icon.

**Comment by deathbeam** [comment]
Or the orange color what we use at other places? The pink feels a bit odd

**Comment by SoyChai** [comment]
Shouldn't we be consistent with our colour theme? I don't think anything else highlights orange when it's hovered at the moment. Pink here just represents a highlighted red.

**Comment by psikoi** [comment]
Yes, but I just suggested that the color difference between red and pink is too great, i think something more subtle would be better, but I'm sold on the red, either that or light gray.

**Comment by SoyChai** [comment]
If we don't agree on colours, then grey & white works fine imo.

image

**Pull request merged**
