### PR TITLE
Fps indicator improvements

### LINKED ISSUE #2544: FPS counter not showing with stretched fixed mode on
title

### LINKED ISSUE #3086: fps counter
Why does the fps counter since today say the number and Fps instead of just the number? ("50 FPS" instead of just "50")
Is there any way to disable this I really like just having the number and I cant seem to find an option for it

### PR DESCRIPTION
**Pull request by devLotto**
**Before:**

**After:**

Fixes #2544 
Fixes #3086

### CODE REVIEW

**Comment by deathbeam** [comment]
This will close #2544

**Comment by FusionLord** [comment]
Why not give it a `PanelComponent` or return its dimensions so it can be moved as the user desires?

**Comment by deathbeam** [comment]
Because we dont have snap-corner there and so it would not be always in top-right. also, panel component would make it quite annoying to look at, and without it it would be awkward to move

**Comment by FusionLord** [comment]
PanelComponent wouldn't be an issue if you pass it a transparent background, and make the BackgroundPanel's border use the alpha from the background color.

**Comment by deathbeam** [comment]
Why use panel component then?

**Pull request merged**
