### PR TITLE
Update to Solution of speaking to Falo the Bard

### PR DESCRIPTION
**Pull request by TylerNichols**
Including a better description of his location and the closest fairy ring.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Southwest of the fairy ring might be a better description, since it involves crossing the bridge to get to him.

**Comment by TylerNichols** [comment]
I agree. Fixed that.

**Comment by deathbeam** [comment]
Is this really necessary now after we have the map helper?

**Comment by TylerNichols** [comment]
I mean, is it not quicker to just get the quick tip? It certainly isn't lowering the value of the clue helper.

**Pull request merged**
