### PR TITLE
Auto formatter that matches the code-style

### PR DESCRIPTION
**Pull request by Hermetism**
Auto-formats code to match the code-style.

You can add it to IntelliJ by going to ` Settings -> Editor -> Code Style ->Java ` and then importing the scheme by clicking on the cog and selecting `"Import Scheme"`

To format the module/plugin/class you are working on just right click it in project structure and select "Reformat Code"

### CODE REVIEW

**Comment by raiyni** [comment]
We already have this on the wiki https://github.com/runelite/runelite/wiki/Code-Conventions

**Comment by Hermetism** [comment]
That just tells you when its wrong if i'm not mistaken?

This actually changes it to match the code style.

Are you sure they are the same thing

**Comment by raiyni** [comment]
read the bold text

**Comment by Hermetism** [comment]
Yeah its not the same thing.

**Comment by Hermetism** [comment]
I use checkstyle and this.

**Comment by raiyni** [comment]
`To setup IntelliJ Idea with correct project code-style, download this xml and follow this guide to import it into your IDE.`

**Comment by Hermetism** [comment]
Yeah man i can read. Its not the same thing.

**Comment by Hermetism** [comment]
Explain yourself or go away please mate, checkstyle and code styling aren't the same thing unless i'm doing something wrong.

**Comment by raiyni** [comment]
That links to the code style.

**Comment by Hermetism** [comment]
Haha. Oh, My bad.

**Pull request closed without merging**
