### PR TITLE
Add region locking to clues

### PR DESCRIPTION
**Pull request by Roughsketch**
This adds functionality that allows NPC highlighting to be locked to a certain region. This is helpful in a handful of clues that reference common NPCs that can be in many areas such as Guards (normal, market, and dog), Barbarians, Wizards, and chickens.

This PR adds the following classes that were pretty much copied from the Emote clue's item requirements implementation:

- `RegionRequirement`, interface
- `AnyRegionRequirement`, used for multiple disconnected RegionRequirements
- `RangeRegionRequirement`, used to map consecutive ranges together
- `SingleRegionRequirement`, used to lock to a single region

This also adds `RegionLockedClueScroll`, which requires a list of RegionRequirements so that ClueScrollPlugin can avoid marking hint arrows on invalid NPCs.

### CODE REVIEW

**Comment by Roughsketch** [comment]
Travis compiled the wrong commit the second time, but amending fixed it.

**Comment by Roughsketch** [comment]
That should be better now.

**Comment by Roughsketch** [comment]
Adam mentioned earlier on discord the possibility of adding an `npc` method to assign regions to npcs. At first I thought that would be excessive because only a minority of clues require regions, but I think that format might fix other issues I was thinking of fixing as well. In particular, the case where multiple npcs are valid for a clue.

I propose adding `npc` and `anyNpc`, and perhaps changing region's methods to `anyRegion` and `rangeRegion`. This would change the region addition to something like `npc("Guard", 10547)`, or `npcAny(npc("Confused Barbarian"), npc("Lost Barbarian"))`, or `npc("Guard dog", regionRange(10547, 10548))`.

Perhaps it would be possible to have a default string to npc, which would remove the requirement of changing every single npc clue to use `npc(...)`.

Is this an okay idea? Should something be changed about it? I'd like to get some input.

**Comment by Nightfirecat** [comment]
Needs rebase

**Pull request closed without merging**
