### PR TITLE
Add spicy stews to item stats plugin

### PR DESCRIPTION
**Pull request by SoyChai**
image

Adds 4 new varbit indices to check the latest stew's ingredients. All that's left is to decide on the colour logic, which is a bit ambiguous due to the random nature of the stew's boosts.

Submitting this early just in case anyone wants to try finishing it themselves, I'm off for today.

### CODE REVIEW

**Comment by SoyChai** [comment]
Aaaand I think it's ready.

image

The colours just assume the stew will always give zero, capped-positive, or fully-positive boosts, and the ± symbol should imply the rest.

**Comment by Infinitay** [comment]
I feel as if ±#/±# is a bit redundant, just ±# seems fine to me

**Comment by SoyChai** [comment]
That's how it looks with all of the item stats info enabled, you can have it look like the screenshot in the OP by just enabling the "theoretical" checkbox.

**Comment by ShaunDreclin** [comment]
Is the tooltip like that just for testing? In practice it shouldn't be possible to get a +1, +3, and +5 boost in three different categories at the same time lol

**Comment by SoyChai** [comment]
Oh, which part of the spicy stew logic prevents that? I was able to add the maximum doses of all 4 spice colours at any time while I was testing this.

**Comment by SoyChai** [comment]
Ahaha yeah, I doubt there's any benefit to boosting that many skills at once, but you can do it.

**Pull request merged**
