### PR TITLE
Clue Scroll Interface Hiding

### PR DESCRIPTION
**Pull request by Desetude**
The clue scroll helper interface is now hidden if there are no clue scrolls in the player's inventory.

### CODE REVIEW

**Comment by deathbeam** [comment]
Is this still needed? As Clue Scroll plugin was changed.

**Comment by Kamielvf** [comment]
image

i think this might still be relevant.

**Comment by SomeoneWithAnInternetConnection** [comment]
It sounds like the infobox went away once the treasure UI came up, so I think we're good on the hiding front, though it still might not hurt to hide the infobox when there's no cluescroll to be found anyways, just for the sake of clarity

**Comment by deathbeam** [comment]
This was fixed in #1493

**Pull request closed without merging**
