### PR TITLE
Add BA high gamble count chat command

### PR DESCRIPTION
**Pull request by Jacoblairm**
Aimed at fixing issue #7691

### CODE REVIEW

**Comment by deathbeam** [comment]
I think this should be part of kill count command

**Comment by Adam-** [comment]
At the very least, it could internally use the `/kc` endpoint to save some code.

**Comment by Adam-** [comment]
If `!kc penance queen` is already a thing I would just pick some other "boss name" like `ba high gamble` or something.

**Comment by jmm140330** [comment]
We do not track penance queen kills with !kc, for whatever reason. Gamble count is commonly used by the ba community as well, I think the separate command like this would be a good fit?

**Comment by Jacoblairm** [comment]
!kc chat command is registered to use killCountLookup() then killCountSubmit(), how could killCountSubmit() be used to submit the Gamble count considering it's just a varbit (similar to quest points)?

Also, a high gamble isn't directly related to killing a monster, "BA high gamble kill count: 355" would seem a little unusual.

**Comment by Adam-** [comment]
@Jacoblairm have you confirmed this works outside of ba?

**Comment by Adam-** [comment]
Alex on Discord checked it so we should be good.

**Pull request merged**
