### PR TITLE
Added hallowed sepulchre floors into the agility calculator

### PR DESCRIPTION
**Pull request by arthur798**
This merge adds each hallowed sepulchre agility course into the agility calculator by floor, not sure how we would go about making "combined" run when a person completes floors from 1-5 in one go, not sure if that needs to be handled? Icon might need to be changed so happy to take suggestions

### CODE REVIEW

**Comment by Broooklyn** [comment]
Since Hallowed Sepulchre is not an Agility course that produces Marks of grace, you should not use `11849` for the icons. Perhaps `24736` (Ring of Endurance) or `24711` (Hallowed mark), although that's only a single mark and maybe not very identifiable. 

java_aAfRLXtQkY
java_1ZFlVVldhm

**Comment by arthur798** [comment]
I am happy to change if that's what is better? Anyone else have suggestions are agree with @Broooklyn

**Comment by Hydrox6** [comment]
The Ring looks the better out of the two, and it feels like the icon for the area

**Comment by arthur798** [comment]
no problem I will ammend the icons now

**Comment by arthur798** [comment]
Is anything else needed to get this merged?

**Pull request merged**
