### PR TITLE
Remove custom chrome

### LINKED ISSUE #956: Move titlebar buttons into a top-bar when custom chrome is disabled
Currently, if you disable custom window chrome the title bar buttons (screenshot, discord, account) move into the info panel. This makes 0 sense.
My proposed fix is instead of moving them there, add a top bar that would contain the elements of the title bar when custom window chrome option is disabled.

To add to this, as a user on discord mentioned, if this would be implemented, it would be nice if hiding this title bar was also possible. OSB does this when you press alt+F11 and I think konduit has has a keybind for this too.

Once something like #668 has been added it would be possible to play with a client looking like the vanilla one, by having no extra UI elements.

### LINKED ISSUE #1426: Window issue crushing the buttons
image

The screenshot or whichever one of those buttons you enable first covers the minimize button meaning that that button doesn't work and the minimize feature works before that button.

### LINKED ISSUE #1953: Enable native window snapping while using custom chrome
Pretty much the only downside of this window mode. It'd be great to have the full visual branding but still make use of basic multi-monitor features.

### LINKED ISSUE #2335: Idle notifications doesn't bring client to the front on Windows 10
Windows 10 plays a toast during the idle notification but doesn't switch to the client or bring it to the front of my screen

'Send notifications when focused' and 'Request focus on notification' are both selected under Runelite settings

### LINKED ISSUE #3138: contain in screen locks to 1st monitor
contain in screen locks the window to the 1st monitor only rather than containing to the screen across all monitors

### PR DESCRIPTION
**Pull request by deathbeam**
In order to maintain somewhat healthy ClientUI implementation and to not
break native OS functionality, remove custom window decorations and
move everything from previous title bar to sidebar.

The main points why this should be implemented:
1. We are facing with users asking why their client is not behaving like other windows do. E.g, not snapping to window corners, not working when using some applications that manipulate/detect windows (OBS for example) and many other
2. The amount of workaround work that will need to be done to solve all issues that come with having undecorated window that basically detaches from native OS window manager can get unmaintainable really quick, and at the moment we tend to tell people to just disable custom window chrome to solve their issues

I am opening this PR also to see people's reactions and get some discussion going on this topic.

Closes #1953 and closes #1426 and closes #956 and closes #2335 and closes #3138  

## New
peek 2018-04-28 12-26
screenshot 2018-04-28 13 02 20
screenshot 2018-04-28 13 02 15
screenshot 2018-04-28 13 02 09

## New (with Obsidian)
screenshot 2018-05-25 18 30 38

## Old:
screenshot 2018-04-26 21 53 07
screenshot 2018-04-26 21 52 58
screenshot 2018-04-26 21 52 47

### CODE REVIEW

**Comment by deathbeam** [comment]
Updated to work with obsidian, this looks currently like this:

screenshot 2018-05-21 16 34 14

**Comment by SomeZer0** [comment]
Not sure if this is already how it works, but..

Would be nice to have a toggle to completely hide/remove the "sidebar button" (and only use the hotkey to hide/show)

Would be nice to be able to move the "sidebar button" (similar to other overlays)

**Comment by deathbeam** [comment]
Not really. But i quite like that auto-hide feature, i might look at adding it here.

**Comment by SomeZer0** [comment]
Having this button appear on top of the logout button (in resizable) is a pretty big issue, especially if it can't be toggled off or moved.

Does it still do this?

**Comment by deathbeam** [comment]
Yeah. I will look at auto-adjusting the position based on the widget too.

**Comment by deathbeam** [comment]
Now open sidebar button moves down based on the logout button widget in corner:

peek 2018-06-06 10-34

**Comment by deathbeam** [comment]
I will just keep #5797 because I think @Adam- is strictly against removing features so this will most likely never be merged

**Pull request closed without merging**
