### PR TITLE
Add Anti Drag Plugin

### PR DESCRIPTION
**Pull request by DevDennis**
- Allows you to configure the delay before you start dragging an item in your inventory in client ticks (20ms)
- Choose whether you want the delay while holding shift only

Adds https://github.com/runelite/runelite/issues/1062, https://github.com/runelite/runelite/issues/1669, https://github.com/runelite/runelite/issues/2299

### CODE REVIEW

**Comment by HSJ-OSRS** [comment]
honestly this would be way to op in pvp and takes alot of skill away from being able to switch properly/quickly

**Comment by jplsek** [comment]
I'm not sure how OSB does it, but why is there an option to set a drag delay? When would it be useful? I don't know if it's a good idea to allow players to configure the drag delay.

IMO, I would just set the delay to INT_MAX and not have an option. And subsequently have the shift option enabled by default. That would make more sense from a player's perspective. Less guess and check.

**Comment by Gamer1120** [comment]
I think this would be OP and should not be added.

**Comment by DevDennis** [comment]
The drag delay option is there so you are able to set a delay that is always active without holding shift. 
If the delay is on MAX and not on shift only then you wouldn't be able to drag any items so if there is no drag delay option then the on shift only option will be useless.

What is OP about it though?

**Comment by CaraPis** [comment]
It wouldn't be OP since you can already do this with a simple ahk ramap which is allowed.

**Comment by Reasel** [comment]
@CaraPis mind dumping your ahk script for that? I am not understanding how you can do a simple remap for this.

**Comment by CaraPis** [comment]
@Reasel Yea sure, there are actually 2 ways of doing it, one is where you remap Numpad5 key from windows mousekeys, so like that would be LButton::Numpad5, the other way would be the following:
LButton::
Click
KeyWait, LButton
return
Which is identical to what you do with the mousekey remap.

**Comment by Chdata** [comment]
If you have something like a razer mouse, you can also create anti-drag by setting a button to click and not hold.

I think it's a fair feature.

**Pull request merged**
