### PR TITLE
Persistent boss drop log

### PR DESCRIPTION
**Pull request by Poppro**
Adds a plugin to track popular in-game boss drops.
Tracks bosses via the plugin config to provide a persistent, account-based experience.

**Features**
- Choose from list of bosses to track
- Automatically rescales UI to account for large drop-tables
- Persistent tracking independent of local storage
- Tracks loot for seperate in-game accounts automatically
- Ability to reset boss log via GUI
- Displays boss uniques to provide completionist log
- Displays tracked KC
- Displays total profit of tracked boss.

**Images**
screen shot 2018-11-22 at 2 47 14 pm

screen shot 2018-11-22 at 2 45 53 pm

screen shot 2018-11-22 at 2 47 48 pm

screen shot 2018-11-22 at 2 48 14 pm

### CODE REVIEW

**Comment by Hydrox6** [comment]
Why is this a separate plugin?

**Comment by Poppro** [comment]
Just seemed to me at the time I started development that the idea of the plugin was departed enough from a general non-persistent loot tracker that it would be fine to have it separate. If it's controversial as a separate plugin I think that it would certainly make sense as a "boss log" sub-menu of the current loot tracker plugin though.

**Comment by raiyni** [comment]
Having the option for every boss isn't necessary imo

**Comment by deathbeam** [comment]
I am pretty sure jagex is implementing this for their collection log (or w/e it is named).

**Comment by Adam-** [comment]
I think Jagex is implementing this "soon", so it is probably not worth adding a plugin for.

**Pull request closed without merging**
