### PR TITLE
Update Xp tracker UI to make it smaller

### PR DESCRIPTION
**Pull request by sethtroll**
xp-initial

### CODE REVIEW

**Comment by deathbeam** [comment]
I feel like the icon should still be button to reset skill, because with right click menu it is a bit annoying reset multiple skills at once :/

**Comment by Unmoon** [comment]
@deathbeam I don't think that's very intuitive. Maybe a reset button on the right side of the bar? If you don't want to make the bar smaller, the skill icon could be inserted inside it or something.

**Comment by deathbeam** [comment]
Well, it would have "Reset blahblah" hover! :joy: Yeah well, maybe reset button would work as well, but idk how good that would look. Making the icon button would look pretty good because it will sort of match with style of the xp bar.

**Comment by SomeoneWithAnInternetConnection** [comment]
"It'll have hovertext" sounds about as convenient as "It's available in the right click menu"

**Comment by Unmoon** [comment]
The hovers appear so slowly, I don't think anyone reads them. :smile:

**Comment by deathbeam** [comment]
Well, no, because my point was about clicking multiple skills fast to reset trackers, having the info as hover but button for immediate access to the functionality is different as have the info and the functionality as right click. Hmm, so maybe alter icon to have small reset icon in corners and make them buttons would be the solution?

**Comment by SomeoneWithAnInternetConnection** [comment]
For reference, the Konduit interface is as follows:

Initially, the widgets in the tracker's list look like this: 
collapsed konduit xp tracker widget

You can then click on them, and they expand into this:
2018-01-31-040604_224x64_scrot
* Hitting the  button pops it out onto the in-game canvas so you can move it around and whatnot.
* Hitting the  button pauses it (no XP events are registered, and the XP/hr doesn't decrease with time spent not gaining XP)
* Hitting the  button resets its state, but doesn't remove it from the list
* Hitting the  button removes the widget from the list in their interface

**Comment by deathbeam** [comment]
Yeah, well, I dont like the konduit interface for the XP tracker very much, everything is so small, and the buttons centered looks weird. I really like the lvl overlay over the icon tho, that can be added I guess? Also, current, without rewriting the tracking logic a bit, we cant really pause the tracking, because that would mean keeping list of time marks, but that is doable I guess.

**Comment by Abextm** [comment]
OSBuddy's also for reference.

**Comment by deathbeam** [comment]
I was thinking something like this (second tracker)
test

**Comment by deathbeam** [comment]
You were right @Sethtroll the button background looked horrible. Made small adjustments to the button that will make it look flat and also added back the level over the button. Preview:

screenie

screenie_inv

**Comment by sethtroll** [comment]
Updated PR to remove the dep on miglayout. Can expand panel to display more info

xp-initial
xp-expanded

**Pull request merged**
