### PR TITLE
Make HTTP service easily usable for local development and deployement

### PR DESCRIPTION
**Pull request by deathbeam**
- Normalize http-service configuration
- Add configurable oauth callback via spring property
- Normalize cache-updater configuration

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

From local testing (i will be publishing/linking ansible later):

```
$ docker container list
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                 PORTS                    NAMES
9e11c85bca45        runelite/http-service:1.5.13-SNAPSHOT   "java -jar /app.jar"     5 minutes ago       Up 5 minutes           0.0.0.0:9080->9080/tcp   httpservice
90a7a5687c8b        tomcat:7-jre8                           "catalina.sh run"        2 hours ago         Up 2 hours             0.0.0.0:8080->8080/tcp   tomcat
b8757649f2c1        redis:alpine                            "docker-entrypoint.s…"   2 hours ago         Up 2 hours             6379/tcp                 redis
31fa0c9ccf29        minio/minio                             "/usr/bin/docker-ent…"   2 hours ago         Up 2 hours (healthy)   9000/tcp                 minio
70508636cd59        mariadb:10.2.16                         "docker-entrypoint.s…"   2 hours ago         Up 2 hours             3306/tcp                 db
```

```
$ docker network inspect -f '{{ range $key, $value := .Containers }}{{ printf "%s\n" $value }}{{ end }}' runelite_network
{minio 86102e4661cb7090dd48b2a20a7b29e546003836c3ebf14cdc931d8d2331a1d5 02:42:ac:12:00:03 172.18.0.3/16 }
{db 159f221119fb4fe116d82ab090a6cbed185083a46995ffd843b48ccf369e3893 02:42:ac:12:00:02 172.18.0.2/16 }
{tomcat 217bd5e02df2fc78e69c89fd752042007ff9f10dc2cebbdb45d4e9ea007d13bc 02:42:ac:12:00:05 172.18.0.5/16 }
{httpservice 85eb046eea2382c0b2b3b28f6c0cf3b35acdbd671f308b1c45f77d81c90a3f80 02:42:ac:12:00:06 172.18.0.6/16 }
{redis 58628a390871858e691174a567b49e925fc00bf87515e7aa2558c48c711cf06d 02:42:ac:12:00:04 172.18.0.4/16 }
```

httpservice is for local development and tomcat can be used for production.

### CODE REVIEW

**Comment by deathbeam** [comment]
Pushed all changes to my ansible repo, after building this patch it should work out of the box:
https://github.com/deathbeam/runelite-ansible

Then to deploy image to tomcat (not necessary, but to test JNDI):
```
docker cp target/runelite-1.5.13-SNAPSHOT.war tomcat:/usr/local/tomcat/webapps/
```

otherwise service should be already deployed on 9080.

**Comment by deathbeam** [comment]
Now the dockerfile generation and deployement is disabled by default (hidden behind dockerfile.skip property, similar pattern as we use everywhere else)

**Comment by deathbeam** [comment]
Added Docker goal for cache-updater too, and updated structure for cache-updater configuration to reflect http-service (so they can use same config e.g from spring cloud config if neeeded).

**Comment by deathbeam** [comment]
Moved debug logging to `dev` profile that is then activated via ENV variable: https://github.com/deathbeam/runelite-ansible/commit/2965608c62689b3c42382ccfe980980555026385#diff-7c260228b9e23f79cc109f865b402021R16

**Comment by deathbeam** [comment]
After #7904 and @Adam- 's PR I updated this PR to just use default connectors, and its now very small, so, nice, I guess?

**Comment by deathbeam** [comment]
Removed cache-updater Dockerfile from PR as I just made ansible playbook to build it as it do not changes that often anyway: https://github.com/deathbeam/runelite-ansible/commit/399782ec9289ff0f549b27d2de7fa2bad596e383

Keeping the http-service docker image because it helps A LOT to just have the ability to build docker image when developing something, during build, without doing any ugly copy paste (its disabled by default anyway, so its fine).

**Comment by deathbeam** [comment]
Added fa7fec707e114920bfc7a38ed80026fa2085c15c that will make oauth callback configurable via spring property (necessary for any kind of deployement that not production)

**Comment by deathbeam** [comment]
Updated and rebased the PR, removed Dockerfile part completely (I will just expose ports from ansible deployement instead, should be very simple to do)

**Comment by deathbeam** [comment]
Udated the PR based on latest changes in master + cleaned up dev config (removed moving of prod config to separate tomcat profile as its not necessary).

**Comment by Adam-** [comment]
How about https://github.com/Adam-/runelite/commits/spring instead?

**Comment by deathbeam** [comment]
That simply do not contains the repackage step right? E.g basically makes this not run at all (other than from intellij and tomcat).

**Comment by Adam-** [comment]
Yes. I'd include it but I can't figure out how to make the deploy plugin skip it.

**Pull request closed without merging**
