### PR TITLE
Changed how idle checks in combat

### LINKED ISSUE #356: Idle notifier - Alerts when HP bar disappears even if still engaged in combat
Happens when safespotting Skeletal Wyverns and splashing too many times (hp bar disappears). Worked fine before #340.

Settings: 
image

### PR DESCRIPTION
**Pull request by Noremac201**
this might require higher user's idle timeouts to work the same
Resolves #356

### CODE REVIEW

**Comment by Unmoon** [comment]
Tested this at wyverns, doesn't seem to fix the issue, even with 1800ms timeout.

**Comment by deathbeam** [comment]
The correct solution for the idle notifier problems is add pending notification, and only after the action ended, save when the action ended and start the configurable timeout. and if no other action happens before the timer runs out, only then throw the notification.

**Comment by deathbeam** [comment]
Any plans to update the PR @Noremac201 ? Currently based on @Unmoon 's comment, it is not fixing the issue.

**Comment by Noremac201** [comment]
@deathbeam 
When you say action do you mean animation? Also removing the line "opponent.getHealth() > -1" solves the majority of issues, but will still trigger a false positive for talking to NPC's with combat level.

**Comment by deathbeam** [comment]
Well, removing opponent.getHealth() do not solves anything, because as you said, it will fix the issue with splashing, but causes a lot of issues when talking to NPCs etc. yeah by action I mean animation.

**Pull request merged**
