### PR TITLE
NMZ Overload Expiration Warning

### PR DESCRIPTION
**Pull request by episkorowski**
#2221
Added a timer to send a notification when your overload is about to expire. Defaults to 15 seconds before expiration.

Time is based on the first overload damage animation, should be accurate within a couple seconds.

image

### CODE REVIEW

**Comment by Adam-** [comment]
Isn't there a chatbox message when this happens? It might be easier to just wait for that and notify then.

**Comment by episkorowski** [comment]
The feature request is for a warning beforehand, so we can't use the "your overload has worn off" message, since it's already expired by the time that message appears.
  
Unless you mean using the "You drink some of your overload potion." message to start the timer, if that would be preferable to using the animation timing.

image

**Comment by deathbeam** [comment]
You should really reword the "Warning timer" it does not make much sense as it is only for overload

**Comment by episkorowski** [comment]
Right, that makes sense. How's "Overload timer (seconds)"? I can't make it any longer since it'll get cut off.

**Comment by Adam-** [comment]
I meant a chatbox message for when the overload is about to expire. I thought there was one, maybe not.

**Comment by episkorowski** [comment]
There isn't, I went back and checked just in case. The only chatbox messages are the initial one and "worn off" one.

**Comment by Adam-** [comment]
That is unfortunate. It would probably be worth it to just notify when it is completely worn off instead of adding all of this logic just to give you a ~15s heads up. Otherwise I would probably recommend starting the timer when it gets the initial chat message instead of using animations since it is more reliable.

**Pull request closed without merging**
