### PR TITLE
Add OSBuddy links and popup menus to GE plugin

### PR DESCRIPTION
**Pull request by Shingyx**
Add popup menus to both the offers and search tabs, allowing links to either the official GE prices or the OSBuddy GE prices. Add option to prefer OSBuddy prices when left clicking search results.

Resolves https://github.com/runelite/runelite/issues/4056.

image

### CODE REVIEW

**Comment by deathbeam** [comment]
You should probably just use 1 link, based on ```	@ConfigItem(
		position = 3,
		keyName = "enableOsbPrices",
		name = "Enable OSB actively traded prices",
		description = "Shows the OSBuddy actively traded price at the GE"
	)
	default boolean enableOsbPrices()
``` and not add right-click menu. E.g with OSB prices enabled, the link will be OSB one, otherwise OSRS one. Also, probably you should also factor the OSB price in search

**Comment by Shingyx** [comment]
This could just be me, but I've always wanted a way to lookup prices for an item in the Offers tab to see if prices changed since I made the offer. I feel like the best way to do this is with a popup menu. I also compare OSBuddy and official prices quite often. I'm not sure if I agree with only having one link.

I think the `preferOsbuddyGeLinks` setting I added is redundant though and I should use the existing `enableOsbPrices` setting more. Things like only showing the Lookup OSBuddy GE price menu item if it's enabled, etc. I'll investigate more tomorrow.

**Comment by deathbeam** [comment]
Well, in GE plugin there should not be anything referring to OSB by default, so make sure that everything OSB related requires explicit enabling. Using the enableOsbPrices config option for that is ideal. I guess if you want, keep the right click menu and make OSB primary menu when the option is enabled, but when disabled there should not be any right click menu and it should simply point to GE.

**Comment by Shingyx** [comment]
Changed behaviour to be around the `enableOsbPrices` setting now. More details in commit messages. Haven't factored OSB price in search yet, but I feel that could probably be it's own separate PR.

**Comment by deathbeam** [comment]
Looks like this needs rebase

**Comment by Shingyx** [comment]
Done.

**Comment by Shingyx** [comment]
Rebased again.

**Comment by Shingyx** [comment]
Needs rework now that https://github.com/runelite/runelite/pull/11940 is merged. Closing for now.

**Pull request closed without merging**
