### PR TITLE
Added Guard pickpocket entry swap

### PR DESCRIPTION
**Pull request by Nalerient**
> edit: jagex compliances... Swapped talk-to with pickpocket for H.A.M. guards, should be 69% compliant in the current format. Once Npc attack option is disabled via ingame options, left click pickpocketing should work.

untitled

### CODE REVIEW

**Comment by Nightfirecat** [comment]
From https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features:

> ####Menu Entry Swapping
> - Pickpocket on non-H.A.M. members: Not supported by other 3rd party clients, and absurdly powerful when blackjacking

**Comment by ShaunDreclin** [comment]
It's supposed to be swapping the talk-to option, not attack.

Wouldn't it be better to just do `if (config.swapPickpocket() && target.contains("h.a.m.") || target.contains("guard")` ?

**Comment by Nalerient** [comment]
My bad, wasn't fully familiar with Jagex compliances. Thanks for pointing that out.

**Comment by Nightfirecat** [comment]
What is the left-click option for HAM guards when NPC attack option is hidden? The reason this feature was previously limited to HAM members is because they were the only NPC which were frequently pickpocketed and did not have a talk-to option which became the left-click when NPC attack options were disabled. (eg. It became a convenience feature to not require changing NPC attack options rather than a feature which provided something unattainable in the vanilla client)

**Comment by ShaunDreclin** [comment]
If you hide attack, left click on ham guards becomes talk-to

I don't think extending the functionality to ham guards would be that overpowered, the main concern was with blackjacking

**Comment by Nalerient** [comment]
Still, kinda would love the left click pickpocket for H.A.M. guards tho.

**Comment by Nalerient** [comment]
Sounds good to me. Got an elegant implementation under that furcout of yours? I know very little of runelite api, so yeah...

**Comment by Nalerient** [comment]
Correct me if im wrong but there are only 2 types of H.A.M. npc's with pickpocket option, rendering your `(target.contains("h.a.m.")` part pointless under `if (option.equals("attack"))` statement returning us back to square one :^

**Comment by ShaunDreclin** [comment]
I mean change that line instead of the change you made to the file, cause the option is to swap talk-to with pickpocket, not attack with pickpocket

**Comment by Nalerient** [comment]
My misunderstanding. Thanks for pointing those things out, perhaps this solution will please mod ash

**Comment by Adam-** [comment]
Pickpocket swapping is iffy since it impacts (afk?) exp rates. So far we have only swapped what other clients swap. I probably do not want to swap anything else pickpocket related.

**Comment by ShaunDreclin** [comment]
>You can get left-click pickpockets with HAM members by changing attack settings.

You actually can't. That's why we have it in the plugin in the first place. In the vanilla client it's not possible to left click pickpocket ham members

**Comment by jsmoa921** [comment]
Would be nice to have this feature

**Comment by Trevor159** [comment]
This should be closed as it falls under `Modifies menu options for pickpocketing, such as swapping 'Pickpocket' and 'Talk-to'`  here https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

**Pull request closed without merging**
