### PR TITLE
Add teleport scroll locations to map

### LINKED ISSUE #3214: Add teleport scroll locations to world map
Similar like the jewellery teleports, but then for each teleport scroll. The item sprite can be used for this and would be the most effective way to display it I think.

### PR DESCRIPTION
**Pull request by shmeeps**
Fixes #3214

### CODE REVIEW

**Comment by deathbeam** [comment]
I would probably use the respective teleport scroll images.

**Comment by shmeeps** [comment]
@deathbeam I did start off trying to do so, but once the images get shrunk down to the same size of the other icons (~15px) they all look very similar. If a larger icon (~32px) can be used, I can probably just have it pull the existing image from the ItemID instead.

**Comment by shmeeps** [comment]
Updated to use the full size image, since another person in the issue request had mentioned that as well. Looks a little out of place, but not horrendously so.

image

**Comment by deathbeam** [comment]
hmm, i would just use scaled down scroll, even when they look really similar, just for consistency.

**Comment by Adam-** [comment]
Any reason why this isn't just a new teleport type?

**Comment by shmeeps** [comment]
@deathbeam This is possible if the images are scaled on load. I've added that functionality it. It's a little bulky IMO, but I can't really see any other way of doing it while adhering to the asynchronous nature of the image loader.

@Adam- Originally was, but it adds some extra bulk to the code that is strictly for teleports (ignoring the magic level requirement, extra config checks, and requires binary images to be included). This implementation uses the images that already exist, so it also handled a little differently then say the jewelry teleport indicators. I also think that it might be worth making this generic so that diary items, skill capes, and other item teleports could be enabled through a config option, which this would allow to be added relatively easily.

**Comment by shmeeps** [comment]
Refactored to be more in line with what was done in #3391

**Comment by Adam-** [comment]
I would just stick with one scroll image since these are too small to tell apart, otherwise looks good.

**Pull request merged**
