### PR TITLE
Add ability to disable/enable all plugins

### PR DESCRIPTION
**Pull request by deathbeam**
Add ability to fully disable and enable each plugin. Fully disabling
plugin means removing it from scheduler and eventBus and fully stopping
it. That improves performance, because it basically removes overhead of
any plugin that is disabled.

Fixes: #280 
Fixes: #521 

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview:
screenie

### CODE REVIEW

**Comment by Adam-** [comment]
I am not sure I like this intermixing of the plugin descriptor with the configuration system. I think I would rather see a PluginConfiguration interface which extends the core Config interface that has enabled() and then have the plugin Provide that.

**Comment by deathbeam** [comment]
I can do that, and add the enabled() flag only to PluginConfiguration. But moving of the ConfigGroup contents to PluginDescriptor is required in order of all this to work, because I need name and description and mainly key for each plugin, but I cannot in any way provide "default" annotation for the default configuration.

**Comment by deathbeam** [comment]
Split the update plugins commit to the getConfig update and separate commit for each update of the startup/shutdown method in plugins.

**Comment by deathbeam** [comment]
Updated to use custom PluginManagerPlugin and store configurations in RuneLiteConfig instead of injecting the enabled() to each config class and providing default configurations.

**Comment by deathbeam** [comment]
Just to give more reasons to merge this (because it is good change), I was doing some profiling with JProfiler with everything I could disable disabled on master and on this patch.

Here is the results overview (left is this patch, right is latest master):
screenie

I can provide the JProfiler snapshot files if needed.

**Comment by deathbeam** [comment]
All possibilities how the buttons can look in the end in the config panel currently:

**Comment by deathbeam** [comment]
Based on discord discussion went with the design that is currently in the PR description, also merged Plugin Manager and Config Manager (again) because Plugin Manager is not needed anymore, because external plugin was removed.

**Comment by Adam-** [comment]
Would it be better to have whatever is reenabling the plugins to handle the RegionTileManager logic instead of each plugin?

**Comment by deathbeam** [comment]
Moved the simulateObjectSpawn call from plugin startup methods to PluginManager, right after the startUp method is called.

**Comment by deathbeam** [comment]
Rebased on https://github.com/runelite/runelite/commit/77c11c8cfbed78e40d32896da729fc1699fc672e (small changes were required) and combined the moving of RegionTileManager#simulateObjectSpawns below "Plugin is now running" to commit where RegionTileManager was added.

**Comment by deathbeam** [comment]
Rebased on latest master changes - Removed some new enabled() checks from new fishing minimap spot overlay and Barrows plugin. Also cleared walls and ladders on Barrows plugin shutdown.

**Comment by deathbeam** [comment]
Added additional sorting based on plugin state (enabled/disabled) as well. Preview:

screenie

**Comment by UniquePassive** [comment]
What happens if you want to quickly disable and re-enable a plugin? Does it get moved to the bottom instantly, or is the list only re-sorted upon opening the settings screen?

**Comment by deathbeam** [comment]
It gets moved to the bottom instantly yea.

**Comment by UniquePassive** [comment]
I would like to think that could get annoying, what do you think?

**Comment by deathbeam** [comment]
Well, for regular user, I don't really see a case where you would want to quickly enable/disable plugin. The only case is to reset plugin state, but you would want to do that only if something breaks, so that is not really valid case I guess, because in perfect world it should not break :D

**Comment by SomeoneWithAnInternetConnection** [comment]
I think someone brought up on discord a while ago that reorganizing the plugins like that could get annoying for anyone who is regularly toggling plugins, since it means that entries in the list aren't always going to be in the same spots, making them more annoying to track down

**Comment by UniquePassive** [comment]
I don't think moving stuff around will make users happy. If you disable the wrong plugin, and then have to scroll down to find the one you accidentally disabled, you'll rage. Moving stuff instantly is a bad idea for the user experience.

**Comment by deathbeam** [comment]
I can add configuration for configuration then :D

**Comment by deathbeam** [comment]
Because someone on Discord also requested this feature before.

**Pull request merged**
