### PR TITLE
Update Slayer Task with Partner

### PR DESCRIPTION
**Pull request by breaklulz**
"You have received a new Slayer assignment from $PARTNER_NAME: $TASK_NAME ($AMOUNT)"

### CODE REVIEW

**Comment by raiyni** [comment]
This could be lumped in with the existing progress checker and ignoring the match on username.

**Comment by breaklulz** [comment]
You're right, @raiyni what is the regex for ignoring a match? That way we can use `group(1)` and `group(2)` for both and just do `find() || find()`

**Comment by breaklulz** [comment]
Ok I changed the regex to ignore the username.

What do you all like better?

```java
Matcher mProgress = CHAT_GEM_PROGRESS_MESSAGE.matcher(chatMsg);
Matcher mPartnerNewTask = CHAT_PARTNER_NEW_TASK_REGEX.matcher(chatMsg);
boolean mProgressFind = mProgress.find();

if (!mProgressFind && !mPartnerNewTask.find())
{
	return;
}

String taskName = mProgressFind ? mProgress.group(1) : mPartnerNewTask.group(1);
int amount = Integer.parseInt(mProgressFind ? mProgress.group(2) : mPartnerNewTask.group(2));

setTask(taskName, amount);
```
or
```java
Matcher mProgress = CHAT_GEM_PROGRESS_MESSAGE.matcher(chatMsg);
Matcher mPartnerNewTask = CHAT_PARTNER_NEW_TASK_REGEX.matcher(chatMsg);
if (!mProgress.find() && !mPartnerNewTask.find())
{
	return;
}

String taskName = mProgress.reset().find() ? mProgress.group(1) : mPartnerNewTask.group(1);
int amount = Integer.parseInt(mProgress.reset().find() ? mProgress.group(2) : mPartnerNewTask.group(2));

setTask(taskName, amount);
```

**Comment by breaklulz** [comment]
Here's my updated `Pattern` that ignores the username:
```java
Pattern.compile("You have received a new Slayer assignment from (?:.*): (.*) \\((\\d*)\\)");
```

**Comment by breaklulz** [comment]
```java
@Test
public void testPartnerNewTask()
```
done

**Comment by breaklulz** [comment]
Gonna retry this with a fresh PR. Closed.

**Pull request closed without merging**
