### PR TITLE
Increase inventory tag color count

### LINKED ISSUE #9767: Increase inventory tag color count to at least match OSBuddy (6)
**Is your feature request related to a problem? Please describe.**
OSBuddy allows for 6 item colors/groups, while RuneLite allows only 4. Losing out on the additional colors is making converting to RuneLite challenging.

**Describe the solution you'd like**
Allow users to define an arbitrarily high # of groups they want to use, and to be able to set colors for all of them. I would love to have as many as 10 groups.

**Describe alternatives you've considered**
Allowing users to set 6 fixed tag colors, to at least match what OSB offers, would help a lot!

**Additional context**
Item tagging is extremely useful for inventory management, so the more colors users can specify, the better!

**Screenshots**
RL vs OSB Tags

### PR DESCRIPTION
**Pull request by Krysaczek**
closes #9767

### CODE REVIEW

**Comment by Adam-** [comment]
Why would anyone need *6* groups? Most people use it for gear and there's only 3 combat styles.

**Comment by Marstead** [comment]
> Why would anyone need _6_ groups? Most people use it for gear and there's only 3 combat styles.

OSB Supports 6 and I've used all of them. I could use more, they help with monitoring and sorting my inventory. I use

Group 1 = Trash/Low value items
Group 2 = Valuable loot
Group 3 = Equip-able gear
Group 4 = Consumables/Food/Etc
Group 5 = Quest Items
Group 6 = Ingredients/Reagents

**Comment by vindux** [comment]
> Why would anyone need _6_ groups? Most people use it for gear and there's only 3 combat styles.

Well, why would you NOT want this?!

image

**Comment by Zirro** [comment]
It would be appreciated if this could be merged. It offers more flexibility for anyone who needs it, without getting in the way of people who are satisfied with fewer groups.

**Pull request merged**
