### PR TITLE
Fix low detail mode roofs

### PR DESCRIPTION
**Pull request by DevDennis**
Fixes roofs and probably other stuff on low detail mode

https://github.com/runelite/runelite/issues/1481 partially fixes this issue, tiles at raids and other newer areas are still broken

image

### CODE REVIEW

**Comment by iguaan** [comment]
This just turns off low detail mode?

**Comment by deathbeam** [comment]
It actually does not. I am not 100% where the object composition applies and if it will degrade the performance boost, but when I was testing it it affected only roofts and I personally do not noticed any performance degradation.

**Comment by DevDennis** [comment]
As far I know the object composition low detail just breaks stuff

**Comment by iguaan** [comment]
Wouldn't this make it less of a fix and more of a compromise, since we don't know the effect of object composition?

**Comment by DevDennis** [comment]
I don't think there is any benefit to having object composition enabled so I wouldn't call it a compromise

**Comment by iguaan** [comment]
Could make it as an opt-in setting (default being false), saying it might increase performance but it will also cause graphical glitches in certain areas.

**Comment by SoyChai** [comment]
>Could make it as an opt-in setting (default being false), saying it might increase performance but it will also cause graphical glitches in certain areas.

Just like low detail mode in general? 😃

I'm not against us making fixes to this mode since Jagex has long abandoned it, and it's already completely broken in some areas.

**Comment by iguaan** [comment]
What I meant was: sure, make this the default option, but dont remove the other option completely but keep it as an opt-in option in the subsection for low detail mode with a warning.

**Pull request closed without merging**
