### PR TITLE
Added 5 new Emojis for the Emoji Plugin - Waving Hand, Fire, Eggplant, Alien, and Heart Eyes

### PR DESCRIPTION
**Pull request by kaicianflone**
Added 5 new emojis for the Emoji Plugin including one from #8844 . Been having a lot of fun with it but was wanting more :) 

Thanks for the awesome application! I hope to contribute some more as I learn the API

Fire is `(/\)`
Eggplant is `8=D`
Waving Hand is `(^_^)/`
Alien is `(@.@)`
Heart Eyes is `(*.*)`

### CODE REVIEW

**Comment by Adam-** [comment]
I have basically no opinion on whether or not we should add more emojis. The only limitation is they either must be from twemoji or otherwise the license for them needs to be identified and probably included somewhere.

**Comment by kaicianflone** [comment]
Ok I couldn't find the non-grayscale waving hand emoji at first but those are all from the twemoji emoji set so there are no attribution issues.

Thanks!

**Comment by Adam-** [comment]
The hand wave emoji doesn't look like it is from twemoji to me?

**Comment by kaicianflone** [comment]
Thank you for checking. Looks like I committed a stash. 

Here is the emoji I tested this commit off of: (super small version)

https://emojipedia.org/twitter/twemoji-2.2.3/waving-hand-sign/

**Comment by devLotto** [comment]
The game does not support partially transparent pixels. 

So your emojis look like this:

image

image

This is my process to resize the emojis:

1. Find emoji on emojipedia https://emojipedia.org/grinning-face/, scroll down to Codepoints and copy the 1F600
2. Download the emoji from https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f600.png
3. Open Photoshop, resize image to 13x13 using the Bilinear resampling mode in Image -> Image Size
4. File -> Export -> Save for Web (Legacy)
5. Select PNG-8 and 13x13 size
6. Enable Transparency. Set colors to 256 and Matte to None.
7. Save image

**Comment by devLotto** [comment]
1f525

1f346

1f44b

1f47d

1f60d

**Pull request closed without merging**
