### PR TITLE
Remove freeze timer on Vorkath Zombified spawn death

### PR DESCRIPTION
**Pull request by Nightfirecat**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
One thing I noticed is that there are two zombified spawn ids:

```
public static final int ZOMBIFIED_SPAWN = 8062;
public static final int ZOMBIFIED_SPAWN_8063 = 8063;
```

The latter is what's present in post-quest Vorkath, so I assume the former is the ID of the spawn in the quest Vorkath fight? I'd be happy to add it to the condition if that's wanted.

**Comment by deathbeam** [comment]
For completeness both should be included yeah

**Comment by deathbeam** [comment]
Needs rebase

**Comment by Nightfirecat** [comment]
Rebased

**Pull request merged**
