### PR TITLE
Boss logger Plugin v2

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
**DEPENDS ON #3908**
**Updated version of #3545**

Records loot received from boss monsters in a `.log` file inside the `.runelite/loots` directory.

* Tracks loot received from the boss
* Has a panel showing all loot and the price of each item, see media below.
* Tracks Unique Items from each boss within panel, see media below.
* In-game and system notification alerts with toggle options
* Records loot from certain activities as well, see below

## Currently supported Bosses
<details>
<p>

* Armadyl 
* Abyssal Sire - TESTED
* Bandos - TESTED
* Callisto - TESTED
* Cerberus - TESTED
* Chaos Elemental - TESTED
* Chaos Fanatic - TESTED
* Corporeal Beast
* Crazy Archaeologist - TESTED
* Dag Rex
* Dag Prime
* Dag Supreme
* Giant Mole - TESTED
* Grotesque Guardians - TESTED
* Kalphite Queen - TESTED
* King black dragon - TESTED
* Kraken
* Saradomin - TESTED
* Scorpia - TESTED
* Skotizo - TESTED
* Thermonuclear Smoke Devil - TESTED
* Vet'ion
* Venenatis
* Vorkath - TESTED
* Zammy - TESTED
* Zulrah - TESTED

<p>
</details>

## Currently supported Activities
<details>
<p>

* Barrows - TESTED
* Raids (Chambers of Xeric) - TESTED
* Raids 2 (Theatre of Blood)
* Clue Scroll (Easy) - TESTED
* Clue Scroll (Medium) - TESTED
* Clue Scroll (Hard) - TESTED
* Clue Scroll (Elite) - TESTED
* Clue Scroll (Master) - TESTED

<p>
</details>

## Media

<details>
<p>

Panel Gif:

Example In-game message:

Auto select when on landing page

</details>
</p>

### CODE REVIEW

**Comment by HSJ-OSRS** [comment]
can you make the loot panel sort the loot based on value also d chain doesnt seem to get highlighted on the uniques for kq https://i.imgur.com/3rqGdHy.png

**Comment by TheStonedTurtle** [comment]
@HSJ-OSRS  I Could make it sort by value but right now its sorting by Name which I think makes finding items the easiest. I'm going to leave it as is until i have the time to program toggle options (Sort by Item Name, Item Price, Show by kill, etc)

I updated the D Chain ID to the 3140 variant, I was using the 2513 variant which isn't trade-able: https://i.imgur.com/SSLl5hm.png

As for the Raids items, I've updated ALL unique item checks to now account for both Noted and Unnoted variants;
https://i.imgur.com/3UPDeqH.png

Thanks a lot for finding these issues, let me know if you find any more :smiley:

**Comment by Lalonde33** [comment]
Could you please add support for non-boss monsters that are killed for GP. Monsters such as rune dragons, gargs and wyverns. Thanks

**Comment by deathbeam** [comment]
There is #3174 that adds that

**Comment by HSJ-OSRS** [comment]
vorkaths head id is incorrect the correct id is 21907

**Comment by HSJ-OSRS** [comment]
raids 1 has broken at some point not sure when but it doesnt track the loot for it anymore just done 3 raids none of them got logged

**Pull request closed without merging**
