### PR TITLE
[WIP] Crowdsourced OSRS Wiki telemetry data

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
Per a request by leejt #6688. Thanks to @Forsco for the help.

## API Communication
All telemetry data collection and communication will be handled by the TelemetryManager.

* Holds up to 50 requests in queue before auto submitting
* Submits queue after 5 minutes of inactivity
* Submits queue on logout

## JSON Format:
**date** = milliseconds since Unix Time
**type** = Java Class as a String
**data** = Object of Type converted to JSON

<details>
<p>

```json
{
	"date": 1543503321483,
	"type": "NpcLootTelemetry",
	"data": {"npcID":2838,"items":[{"id":526,"quantity":1},{"id":2136,"quantity":1},{"id":948,"quantity":1}]}
}
```

</p>
</details>

## Telemetry Data

- [X] NPC loot received
- [X] Event loot received (barrows, clue scrolls, CoX/ToB)
- [X] NPC Spawn Locations
- [ ] Teleport tracking
- [ ] Skilling Success/Failure rates (including tools)
	- [x] Cooking
	- [x] Fishing
	- [x] Mining
	- [ ] Thieving
	- [x] Woodcutting
- [x] Motherlode Mine Pay Dirt distribution

### To make contributions to this PR make PRs to my internal branch
<a href="https://github.com/TheStonedTurtle/runelite/tree/TelemetryData" target="_blank">Internal Branch</a>

### CODE REVIEW

**Comment by 15987632** [comment]
You should track personal/team deaths also for ToB loot. Also points for CoX and % for barrows. Sorry if you are already doing this but it doesn't look like it unless i'm dumb.

**Comment by Joshua-F** [comment]
> NO TELEMETRY DATA WILL BE COLLECTED IF THE TELEMETRY PLUGIN IS DISABLED, WHICH IT IS BY DEFAULT

I think it should probably be opt-out instead of opt-in since a majority of people wouldn't opt-in most likely.

**Comment by deathbeam** [comment]
There are multiple things wrong with this PR:

1. You created external manager that depends on plugin
2. You altered PluginManager for no reason
3. You have data structures in telemetry plugin for no reason that are used from other plugins and that are only relevant to those plugins

**Comment by TheStonedTurtle** [comment]
1) I Figured having a manager based on the plugin state would make opting in/out easier since this may span multiple different plugins. What should I do instead?
2) I altered PluginManager to use the Class name instead of the Plugin instance so I can check the Plugin State by class name (used in step 1.) 
3) I can only think of the `PestControlTelemetry` file which falls under this and I will move it to the Pest Control plugin. I thought keeping all new Telemetry related files inside the plugin was preferred.

**Comment by deathbeam** [comment]
- Then maybe make the plugins depend on that plugin instead, or just move everything to manager, ditch plugin, and use config option.
- You already injected entire plugin to the manager in 1st step , you did not needed to alter plugin manager at all
- They have no reason to be there, and the structs for "telemetry" can be used for other purposes too, just give them sane names

**Comment by TheStonedTurtle** [comment]
I've moved the TelemetryManager and TelemetryClient into the Plugin Folder, reverted the PluginManager changes, changed the plugin to be enabled by default, and removed the Pest Control Telemetry data.

If there are any other structure changes that I should make let me know.

**Comment by forsco** [comment]
> You should track personal/team deaths also for ToB loot. Also points for CoX and % for barrows. Sorry if you are already doing this but it doesn't look like it unless i'm dumb.
> 
> Edit: and mvp for ToB, but i'm not sure the client can get that information without the player looking at the scoreboard thing.

@15987632 

Do team deaths take a toll on personal loot? I thought ToB was local player specific for your own rewards?

**Comment by 15987632** [comment]
> > You should track personal/team deaths also for ToB loot. Also points for CoX and % for barrows. Sorry if you are already doing this but it doesn't look like it unless i'm dumb.
> > Edit: and mvp for ToB, but i'm not sure the client can get that information without the player looking at the scoreboard thing.
> 
> @15987632
> 
> Do team deaths take a toll on personal loot? I thought ToB was local player specific for your own rewards?

We don't know how it works and jagex hasn't given enough information to assume anything other than saying its affected by your "teams performance." I'm pretty sure from  my experience that your regular loot isn't affected by your other teammates deaths but for items/pet it isn't known.

**Comment by forsco** [comment]
> > > You should track personal/team deaths also for ToB loot. Also points for CoX and % for barrows. Sorry if you are already doing this but it doesn't look like it unless i'm dumb.
> > > Edit: and mvp for ToB, but i'm not sure the client can get that information without the player looking at the scoreboard thing.
> > 
> > 
> > @15987632
> > Do team deaths take a toll on personal loot? I thought ToB was local player specific for your own rewards?
> 
> We don't know how it works and jagex hasn't given enough information to assume anything other than saying its affected by your "teams performance." I'm pretty sure from my experience that your regular loot isn't affected by your other teammates deaths but for items/pet it isn't known.

Okay, I'll look into adding in local player deaths and team mate death counts.

**Comment by 15987632** [comment]
To add to what I said about % at barrows also being tracked the brothers killed should be tracked also, as they directly affect the items you receive.

**Comment by TheStonedTurtle** [comment]
@15987632 Should we track which brothers were killed? currently there's just a number for how many. Whatever is needed lmk.

**Comment by 15987632** [comment]
> @15987632 Should we track which brothers were killed? currently there's just a number for how many. Whatever is needed lmk.

Probably yes, iirc you can only get items from the brothers you kill so it should be obvious from the result but it but it still directly affects the loot so it should be added. To my knowledge any factor that affects the end result should be added in.

**Comment by TheStonedTurtle** [comment]
I've cleaned up the commit history some and this plugin is working with the current features. A code review would be useful to know if I could accomplish some of these tasks easier/more efficiently.

**Pull request closed without merging**
