### PR TITLE
Add !layout command to Raids plugin

### PR DESCRIPTION
**Pull request by deathbeam**
Add support for !layout command to raids plugin that will stream current
raid layout to everyone who will see the message.

The code for displaying the chat message is partially from #3919 and
from #2992 so thanks for the work done in those PRs.

Closes #4354
Closes #3919
Closes #2992

Signed-off-by: Tomas Slusny slusnucky@gmail.com

screenie

### CODE REVIEW

**Comment by deathbeam** [comment]
Added validation for the !layout command input to service: https://regexr.com/45tac

**Comment by Adam-** [comment]
Validation should be at least client side

**Comment by deathbeam** [comment]
Doesnt that kind of defeat the point of the validation

**Comment by deathbeam** [comment]
As Jagex is going to remove scouting in future (based on their blog post) I am going to close this PR for 2nd time :D

**Comment by lyzrds** [comment]
It seems that jagex is pretty happy with the current meta of raids/scouting, i feel this should be reconsidered.

**Pull request closed without merging**
