### PR TITLE
Wilderness obelisk teleport spots on map

### LINKED ISSUE #4216: Game map: add levels of wilderness on the wilderness obelisks
On the in game map add the wilderness level on the obelisks so you know where you want to go to. Or alternatively add lines of the wilderness on the map ie lines of 5 or 10 intervals.

### PR DESCRIPTION
**Pull request by raiyni**
Fixes #4216

### CODE REVIEW

**Comment by Nightfirecat** [comment]
@raiyni Wilderness lines and obelisk teleport spots should be separate PRs.

**Comment by deathbeam** [comment]
The obelisk part looks good, except I would probably use more friendly icon that will fit the map more.

**Comment by raiyni** [comment]
Okay, I'll rebase.

@deathbeam that is the ancient crystal icon, really it can be whatever though.

**Comment by raiyni** [comment]
This icon is based on the ancient staff top.

**Pull request merged**
