### PR TITLE
Fix issues with Hiding styles and expand options

### PR DESCRIPTION
**Pull request by Dreyri**
Changes:
- use list rather than hashtable to eliminate unused information
- ability to restore original widgets hidden value on shutDown and when turning some options off (see img)
- register sotd/sol as a magic weapon
- making the plugin able to handle magic autocasting in a consistent manner rather than hardcoding behaviour
- Mixin to as a workaround for widgets not being hidden when exiting casting interface
- having the defensive casting interface open now counts as defensive casting as using the spellbook with this interface open will yield defensive casting xp
- ability to block styles 1-4 and show warning for them
- ability to remove auto retaliate box (not text)

### CODE REVIEW

**Comment by lulwut** [comment]
I don't know much about how the client works and what we can and cannot do,
but having the auto retaliate text visible just seems.. Idk. Is it possible
to also add an overlay to block the text (e.g. Use the existing background
and put it on above the text - could whip an image up in a few minutes if I
was at my pc).

Only issue would be when transparency is on..

Alternatively a dark greyed out version of auto retaliate could be placed
over the existing button?

Code is not my thing so I have no clue if this is possible, but it might be
a bit of a more elegant solution?

**Comment by Dreyri** [comment]
The removing of auto retaliate is mainly to prevent missclicks.
I could easily just hide the text as well but I thought people would like to still be able to see their auto retaliate settings.
I guess it would be more consistent with hiding everything for the other options, which is necessary for the first 4 attack styles because their click listener is tied to the container.
More opinions would be appreciated.

**Comment by lulwut** [comment]
Ah okay, I'm all for consistency. I think users might be confused as to why
it is different than everything else.

**Comment by deathbeam** [comment]
Closing as this is very old PR now and has a lot of merge conflicts, reopen if you want to re-implement it.

**Pull request closed without merging**
