### PR TITLE
api: Ultimate Ironman account type

### PR DESCRIPTION
**Pull request by Obasill**
Figured I'd add this since it's missing, also it's nice for one of the diaries I'm working on for the quest helper.

### CODE REVIEW

**Comment by Hydrox6** [comment]
The other functions check for a range of values; this is the same as `== AccountType.ULTIMATE_IRONMAN`

**Comment by Obasill** [comment]
Ah gotcha, however I'm throwing errors unless I'm using `AccountType.ULTIMATE_IRONMAN.isIronman()`
For my if check, will this still work properly? I don't have an UIM account to check.

**Comment by Hydrox6** [comment]
You are probably doing something very *very* wrong

**Comment by Obasill** [comment]
Yeah, 7am and no sleep will do that to you. Thanks for the help.

**Pull request closed without merging**
