### PR TITLE
falconry plugin

### PR DESCRIPTION
**Pull request by stealthAngel**
https://www.youtube.com/watch?v=QiJ06C2k19Y&feature=youtu.be

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The linked video is unavailable.

Also, what functionality does this plugin provide which isn't already available via the NPC Indicators plugin?

**Comment by stealthAngel** [comment]
video link should be fixed now

**Comment by stealthAngel** [comment]
you're right.... there is an npc indicator l0l

**Comment by psikoi** [comment]
> you're right.... there is an npc indicator l0l

So I guess this can be closed?

**Pull request closed without merging**
