### PR TITLE
Extend shift-click customization to support changing default item action

### LINKED ISSUE #971: Split up the "Teleport item" option in the menu entry swapper plugin
Make it possible to differentiate between 1 click teleports like Kandarin headgear, multi-teleport items like amulet of glory and multi-function items like slayer ring. 1 click items is mostly because they are easily clicked by mistake and multi-function items should have their own category since they aren't solely a teleport item.

### LINKED ISSUE #1452: Menu Entry Swapper
please separate the 'Teleport item' for the dueling ring and the crafting skill cape please make two different options for them because i want to enable one and not the other.
also for the construction cape are we able to change it to tele to home? and not the teleport or are we able to customize that without clicking the shift and just the left click?

### LINKED ISSUE #1536: Ardougne Cloak not included in left click teleport for menu swapper.
The ardougne cloak is not left click teleport even though the config description states it will be. This might be due to recent QoL changes to the cloak and Morytania legs.

### LINKED ISSUE #1599: "use" as left click on Imp box
The option to have "use" as left click on "Imp-in-a-box(2)" and "Imp-in-a-box(1)", instead of "bank".

### LINKED ISSUE #1848: Re-add Silver Sickle (b) in Menu Entry Swapper
This was in here a few days ago and now it's gone? Can it be added again?

### LINKED ISSUE #1860: QoL - Add Dwarven Rock Cake to Menu Entry Swapper
It would be awesome if we can swap the eat and guzzle options for Dwarven Rock Cakes. Would reduce the number of right clicks I need when trying to get to 1 HP for NMZ (dharoks)

### LINKED ISSUE #1861: QoL - Don't Menu Swap Rub on Empty Jewelry
Items like glory/skill's necklace/wealth still swap the rub option even though they are empty of charges.

### LINKED ISSUE #2361: Switch Options on Con/Craft Cape
Instead of Wear 1st option make it "teleport to poh" and the same for crafting

### LINKED ISSUE #2585: Add fish to the menu entry swapper (Swapping use and drop)
- Leaping sturgeon
- Leaping trout
- Leaping salmon
- Salmon
- Trout

### PR DESCRIPTION
**Pull request by Kamielvf**
This will extend the current shift-click customization to add a "force" shift-click option.
Forcing an item's shift click will make the first entry (left-clicking the item) always be the customized/default shift-click. Main items this would be useful for are teleport capes/jewelry.

The way this works is by toggling the client's shift-click mode on when the user hovers over an item that has this setting set.

Things this will not do:
- Allow user to have a changed first op and shift-click another op

Preview:
preview

Fixes #2585
Fixes #2361
Fixes #1861
Fixes #1860
Fixes #1848
Fixes #1599
Fixes #1452
Fixes #1536
Fixes #971

Will cover the following PRs:
Closes #1555 
Closes #1933
Closes #2118

Relevant: #1558

### CODE REVIEW

**Comment by SoyChai** [comment]
Really loving the functionality on this. Two great features becoming greater together.

I feel like the `Force` `Shift-click` could be worded more clearly, though. Maybe `Force as` `Left-click` would be easier to understand from first glance?

**Comment by Kamielvf** [comment]
I'm fine with renaming the menu entry to something else. Currently it just describes what it's actually doing since I had no other ideas of what to name it.

**Comment by Kamielvf** [comment]
Commit 2ed6a1a is the same as the commit in #1554 but I probably messed something up so the hash isn't the same anymore.

**Comment by Kamielvf** [comment]
Seeing as there are often menu entry swap PRs I will wait with rebasing this until this PR is approved.

Menu entry swap PRs:
#1663, #1759, #1832, #1833

**Comment by Kamielvf** [comment]
Rebased + added spirit tree travel swap, as this was missing due to me moving all the travel related swaps under the NPC_FIRST_OPTION statement and the spirit tree being an object.

**Comment by Kamielvf** [comment]
Closing, will reopen when updated

**Comment by 0xDREAMS** [comment]
For anybody that googles their way here and still can't figure it out because *it's still not obvious*:

**Comment by deathbeam** [comment]
You can right click menu entry swapper plugin in sidebar and it takes you to the wiki where it is explained.

**Pull request closed without merging**
