### PR TITLE
Keep special attack counter up for multiple phases and when attacking minions [WIP]

### LINKED ISSUE #2741: Keep specs up for both phases of kq
Currently def specs only stay up for first phase. Would be nice if it would stay up for both.

### PR DESCRIPTION
**Pull request by Infinitay**
Fixes #2741 

Doesn't remove the special attack indicator if the current NPC ID is equal to KQ's first phase ID

**Changed this PR to WIP because it's been nearly a month since I last tested these changes. On top of that, there has been changes to the plugin merged with master needing to be resolved.**

### CODE REVIEW

**Comment by deathbeam** [comment]
I would probably do this in some enum-based-generic-way. As same issue will apply to Vetion, and ughh, if you can somehow rambo spec zulrah then probably zulrah too.

**Comment by Adam-** [comment]
I've updated this as suggested.

**Comment by Infinitay** [comment]
Thanks Adam, I wanted to do it as you suggested Adam but I thought only KQ had different phases so I didn't mess with it. As for Vetion, I've never fought it, but I'll try to get it's second phase. 

For Zulrah, honestly, I don't think anyone specs it, but if they were to, they'd have to use the Dorgeshuun crossbow as it's the only ranged weapon that reduces the opponents defense. I highly doubt anyone would attempt Zulrah with it, but I will add the crossbow to `SpecialWeapon` enum

**Comment by Infinitay** [comment]
Should handle Vet'ion and KQ correctly now, keeping the counter up after their initial phases. Also, I made it to where if you interact with the bosses minion, for example, the hellhounds at Vet'ion, the indicator will still stay

**Comment by Nightfirecat** [comment]
@Infinitay What's the status on this PR? Looks like it needs rebase if nothing else.

**Comment by Infinitay** [comment]
To be honest, I don't remember and I haven't played RS in some time now. IIRC, maybe it was during the summer when another PR was merged to fix KQ and some other bosses? Can't quite remember though.

**Comment by deathbeam** [comment]
Yeah the problems with multiple-phase bosses were fixed so this PR is now relevant only for when you attack minions, what is probably not that important.

**Comment by deathbeam** [comment]
This PR has a lot of conflicts and it is also probably no longer necessary, closing

**Pull request closed without merging**
