### PR TITLE
Add GE limits

### PR DESCRIPTION
**Pull request by 15987632**
taken from here https://twitter.com/JagexMaz/status/1075735514421096451

The 6 items that weren't added are 

Bronze hasta(p+)
Bryophyta's Staff
Gilded magic wardrobe
Necklace of Anguish (or)
Opulent table
Rainbow scarf

The only one that actually should be added is the bronze hasta be itemManager.search(); doesnt include it currently and I don't know why. The rest are untradables/arn't sold on the GE

### CODE REVIEW

**Comment by deathbeam** [comment]
But Bryophyta staff is tradeable

**Comment by 15987632** [comment]
> But Bryophyta staff is tradeable

The uncharged version is tradable, not the charged version. The uncharged version is in the json.

**Comment by 15987632** [comment]
Ok, now this should have everything from the spreadsheet accurate except the following
Bryophyta's Staff (untradable)
Necklace of Anguish (or) (untradable)
Rainbow scarf (untradable)
Snake hide (2 variation with the same name)
Sweetcorn (3 variations with the same name on the sheet although only two of them are on the ge)

**Comment by 15987632** [comment]
Closing cause abex has started this and probably did a better job than me

**Comment by 15987632** [comment]
This is finished now btw and there shouldnt be anymore fixes

**Pull request merged**
