### PR TITLE
Plugin - Climb Switcher

### PR DESCRIPTION
**Pull request by killje**
A plugin that puts the climb-up (climb-down when holding shift) option on top for stairs and ladders that go up and down

### CODE REVIEW

**Comment by killje** [comment]
The last build resulted in a ``java.net.SocketTimeoutException: connect timed out`` and does not seem to be the cause of the commit itself

**Comment by Adam-** [comment]
This could probably just go into the menu entry swapper plugin?

**Comment by killje** [comment]
Maybe it could, but it does uses a shift modifier that non of the menu entries use in the swapper plugin

**Comment by killje** [comment]
I can add it no problem, i just don't know if i should add a "new" feature to the swapper plugin with different actions than it normally has

**Pull request closed without merging**
