### PR TITLE
Kourend Library - Improvement (Hint arrow, tile state color, hide duplicate books/dark manuscript, refactor)

### PR DESCRIPTION
**Pull request by Koekkruimels**
- Added option to hide dark manuscripts. 
- Added option to hide duplicate books.
- Added option to show hint arrow to the requested book (staircase support).
- Added color to bookcase tile indicating if you already have this book or nor and if this book is requested.
- Added color to the library npcs indicating if you can assist him/her or can deliver the book you might already have.
- Refactored a lot to increase readability (extract method/class, variable/parameter renaming)

### CODE REVIEW

**Comment by deathbeam** [comment]
Travis is failing, and before anyone will be able to review this, you should split this commit to multiple (e.g to refactor, the hide options, coloring, hint arrow)

**Comment by Koekkruimels** [comment]
Travis issues have been resolved.

@deathbeam Could you explain what you mean by splitting this commit up? Multiple branches -> pull requests I would assume, but that seems like a lot of hassle due to the intertwined connection of all the changes. I do understand that the size of this Pull Request is rather large.

**Comment by deathbeam** [comment]
1 pull request, multiple commits

**Comment by Koekkruimels** [comment]
How would you approach this? **git reset mixed** and then start committing them separately?
I would have a rough time excluding each feature...

**Comment by raiyni** [comment]
`git soft reset HEAD~2`

and then commit as you would

**Comment by Koekkruimels** [comment]
Finished splitting up large commit in many smaller ones.

**Comment by Abextm** [comment]
- Your commit messages seem to have not much to do with what the commit actually changes
 - Commit messages should be <=72 chars
 - You should import [this xml](https://github.com/runelite/runelite/wiki/Code-Conventions) and make sure your code is formatted correctly to it
 - You have a lot of extra whitespace, remove it
 - You rename a lot of stuff for no reason; don't do that
 - You make some things public that were package private for no reason; don't do that

**Comment by Koekkruimels** [comment]
@Abextm 

Thank you for your comments, although I'm quite uncertain what you expect me to change since that is not explained for every mentioned comment.

* Your commit messages seem to have not much to do with what the commit actually changes
  * Beside the big refactor commit, which was a mess due to a git reset, I do disagree.
* Commit messages should be <=72 chars
  * This rule has not been mentioned somewhere on the wiki or readme. After reading some posts about the reasoning, I do understand why it is preferred and I will limit my commit messages from now on.
* You should import [this xml](https://github.com/runelite/runelite/wiki/Code-Conventions) and make sure your code is formatted correctly to it
  * That XML is already used to format my changes, if you found code style mistakes, let me know.
* You have a lot of extra whitespace, remove it
  * Besides a few cases, which I addressed, I don't find any other logical places.
* You rename a lot of stuff for no reason; don't do that
  * In order to add new functionality to this plugin, I had to understand what the plugin was doing and that was rather difficult when variables and parameters have only one character and function have multiple responsibilities. For example, if you are defining a variable "Book b" at the start of a function and you use it again at the end of a function that contains hundreds of lines of code you will forget the meaning of "b", besides that, I don't see the negative side of writing them down more explicit. And there were also a lot of functions that had many responsibilities and were unclear what each section was doing, it makes no more than sense to extract method of even class to increase readability and maintainability, the reasoning to disallow creating a new function if it is only called from one place is for me pretty unheard of for me, at least in the trade-off I mentioned earlier. 
* You make some things public that were package private for no reason; don't do that
  * Could you point out these changes that were done for no reason?
* You have split stuff into multiple methods with single callsites for no reason; don't do that
  * See answer "You rename a lot of stuff for no reason; don't do that"

I hope you understand my uncertainties and can address them, I understand that this Pull Request has more changes than you would expect and might not be immediate to the standards you desire.

**Comment by Abextm** [comment]
- Your refactor commit includes alot of stuff from other commits, like the hint arrow, sections, etc.
 - Commit messages being <72 chars is just a thing you do with git
 - Your imports have newlines and wildcard imports, which we disallow
 - Spliting methods [like this](https://github.com/runelite/runelite/pull/7909/files#diff-ef1f85ab2de4bceeda0b10bb54fb34eaL72) makes code review a pain, destroys the commit history, and makes the code harder to read, decreasing my ability to maintain it because now neither of us fully understand how it works. Renaming variables like `g` to `graphics` only adds fluff to the code, because you can always tell that `g` is a `Graphics2D` because of how its used. Changes [like this](https://github.com/runelite/runelite/pull/7909/files#diff-6bc3d8d5d111e9910abc803a4f6eb23eR72) don't really matter, but add no value and destroy the commit history, so I would prefer to not see them.
 - https://github.com/runelite/runelite/pull/7909/commits/62cfbd880e393e5ba0e545249e51df64c6d0f687#diff-0ac3a816976b208b0764954b57161d88R62

**Pull request closed without merging**
