### PR TITLE
Change the Jewellery Count plugin to Item Charges and added more options.

### PR DESCRIPTION
**Pull request by Mitchell-Kovacs**
Renamed plugin as it also modified non jewellery items, imp-in-a-box and waterskin. 
- Added more overlay toggle options for them.
- Added the ability to configure the color when charges hit a certain number.

I can move the watering can from Tithe Farm plugin to here if you find that fits better.

### CODE REVIEW

**Comment by Adam-** [comment]
I've rebased this into a commit to do the renaming, and another to add the color config. Moving the watering cans here would probably be good as well.

**Comment by Mitchell-Kovacs** [comment]
I fixed a small problem with your rebase (getting charges on a null item) and in a new commit I moved the watering can overlay from the Tithe Farm plugin to Item Charge.

**Comment by Mitchell-Kovacs** [comment]
I happened to notice #3727 so I decide to add this on top because it makes sense.

**Comment by Adam-** [comment]
I had intentionally removed that INVALID thing since that is not a good solution, I guess I had messed it up. I re-did it now.

**Comment by Mitchell-Kovacs** [comment]
Fair enough, I'll keep that in mind for the future.

**Pull request merged**
