### PR TITLE
fix nightmare loot tracking

### PR DESCRIPTION
**Pull request by umer-rs**
Fixes https://github.com/runelite/runelite/issues/16943

### CODE REVIEW

**Comment by Adam-** [comment]
Why are you changing the wall beast area logic? I believe it works and has no issues. And what is the significance of this 3 tick loot spawning window? Why not 1 tick? What we have now uses the entire duration specified in `delayedLootTickLimit` starting from the npc change, which I am not really opposed to. Though the 15 tick nightmare death is rather exaggerated.

**Comment by umer-rs** [comment]
> Why are you changing the wall beast area logic? I believe it works and has no issues. And what is the significance of this 3 tick loot spawning window? Why not 1 tick? What we have now uses the entire duration specified in `delayedLootTickLimit` starting from the npc change, which I am not really opposed to. Though the 15 tick nightmare death is rather exaggerated.

> Why are you changing the wall beast area logic? I believe it works and has no issues.
It is bugged. If you kill it with a weapon that has a delay, and run away, it doesn't work.

> And what is the significance of this 3 tick loot spawning window?
The 2 tick loot window is the exact tick the loot spawns on, and 1 tick leeway after that. If we allow for checking every tick, dropping items will proc the `processDelayedLoot`. I'm not opposed to making it only work for 1 specific tick though.

**Comment by Adam-** [comment]
> > Why are you changing the wall beast area logic? I believe it works and has no issues.
> 
> It is bugged. If you kill it with a weapon that has a delay, and run away, it doesn't work.

This type of information is good to include in either a comment, the commit message, or the PR description. Ideally, this should be in a separate commit. 

> 
> > And what is the significance of this 3 tick loot spawning window?
> 
> The 2 tick loot window is the exact tick the loot spawns on, and 1 tick leeway after that. If we allow for checking every tick, dropping items will proc the `processDelayedLoot`. I'm not opposed to making it only work for 1 specific tick though.

```java
		if (delayedLootNpc != null && --delayedLootTickLimit < 2)
		{
			processDelayedLoot();
			// Handles cases where the npc dying is not caught by the client.
			if (delayedLootTickLimit < 0)
			{
				clearDelayedLootNpc();
			}
		}
```
This is 3 tick because of delayedLootTickLimit=1, delayedLootTickLimit=0, delayedLootTickLimit=-1

**Comment by Adam-** [comment]
@umer-rs I have squashed the commits and added some comments. Can you review that it still looks ok? (Particularly for Duke and NM)

**Comment by umer-rs** [comment]
Code changes look good. Will test in game tonight just for a sanity check.

**Comment by umer-rs** [comment]
👍 Looks good to me in game. Killed the 3 mobs affected and it works as expected.

**Pull request merged**
