### PR TITLE
screenmarkers: Add screen marker grouping

### LINKED ISSUE #3205: Screen Marker Grouping
First of all thank you for screen markers plugin, its going to be so useful for skilling.

Would be really nice if I can group markers together and toggle the group visibility so that I can have a group for different things.

Thanks!

### PR DESCRIPTION
**Pull request by Zakru**
Screen marker groups can now be added. Screen markers can then be added
to those groups. The visibility of a whole group can be set at once.

I chose this kind of "tabbed" layout as I find it intuitive regarding how the feature operates. Here is the "main group", aka the markers without a group.
image
And here is a group with some markers, with buttons for visibility, removal and renaming for the group.
image

Closes #3205

### CODE REVIEW

**Comment by raiyni** [comment]
a gif/image would be nice

**Comment by Adam-** [comment]
You mentioned earlier in Discord that there is a bug with the screen markers panel adding duplicate mouse listeners whenever it is rebuilt. Can you test if https://github.com/Adam-/runelite/commit/7c68cb21600bd96ac30953ec53b8b3fde9b7abe4 fixes it?

**Comment by Zakru** [comment]
This should be good to go now.

**Comment by Zakru** [comment]
Nevermind, just spotted an little error.

**Comment by raiyni** [comment]
I think it would make more sense to have the groups show as parent boxes instead of being in a dropdown. 

Then you can:
*  Thumb through them and turn them on/off without having to guess which is on/off in the dropdown. 
* Maybe drag screen markers between groups

**Comment by Zakru** [comment]
@raiyni I did consider that as well, but I thought it might defeat the purpose of groups and make them harder to keep organized. The drag-and-drop feature could, of course, be handy. I also don't think there is a need to toggle several groups on/off in quick succession. I could, though, add some indication of whether groups are visible in the dropdown menu (perhaps a darker shade of text for invisible groups?).

**Comment by bloodred** [comment]
+1 this would be really helpful, also being able to move markers up/down to categorize them better

**Comment by Zakru** [comment]
@bloodred I actually made this organization system for my external plugin, based on my ideas while thinking about this PR.


I am planning to maybe take up the screen markers once again and implement a similar system, but I haven't had the time to do so yet.

**Comment by Nightfirecat** [comment]
Needs rebase

**Comment by orlp** [comment]
@Zakru Would love it if you could bring this feature to Runelite, if you have the time.

**Comment by Zakru** [comment]
I don't mind, I haven't touched this PR in a long time. Although, I made a similar grouping system in my advanced notifications plugin, which I feel is close to the best solution to this issue. Anyway, I'm not actively developing this anymore so I will close this PR.

**Pull request closed without merging**
