### PR TITLE
Chat message on virtual level up + Level up event

### PR DESCRIPTION
**Pull request by Haashi**
First look at #6619 feature-request.

First commit is about adding an event on level up (any level, even real level) and xptracker posting the event.

Second one is adding the message in the chatbox using the already existing virtual level plugin.

Any suggestions is welcome.

### CODE REVIEW

**Comment by Haashi** [comment]
any idea what can post the event then ? because the leveling up is quite related to xp tracking, don't really know how we can trigger it without tracking XP.
Could track XP inside a non plugin class, but that would be duplicating code/task right ?

**Comment by deathbeam** [comment]
Well it is not really related to XP tracking. You can either copy-paste the code, or just look how it works, and use parts of it (we already do that at bunch of places, it is pretty simple)

**Comment by Haashi** [comment]
Updated. Did it my own way to check after every ExperienceChanged event.

**Comment by melkypie** [comment]
This has been added in runelite/plugin-hub#171

**Pull request closed without merging**
