### PR TITLE
slayer: fix the plugin computing on free-to-play worlds

### LINKED ISSUE #3628: Slayer task showing up after losing members in a F2P world
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

### PR DESCRIPTION
**Pull request by adwitkow**
closes  #3628

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Technically, #4012 fixes this as well, and I rather prefer that solution personally.

**Comment by adwitkow** [comment]
While #4012 does seem more elegant, while using it I can make the infobox appear on a free-to-play world by flipping the Task Infobox config item.

**Comment by Adam-** [comment]
I much prefer #4012, though I feel like it will probably come back as a config option... maybe we can  just deal with that then, but it should really only have a world check ~1 place. Maybe two if we really care to block the config change thing but I don't think many people will hit that.

**Comment by Adam-** [comment]
If you really want to block the npc highlights I suppose we can do that. The rest of this I think either can't happen (the chat messages) or shouldn't be blocked (!task)

**Comment by Nightfirecat** [comment]
Most of this is covered now that #4012 has been merged. If blocking NPC highlights is wanted, this PR can be reopened with those specific changes, or it can be added in a separate PR.

**Pull request closed without merging**
