### PR TITLE
Add support for searching multiple inventories to InventoryItemQuery

### LINKED ISSUE #1070: Add some sort of centralized inventory/equipment system
Various plugins behave differently depending on what you have in your inventory or equipped. Rather than every plugin scanning the inventory constantly, it'd be good if there was a single system doing it. Then to check it, you could do things like `inventory.contains(CHISEL)`, `equipment.contains(RUNE_PICKAXE)` etc.

Being able to test for all of or any of the items in an array/list/set/etc of items would be nice too.

### PR DESCRIPTION
**Pull request by ShaunDreclin**
Also includes an option to require *all* listed item ids instead of any

Resolves #1070

### CODE REVIEW

**Comment by HelloKitty** [comment]
You modified the copyright? You do not have the copyright to this code, you may hold a copyright to the diff but that's different.

You removed Lombok's annotation for auto-ctor generation, no reason to deviate away from this.

You completely broke the design of implementing Query<,> by not utilizing the base Type's predicate. Either with Streams or otherwise.

This violates the concept of SRP, there is no reason the query object should allow for queries against multiple inventories. Either implement a new Query<,> or decorate the original to provide multiple inventory queries.

On top of that this could be implemented as a couple lines with Streams filtering and combining.

**Comment by ShaunDreclin** [comment]
I did, as others have been doing when they have made modifications. Nobody has raised an issue with it before. I even asked and was told it was fine. If that policy has changed, then I'll stop doing it.

Lombok's annotation does not support varargs.

I asked for assistance with it and nobody offered any, so I made it work as I knew how to. I did say somebody else should be the one to implement this but nobody else wanted to work on it.

Please feel free to implement the features yourself if you have a better way of doing it.

**Comment by devinfrench** [comment]
I think a ``containsAll`` or ``findAll`` method should not be within the query class itself as the filters are for each item individually and not the items collectively. However, there isn't currently an API class that it fits into.

Here's an untested example of how I'd do multiple inventories.
```java
private final InventoryID[] inventories;

public InventoryItemQuery(InventoryID... inventories) 
{
	this.inventories = inventories;
}

@Override
public Item[] result(Client client)
{
	List<Item> items = new ArrayList<>();
	for (InventoryID inventory : inventories)
	{
		ItemContainer container = client.getItemContainer(inventory);
		if (container != null)
		{
			items.addAll(Arrays.asList(container.getItems()));
		}
	}
	return items.stream()
			.filter(Objects::nonNull)
			.filter(predicate)
			.toArray(Item[]::new);
}
```

**Comment by ShaunDreclin** [comment]
That looks to me like it would work, but it raises two issues.

- Would `.toArray()` return null if given an empty list/stream? Current uses of the query rely on that.
- Where would be a better place to put the `.findAll()` logic? I don't think re-writing that logic every time it's needed would be good.

**Comment by HelloKitty** [comment]
@devinfrench implementation seems better. Including the original base/super's predicate which is a critical difference. Though [Stream's Flatten](https://www.wangler.io/blog/2017/java8-streams.html) may be cleaner for processing multiple inventories.

As for expected behaviors of current uses of InventoryItemQuery:
* [ClueScrollPlugin](https://github.com/runelite/runelite/blob/2869f24d06a1920e7df4728bab8d13dfa3dfef7f/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java#L237) does check the nullness. But this should not effect the result if the collection is empty instead of null.
* [RunecraftPlugin](https://github.com/runelite/runelite/blob/333629c8dc4d1214cb122da8c7950622f1a14cfa/runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java#L195) checks both nullness and length. So that would be fine.

I too agree with @devinfrench that the InventoryItemQuery object's responsibility is querying against a single inventory. The mention of SRP, while thumbsdown and ignored, it's pretty valid here. You're essentially changing the responsibility and giving the current Type more responsibilities for working with multiple inventories. Querying multiple may be best left up to another object. Either a [decoration](https://en.wikipedia.org/wiki/Decorator_pattern), though not technically a decorator in the traditional sense, would work fine. This would adhere to both SRP and DRY. A bonus.

Though in your defense there are some Query<,> implementations in the project that do operate on multiple flattened collections like [TileObjectQuery](https://github.com/runelite/runelite/blob/5f21163163d3c3b37c220aa7d0095b5bc2b878b7/runelite-api/src/main/java/net/runelite/api/queries/TileObjectQuery.java) so it wouldn't go against convention seen in other Querys. I wouldn't have implemented it that way. In fact more fine grained query control, especially for something so large and expensive such as tile searching, might be better. It's odd that such a feature is not provided. Providing potential for plugins to only query/search explicitly could yield performance gains in the future.

Anyway, I have no stake in this and was merely offering input/codereview. The Github "reactions" on my post only let me know who not to trust when it comes to design decisions on projects lol. Making use of the predicate though is **absolutely** mandatory and not doing so would definitely be or cause a fault in the future. It is the design of the Query<,> types to rely on the predicate.

**Comment by HelloKitty** [comment]
However someone else read what I wrote is how **they** wanted to read it, by no intention of my own. The statements were neutral.

**Comment by ShaunDreclin** [comment]
Code is emotionless, people aren't. This is a project involving both.

That's out of scope of this discussion though, I think I would like somebody higher up to weigh in so we know which direction to go from here.

**Comment by SoyChai** [comment]
@HelloKitty Personally I left a reaction because I was confused why you thought the copyright notice was immutable, despite this kind of appending being very common in our codebase. The rest of your points are definitely valuable concerns, and I'd love to see you help Shaun understand and address them, but I think the unexpected air of authority may have started us off on the wrong foot.

**Comment by HelloKitty** [comment]
@SoyChai that is a difficult question to answer because it depends on the jurisdiction as I think the EU has some additional protections for rights holders. If you want to consider it from the point of view of U.S. copyright law then refer to [17 U.S. Code § 401](https://www.law.cornell.edu/uscode/text/17/401) which states in part:
> "the name of the owner of copyright in the work, or an abbreviation by which the name can be recognized, or a generally known alternative designation of the owner."

This U.S. code describes essentially what the header of the [BSD 2-Clause License](https://opensource.org/licenses/BSD-2-Clause) for, if you were curious, which is both what this file header is and what the repository is licensed under. Now, contributions under BSD don't require a relinquishment of copyright, like some licenses do (some require some explicit handling of this), so the contributor does retain a copyright to their contribution and diff. However that does not grant them the right to make a modification of the licensing and original copyright terms. Even licensors have difficultly legally changing the license of a work that has contributors to an incompatible license. 

Though with BSD 2 I don't think that is likely to be the case. Either way, while a contributor doesn't have the right to change the license terms the question is if what is done with this commit; if the licensing text has technically changed meaning. Which is odd, because it's only on this single file too. What is the legal meaning or ramifications? Maybe nothing but you'd need to ask a lawyer.

Shuan's copyright of his work is implict too. Assuming he is a country that ratified the Berne Convention at least. So that is yet another reason to not change the text of the license, among others.

Adding additional copyright holder's name, especially if they do not have the same general copyright ownership amount, to the license header leaves things very ambiguous too. That's *NOT* a good thing for when/if Adam ever wishes to use his rights as a copyright holder in some way. This looks to me to potentially erode a claim to those total rights he currently holds.

Copyright is confusing. A lawyer is always needed. Don't even take my word for it partly the reason IANAL expression exists. Though I don't think any legal team that had the interests of the copyright holder in mind would suggest it was a good idea to merge a pull request that modifies the license text and adds a new listed "owner of copyright in the work". Regardless of Shaun's implicit copyright to his contribution/diff.

As for the mention of immutability. The copyright is not technically immutable no, though these changes are very ambiguous on their meaning. Re-licensing a collective work is not so simple as changing the license. Which may be what is occurring with the small change in licensing text of the BSD 2-Clause header here but a lawyer would need to clarify that.

Why would anyone want to open the legal can of worms of doing this when there is no benefit to the rights holder nor would it mean Shaun doesn't have a copyright to the contribution? There are only problems when you start to change licenses or leave ambiguity in copyright. Copyright is serious stuff you have to be careful when not to accidentally erode your rights in some way.

Don't take legal advise from someone named HelloKitty on the internet though. Your rights are important and you should get legal advice. This is a very serious area in opensource software and I'd recommend the repository administrator create a contribution section about copyright/license. For example, [Mono Project](http://www.mono-project.com/community/contributing/) explicitly states your contributions are provided as licensed under a particular license. Now it's MIT but originally was LGPL I think.

Hearing that other people are amending the license header for other files is abit unsettling too. Thankfully only the original license matters, hopefully, but it is unsettling on the legal meaning of these changes sprinkled throughout.

As for helping, that you mentioned, I don't play Runescape, nor use Runelite and I'm not a Java developer. Though I did stop in because this project is important. It sets an important precedence that I hope other companies allow or follow. Developing or allowing the development of a client opensource for their games. Anyway, @devinfrench seemed to do it well enough for the major concern, the predicate. That's the most major thing here.

**Comment by SoyChai** [comment]
Wow, thanks for explaining your thoughts in so much detail. I guess the copyright situation is more complex than most of us want to admit! We'll probably discuss this among ourselves later because it already came up once in our dev conversations, and we left the point unresolved due to lack of research.

**Comment by ShaunDreclin** [comment]
This issue/pr still requires input from @Adam- on [these](https://github.com/runelite/runelite/pull/1653#issuecomment-382954726) questions

**Pull request closed without merging**
