### PR TITLE
clue: Fix spelling in an anagram clue

### PR DESCRIPTION
**Pull request by wayne-li2**
Analyzing emerald000's clue helper commit. It contains a large amount of changes covering many areas.

Begin by merging in this text error they found.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
It looks like the wiki has the text we currently use on <https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Challenge_scrolls>. Can you check with them regarding this typo? This fix makes sense grammatically but it's possible, however unlikely, that this is the text present ingame and is correct despite it not being correct.

**Comment by emerald000** [comment]
The crowdsourced clue texts (https://docs.google.com/spreadsheets/d/1tmSPxJiT3YuCfpezEIS5SAyRaZjBwUaaeAd711bEPKI/edit#gid=0) has `tank`.

**Comment by wayne-li2** [comment]
Good catches -- I've edited the OSRS Wiki to fix the typo.

**Comment by wayne-li2** [comment]
@Nightfirecat I could use a re-review -- I fixed all of the clue step discrepancies (and have updated the Wiki as well).

**Pull request merged**
