### PR TITLE
 hiscore plugin: fix exception on unranked skills

### PR DESCRIPTION
**Pull request by Adam-**

### CODE REVIEW

**Comment by AlexKolpa** [comment]
Duplicate of #3058?

**Comment by Adam-** [comment]
#3058 looks wrong to me because it is still calling getLevelForXp() with negative xp.. which I think is what the original commit was trying to do?

**Comment by AlexKolpa** [comment]
Yes, in which case you're unranked for that specific skill, which returns -1. I checked for that user linked in the issue, and they have `xp=-1` and `rank=-1` for fletching, as expected.

**Comment by Adam-** [comment]
Do you have a stacktrace or something from the original issue?

**Comment by AlexKolpa** [comment]
Unfortunately for some reason the exception gets swallowed (haven't had the chance to check why), however the code flow is somewhat straightforward so I'll try to explain:

It broke for every skill after combat. The reason for that is that RL returns `null` for combat when asking for it as a hiscore skill (see [here](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java#L505)). However if `skill` was null, we still continued, reaching [this line](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java#L465). However we never check for null in that call, which would crash on [this line](https://github.com/runelite/runelite/blob/master/http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreResult.java#L408) then, since you can't put null as an argument into a switch statement.

I'll try to see if I can find out why the exception is being swallowed here as well btw.

**Comment by Adam-** [comment]
This is the original problem:

```
java.lang.IllegalArgumentException: XP (-1) must not be negative
	at net.runelite.api.Experience.getLevelForXp(Experience.java:82)
	at net.runelite.client.plugins.hiscore.HiscorePanel.detailsHtml(HiscorePanel.java:655)
	at net.runelite.client.plugins.hiscore.HiscorePanel.lookup(HiscorePanel.java:489)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlexKolpa** [comment]
Which was fixed in #3035, however that introduced the following NPE (current master):

```
java.lang.NullPointerException: null
	at net.runelite.http.api.hiscore.HiscoreResult.getSkill(HiscoreResult.java:408)
	at net.runelite.client.plugins.hiscore.HiscorePanel.lookup(HiscorePanel.java:468)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Pull request closed without merging**
