### PR TITLE
Add "Actions left" for Xp globes

### PR DESCRIPTION
**Pull request by valmir95**
The Xp globe now has an extra field which displays amount of actions left.

### CODE REVIEW

**Comment by Kamielvf** [comment]
Related: #1030

**Comment by Foulwerp** [comment]
#1352 Would allow implementing all the features from the xp tracker into xp globes way easier, and cut down a lots of duplicate code.

**Comment by Adam-** [comment]
I think the xp tracker and globes are fairly logically different even though they both show mostly the same information. So I don't like #1352 too much. To add actions left to the xp globes, I would add a dependency on the xptracker from the xpglobes plugin, and then use the information from the xptracker in the globes plugin. #1030 does this, but it got a little overzealous and also abandoned.

I would use it as reference. Add `@PluginDependency` and then inject the XpTrackerService into the xp globes plugin.

**Comment by valmir95** [comment]
Added the XpTrackerPlugin as a PluginDependency (as requested). There is some interesting logic that  has been used by the author of the XpTrackerPlugin for calculating which might need some fine-tuning.

**Comment by Adam-** [comment]
This resolves #1655

**Pull request merged**
