### PR TITLE
Fix KBD respawn timer

### PR DESCRIPTION
**Pull request by MagicfTail**
Timed using NPC tagger

### CODE REVIEW

**Comment by deathbeam** [comment]
But wiki says its ten 🤔

**Comment by MagicfTail** [comment]
Then the wiki is wrong since the npc tagger is supposed to be tick perfect 🤷‍♂️

**Comment by ShaunDreclin** [comment]
You sure it said 9 and not 9.9?

**Comment by MagicfTail** [comment]
Yes, because i made it log the time and npc when starting a new timer. I should probably pr that since it's really useful

**Comment by ShaunDreclin** [comment]
Oh, yea that sounds useful ;o I'll go update the wiki

**Comment by MagicfTail** [comment]
https://i.imgur.com/fyfIYBw.png

**Comment by ShaunDreclin** [comment]
>https://i.imgur.com/fyfIYBw.png

dountdown

**Comment by deathbeam** [comment]
Alright now wiki says 9 so i guess its ok :p

**Pull request merged**
