### PR TITLE
Add barbarian potions to Item Stats plugin

### LINKED ISSUE #12873: Add obscure items to item stats
**Is your feature request related to a problem? Please describe.**
the "Item Stats" plugin is missing a few niche consumable items, such as [Cooked mystery meat](https://oldschool.runescape.wiki/w/Cooked_mystery_meat), and [Barbarian potions](https://oldschool.runescape.wiki/w/Barbarian_Training#Barbarian_Herblore). 

**Describe the solution you'd like**
I want to submit a PR that adds these item to the item stats plugin. I think this is as simple as adding some lines to the `net.runelite.client.plugins.itemstats.ItemStatChanges.java` file.

### PR DESCRIPTION
**Pull request by maxbla**
fixes #12873 

~Has one known bug - super restore mix tooltip doesn't properly show healed hitpoints. I'll work on this before merging, but I want to avoid creating a new `SuperRestoreMix` class.~ Fixed

### CODE REVIEW

**Comment by maxbla** [comment]
ready for review

**Comment by Hydrox6** [comment]
Pro tip: if you're going to submit a PR yourself, you don't need to make an issue first; just explain the reasoning in the PR post

**Comment by Nightfirecat** [comment]
This does not work properly as mixed potions apply the fixed health gain (+3 or +6 depending on the potion) prior to applying the potion's effect. Hence, this will return incorrect values for zamorak mixes whenever you are at most 5 hitpoints below your max hitpoints value. e.g. If you are 91/91 hitpoints, a zamorak mix will give the same boost as a zamorak brew--this PR would indicate it would give -4 hitpoints rather than the expected -10.

**Comment by maxbla** [comment]
closing in favor of #4036

**Pull request closed without merging**
