### PR TITLE
Do not filter messages from yourself, friends, or clan members when using chat filter plugin.

### PR DESCRIPTION
**Pull request by dmeredith96**
Fixes issue #8282. No longer filters messages from yourself, clan members, or friends. 

Not a huge fan of how the unit testing is mocked, maybe I should make a separate method for checking local player? Tests are passing, though.

### CODE REVIEW

**Comment by Hydrox6** [comment]
There should be an option to let the filter still affect yourself, friends, and clanmates

**Comment by MagicfTail** [comment]
This won't work for the chat, only the overhead

**Comment by deathbeam** [comment]
Also this works only for overheads and not for chat messages. it should work for both

**Comment by psikoi** [comment]
@Nightfirecat #8775 was merged and references this (and apparently does the same thing), I assume this is a dupe and should be closed?

**Pull request closed without merging**
