### PR TITLE
Change default examine chat color to green

### PR DESCRIPTION
**Pull request by ltvill**
For better visibility.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Can you get screenshots comparing the change to the current code on the various chat backgrounds?

**Comment by ltvill** [comment]
Can’t do that right now, sorry. It’s worse on the transparent chatbox.

**Comment by ltvill** [comment]
image

image

**Comment by devLotto** [comment]
It should only change the colors for the transparent backgrounds, green is hard to read on the opaque one:

image

**Comment by devLotto** [comment]
I have updated your pull request.

**Pull request merged**
