### PR TITLE
Show username in window title

### LINKED ISSUE #1918: Display username as part of the window title
This would help identify different RuneLite instances in streaming apps, and also in the taskbar / dock. An option to choose between appending and prepending the text would be valuable.

### PR DESCRIPTION
**Pull request by rherms**
Fixes #1918 

CC @SoyChai

### CODE REVIEW

**Comment by SoyChai** [comment]
I actually had no idea that you could cast Applet to Client here, how did you figure that one out?

**Comment by rherms** [comment]
I saw it was already being done in RuneLite.java line 156.

**Comment by SoyChai** [comment]
Oh duh, on second glance it's actually used this way all throughout ClientUI. I guess the field name is a big hint. I'll tag you in my own pull so we can take notes off each other.

**Comment by rherms** [comment]
closing in favor of #1952

**Pull request closed without merging**
