### PR TITLE
Option to only show Player Indicators for attackable players

### PR DESCRIPTION
**Pull request by ingokuba**
I don't know whether this is against the third party client rules but it helps doing activities in the wilderness. Let me know of any possible improvements.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
It's not spelled out in [the Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1), but we do include it in our [Rejected or Rolled Back Features wiki page](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features):

> **Not currently being considered**
> Level-based PvP player indicators (eg. highlighting players who can be attacked, or are within X levels range)

**Comment by ingokuba** [comment]
Thanks! Understandable... is it morally acceptable to add this with a plugin hub plugin?

**Comment by Nightfirecat** [comment]
The rules apply to hub plugins the same as changes to the core client, so no.

**Comment by ingokuba** [comment]
Hey, don't act like you edited your comment :wink: 
I will not publish this of course - just want to live in peace with my ironman

**Pull request closed without merging**
