### PR TITLE
Add Leather hide shields to crafting calculator #4326

### LINKED ISSUE #4326: Add Leather hide shields to crafting calculator
Leather hide shields don't appear in the crafting skilling calculator.

### PR DESCRIPTION
**Pull request by ryancatlin**
Added Hard Leather Shield & Snakeskin Shield to crafting skill calculator

Fixes #4326

### CODE REVIEW

**Comment by Nightfirecat** [comment]
FYI, you can just push your changes to a PR'd branch to update it instead of closing and opening the PR from another branch.

**Comment by ryancatlin** [comment]
@Nightfirecat thanks for letting me know

**Comment by delps1001** [comment]
Isn't this still missing green - black dragonhide shields as well?

**Comment by ryancatlin** [comment]
Added the D'hide Shields

**Comment by raiyni** [comment]
merged in https://github.com/runelite/runelite/commit/f526ba1f7f8d9021f581eec04090cc4c769c9f8e

**Pull request closed without merging**
