### PR TITLE
gpu: fix major visual glitches on linux

### PR DESCRIPTION
**Pull request by Hydrox6**
Putting this if statement behind `localId < size` causes major visual
glitches with the Mesa graphics driver.

### CODE REVIEW

**Comment by tmewett** [comment]
Unfortunately, this doesn't seem to fix things for me:

image

**Comment by tmewett** [comment]
I can confirm this PR fixes the issue on my settings:

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD Radeon R7 200 Series (BONAIRE, DRM 3.35.0, 5.4.36-1-MANJARO, LLVM 10.0.0) (0x6658)
    Version: 20.0.6
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

Very odd bug, I should have believed you at first!

**Comment by tmewett** [comment]
I should add that the branch crashed on launch for me, but worked after I first rebased it onto current master 4b4720751c6845d11219ac6d3351b8377464e98b.

**Comment by dekvall** [comment]
This fixes the issue for me too.
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD OLAND (DRM 2.50.0, 5.3.0-55-generic, LLVM 9.0.0) (0x6610)
    Version: 19.2.8
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

**Comment by biggggs** [comment]
This also fixed my gpu issues

Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD Radeon VII (VEGA20, DRM 3.37.0, 5.7.0-3-MANJARO, LLVM 10.0.0) (0x66af)
    Version: 20.0.7
    Accelerated: yes
    Video memory: 16384MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

**Pull request merged**
