### PR TITLE
Improvements to ChatboxItemSearch

### PR DESCRIPTION
**Pull request by YeahImRose**
Current goals:

- [X] - Allow extra rows of items to be displayed
- [X] - Allow keyboard navigation of extra rows
- [x] - Allow mouse wheel scrolling

### CODE REVIEW

**Comment by YeahImRose** [comment]
All my initial goals on this are done. My only hangups are as follow:

- I'm unsure if the scroll bar visible in the normal chat menu should be added (don't want to make design choices when I don't know the systems that well)
- I'm unsure on the MAX_RESULTS value. It seems fine to me at 120, but I don't know if we want it lower or higher or customizable per instance of the class

Otherwise all good for me!

**Comment by raiyni** [comment]
This should be trying to build scrollbars like any other jagex interface probably.

**Comment by YeahImRose** [comment]
> This should be trying to build scrollbars like any other jagex interface probably.

Probably, but that's why I was kinda doubting haha. Do you (or anyone else) happen to have any examples of a scrollbar actually being implemented in a widget? I see RuneLiteScrollBarUI, but I don't see any uses of it, and haven't been able to find any other examples of a plugin or something using the Jagex-style scrollbar.

**Comment by raiyni** [comment]
I believe it would just take calling the `[proc,scrollbar_vertical]`  script with the right parameters

**Comment by raiyni** [comment]
I liked the idea of reusing the GE item search for this, there's more to look into for it but I think I like it.


https://github.com/user-attachments/assets/7f7d238e-8f2e-455d-8220-995660387aab

**Comment by YeahImRose** [comment]
I really do like the way that one looks. I've kinda been running up against a brick wall trying to get the scrollbar to apply to a widget that isn't a layer. Not sure if it's even possible to be honest, because every message I've read in the discord about it makes me think it's not.

**Comment by raiyni** [comment]
I believe https://github.com/raiyni/runelite/commits/gelike-search/ covers all usage

**Comment by YeahImRose** [comment]
> I believe https://github.com/raiyni/runelite/commits/gelike-search/ covers all usage

Unfortunately, implementing it that way prevents use cases where you want non-GE items, which was possible with the old implementation
image

**Comment by raiyni** [comment]
It supports non-tradable items just fine


https://github.com/user-attachments/assets/fc887d4c-dfc7-463c-b8cf-41ffaf81994b

**Comment by YeahImRose** [comment]
Using the exact same plugin code which made my earlier screenshot, just swapping in your version of ChatboxItemSearch does not include the same results. This is what I'm talking about
image

**Comment by raiyni** [comment]
looks fine for me except collapsing the same item models, maybe try just building my branch directly as I don't know what you copy and pasted

image

**Comment by YeahImRose** [comment]
Ah yep, building straight from yours does work! I'd be a-ok with it. Should I just close this and you open another PR or is there a way to merge yours in easily?

**Comment by YeahImRose** [comment]
Ah yeah, seems like there's no way to change source. I'll just close this and let you make another https://stackoverflow.com/a/42381583

**Pull request closed without merging**
