### PR TITLE
Remove the dotted line on JButtons when clicked

### PR DESCRIPTION
**Pull request by HexRealm**
This is a simple aesthetic change to JButtons to remove the dotted line when the user clicks them. 

Before - https://i.imgur.com/AWsbmex.gifv
After  - https://i.imgur.com/ZFejGG2.gifv

### CODE REVIEW

**Comment by SoyChai** [comment]
Ahh thank you, this is a pretty ugly effect. Wish it wasn't so popular in UI design.

**Comment by jplsek** [comment]
I don't think it should be outright removed. This breaks for people who only use the keyboard for actions. For example, in the current client, from the plugin panel, you can keep pressing tab to select the buttons for each plugin (start from the search bar). With this change, you can no longer select any button if only using the keyboard. A more common example is if you go to a plugin like the Agility plugin, click the text input, and press tab, it will skip the overlay color because it's not focusable.

Adding a somewhat transparent underline (like hyperlinks), or highlighting the background a different color, or putting a border around (like bootstrap) would be a better approach IMO.

**Comment by SoyChai** [comment]
Is there a way to preserve the keyboard navigation cursor when it's needed, but not summon that cursor after a mouse hover?

**Comment by Kamielvf** [comment]
No, because that line indicates the button being focussed

**Comment by SoyChai** [comment]
Hm, then we'll need to consider if it's okay to remove keyboard support from the plugins list of an extremely mouse-heavy game.

**Comment by SomeoneWithAnInternetConnection** [comment]
The sidebar is going to steal focus whether or not we hide the focus indicators. Hiding the focus indicators will just make it more confusing when you start typing your message into the hiscore lookup or whatever

**Comment by deathbeam** [comment]
Closing as this is very old PR now and has a lot of merge conflicts, reopen if you want to re-implement it.

**Pull request closed without merging**
