### PR TITLE
Reorder time tracker tabs by priority

### PR DESCRIPTION
**Pull request by deathbeam**
Timers -> Birdhouses -> Herbs -> Trees -> Special (for seaweed) ->
Flowers (because of recent buff) -> Bushes (whiteberries) -> Grapes
(wine of zammy?) -> Hops

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Abextm** [comment]
What was this supposed to fix?

**Comment by deathbeam** [comment]
This was not bug, just quite a few people were complaining about order of the tabs, and tbh it didnt made much sense to me as well, so I ordered it mostly by how often are the farming tabs used after some discussion on Discord.

**Comment by Abextm** [comment]
I would like to not mess with people's muscle memory for this

**Comment by deathbeam** [comment]
I doubt that will be the case, the interface is clear and easy to use, and it will mostly help people in future by not having the less useful and useless stuff as first tabs in the interface.

**Comment by deathbeam** [comment]
Well if people were not complaining about the order in first place this would not be necessary I guess. I personally don't care about it.

**Pull request merged**
