### PR TITLE
Add blurite bar to item identification

### PR DESCRIPTION
**Pull request by Kashif300**
Added blurite bar into item identification

### CODE REVIEW

**Comment by YvesW** [comment]
If you're adding this, you probably also want to add e.g. lunar bar and lovakite bar.

**Comment by Kashif300** [comment]
> If you're adding this, you probably also want to add e.g. lunar bar and lovakite bar.
Done

**Comment by Kashif300** [comment]
@YvesW Hey, do you know what the process is to get this pull request merged? This is my first pull request for a open repository

**Comment by YvesW** [comment]
Just wait patiently for a maintainer to review it.

**Pull request merged**
