### PR TITLE
Add "Kills Left" on the XP Tracker for combat kills

### LINKED ISSUE #1594: Add "Kills Left" on the XP Tracker for combat kills
Right now the combat XP Tracker shows "### Action Left" until a level up.  If the client could be updated with "### Kills Left" for the combat skills that would help out a lot.  Because right now I am 62 ranged, and I look at the XP tracker and it shows "1612 Actions Left" and than a few second later "1323 Actions Left", few seconds after that "1852 Actions Left".  It is not very accurate when it comes to combat skills.

### PR DESCRIPTION
**Pull request by DaanG96**
Replaces "Action left" until a level up with "Kills left". It calculates all the xp you got from the previous monster you fought and based on that, it calculates how many you still have to kill. It can calculate this while using all the styles of melee and ranged (magic calculation would be another thing).

screenshot

Closes #1594

### CODE REVIEW

**Comment by DaanG96** [comment]
@Kamielvf it will check for the enemy you are fighting just like the OpponentInfoOverlay. So if you are chinning, it will select the npc which you are fighting with and calculates the amount of xp you will get from it when you completely kill it from full to 0 hp. 

This will be give the right amount for chinning, but it won't do this for bursting, since this is magic and it doesn't calculate it for magic (because there is no set amount of xp you will get). It also will give a wrong  output with cannon, since there is no way you can predetermine how many kills there are left while the cannon is firing.

**Comment by valmir95** [comment]
How about health regen? NPC's heal every minute I believe, which in the long run (slayer task) might skew the results a bit. Do you call the getHP method every hit or in an interval of less than one minute?

**Comment by DaanG96** [comment]
@valmir95 The calculations will adjust themselves in the same interval the previous implementation did with actions remaining. So switching styles, npc targets and regen will be skewing the results a little bit, but it will recalculate the amount of kills needed almost immediatly.

**Comment by LeviSchuck** [comment]
This will need to rebase now that #1367 has been landed on master.

**Comment by DaanG96** [comment]
@LeviSchuck merged it together

**Comment by Yoone** [comment]
I wanted to make the exact same PR when I downloaded the client yesterday. Well done! Can't wait for it to be merged.

**Pull request closed without merging**
