### PR TITLE
Menu Entry Swapper: add swap Withdraw-1 with Withdraw-X option.

### PR DESCRIPTION
**Pull request by haakonrp**
Add option to swap Withdraw-1 with Withdraw-(x).

Withdraw-1 swap with Withdraw-X:
withdraw-x

User chooses X to be e.g. 14, and Withdraw-1 will swap with Withdraw-14:
withdraw-14

### CODE REVIEW

**Comment by Adam-** [comment]
Duplicate of #1647. We've already decided we don't want to do this as the other clients don't do it.

**Comment by deathbeam** [comment]
I don't think leaving this open for everyone to use is good idea. Reopen when there is demand for this feature, but atm it is rejected. And the original issue this PR is solving was closed too.

**Comment by MarkEGibbons** [comment]
I cannot stress how much I support this and I truly hope this feature comes sooner rather than later.

**Comment by deathbeam** [comment]
It was implemented on desktop by Jagex long time ago?

**Comment by Hydrox6** [comment]
image

Click the X

**Pull request closed without merging**
