### PR TITLE
Add option to disable system tray icon

### LINKED ISSUE #14443: Option to remove/hide menu bar Runelite icon. [ Mac ]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Its wasted space. All it does is open Runelite when I can just use my mouse shortcuts instead or go down to the dock in the same amount of time. 👎 
I have a 2021 Mac M1 Pro and I have a notch on this computer and its pretty close to being behind the notch I would absoulutly love more real-estate with the icon removed! 

**Describe the solution you'd like**
Option to remove menu bar icon with Command+Mouse Button 1 (Dragging off screen) 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Add a setting to remove it in the built in 'Runelite' setting

**Additional context**
I am uploading a quick little screen recording of what the problem is:

https://user-images.githubusercontent.com/28886725/144695847-9ca4f003-5aec-4d69-8aee-9d34c0475983.mov

### PR DESCRIPTION
**Pull request by testing-ongithub**
Closes #14443 

Until I saw this issue, I hadn't realized I wasn't the only one that didn't like the icon.

### CODE REVIEW

**Comment by Adam-** [comment]
Removing the tray icon would also silently break tray notifications, which is kind of not nice (there is no feedback about it).

**Comment by testing-ongithub** [comment]
> Removing the tray icon would also silently break tray notifications, which is kind of not nice (there is no feedback about it).

I know. I added a warning for the config saying exactly that.

**Comment by Adam-** [comment]
That seems fine. I would probably place the "Enable tray icon" above the "Enable tray notifications" option since people tend to read top -> bottom and the one is dependent the other.

**Comment by testing-ongithub** [comment]
> I would probably place the "Enable tray icon" above the "Enable tray notifications" option since people tend to read top -> bottom and the one is dependent the other.

Done!

**Pull request merged**
