### PR TITLE
Fix NPC indicators to not consume tags clicks on non-NPCs

### PR DESCRIPTION
**Pull request by Kamielvf**
Fix an issue introduced by #3778 that would prevent the player from clicking the "Tag" option on pillars in the pinball random event.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
That's an oddly specific bug. :+1:

**Comment by Kamielvf** [comment]
Also related: agility arena

**Comment by Adam-** [comment]
Usually when we add our own actions they are of type RUNELITE - can you not just check that?

**Comment by Kamielvf** [comment]
It calls `menuManager.addNpcMenuOption` which loops over the available NPC actions of that npc's composition to look for an empty spot, then fills it with the new action.

On another note, if all options are already taken there won't be a new one added. I'm not sure if there's NPCs that have that many actions (5) but it is likely possible to happen at some point.

**Comment by Alexsuperfly** [comment]
menaphite thugs cant get tagged because of that

**Pull request merged**
