### PR TITLE
Added right click reset xp for xp plugin item

### PR DESCRIPTION
**Pull request by alecsolder**
The main purpose of this was to add the right click reset option to the skill xp tracker. 

There was a current right click option that would launch an external web xp log, but it was difficult to use as it was only available when not clicking on the progress bar (which made up most of the window). So the drop-down is now able to be accessed in the entire skill window.

I also removed the right click reset for the skill icon, as it is confusing behavior that some right clicks open a menu while other ones reset without any prompt.

image

### CODE REVIEW

**Comment by LeviSchuck** [comment]
I thought the click on skill to reset that skill was confusing behavior.

Looks good to me!

**Comment by deathbeam** [comment]
I think both should be kept then in this case, and to solve the right click issue, make the reset on icon apply only when left-clicked.

**Comment by Chayekx** [comment]
is this single xp tracker reset coming on live version anysoon ? i'd love that

**Comment by ypperlig** [comment]
This is in the next version along with the UI redesign

**Comment by deathbeam** [comment]
This was already implemented in the Obsidian redesign.

**Pull request closed without merging**
