### PR TITLE
Kitten hungry idle notifiers

### PR DESCRIPTION
**Pull request by robinwithes**
Added a option in idle notifiers to warn you when your cat is hungry or wants attention.

### CODE REVIEW

**Comment by deathbeam** [comment]
This should probably be in chat notifier, also, you can already use chat notifier for this

**Comment by robinwithes** [comment]
> 
> 
> This should probably be in chat notifier, also, you can already use chat notifier for this

So should i just close it or implement it into chat notifier? I personally think this could be good as a seperate option.

**Comment by deathbeam** [comment]
Probs just move it to chat notifier then

**Comment by Trevor159** [comment]
This should be closed because it can already be done in chat notifications.

**Pull request closed without merging**
