### PR TITLE
timers: Wilderness boss timers off by 10 seconds

### PR DESCRIPTION
**Pull request by Hevaroo**
Wilderness boss timers are off since wilderness update

### CODE REVIEW

**Comment by Adam-** [comment]
https://secure.runescape.com/m=news/a=97/undead-pirates-colosseum-changes--more?oldschool=1 this blog says `Reduced respawn timers for most NPCs in the Wilderness (including bosses, but excluding Revenants) to 9 seconds.` which is 15 ticks. Is the blog wrong?

**Comment by Hevaroo** [comment]
> https://secure.runescape.com/m=news/a=97/undead-pirates-colosseum-changes--more?oldschool=1 this blog says `Reduced respawn timers for most NPCs in the Wilderness (including bosses, but excluding Revenants) to 9 seconds.` which is 15 ticks. Is the blog wrong?

Blog post is probably wrong. Respawn time for Spindel seems to be around 5-6 seconds, and not 9 as stated in the blog post.

**Comment by DrJam** [comment]
Might be 9 ticks in that case and they said seconds instead

**Comment by evilgenious448** [comment]
Did 100KC of Chaos fanatic last night and it was around 9 sec. So might be different for demi bosses vs cave bosses?

**Comment by MarniRS** [comment]
Blog stated they changed most of the respawn timers in wildy to 9 seconds but thats not the case in reality.

Link to blog;
[https://secure.runescape.com/m=news/undead-pirates-colosseum-changes--more?oldschool=1#_ga=2.2485048.902770785.1713177428-1711704415.1673028180]

I timed most bosses in wildy and these are the rates i've found (I forgot about crazy arch and chaos fanatic)
These changes are also visible on the wiki now.
The only boss that has a varying spawnrate is spindel which varied between 8-10 ticks so i took the average of 9. The rest are consistent.

artio 11 ticks
callisto 11 ticks 
calvarion 14 ticks
scorpia 14 ticks
spindel 9 ticks 
vetion 15 ticks
venenatis 10 ticks
chaos ele 14 ticks
lava dragon 14 ticks

**Comment by DapperMickie** [comment]
You can add new changes by pushing new commits to your branch that you've created. 
I think there should be a message explaining that on this pull request.

**Pull request merged**
