### PR TITLE
Npc indicator plugin highligh all menu names

### LINKED ISSUE #12671: NPC Inidicators plugin: Highlight menu names does not highlight all options
**Is your feature request related to a problem? Please describe.**
The plugin has a " Highlight menu names" configuration option, but when you toggle it on it only highlights the first menu item.
**Describe the solution you'd like**
Highlight all menu item names hat belong to the tagged npc. I have implemented this and will create a PR shortly after submitting this issue.

**Describe alternatives you've considered**
None, just a fun enhancement of the npc indicator plugin 

**Additional context**
Before picture:
Screenshot 2020-10-19 at 22 56 35

After pictures:
Screenshot 2020-10-19 at 23 05 38
Screenshot 2020-10-19 at 23 04 46

### PR DESCRIPTION
**Pull request by syngfaa**
Close #12671

A small enhancement for the NPC Indicator plugin by highlighting all menu name items instead of only partly when the "Highlight menu names" option is turned on. See #12671 for more details

### CODE REVIEW

**Comment by Nightfirecat** [comment]
In the future, you don't need to create an issue to file a PR against if you already have the code written.

**Comment by syngfaa** [comment]
> In the future, you don't need to create an issue to file a PR against if you already have the code written.

That makes sense, thanks for the heads up!

**Comment by Nightfirecat** [comment]
You need to [format your code to follow our code conventions](https://github.com/runelite/runelite/wiki/Code-Conventions).

**Comment by syngfaa** [comment]
> You need to [format your code to follow our code conventions](https://github.com/runelite/runelite/wiki/Code-Conventions).

done!

**Comment by Nightfirecat** [comment]
[Per my comment on the issue this addresses](https://github.com/runelite/runelite/issues/12671#issuecomment-758431872), we're not looking to make this change.

**Pull request closed without merging**
