### PR TITLE
Zoom fix

### PR DESCRIPTION
**Pull request by MagicfTail**
- Remove now useless outer zoom limit expansion
- Change exponent to make zoom feel better after extra 'notch' was added
- Put fixed and resizable zoom together since they now use the same scale
- Change script to correctly fetch range
- Fix control zoom

### CODE REVIEW

**Comment by MagicfTail** [comment]
That extra zoom bit was basically nothing, having an option to zoom out that much extra would be a joke

**Comment by Adam-** [comment]
What about a setting for restoring the old zoom limit? There has been several requests for this.

**Comment by Aborts** [comment]
add our own default camera limit 💯💯💯

**Comment by MagicfTail** [comment]
I was going to add that, but I feel like it should be a separate pr since this is focused on fixing stuff, rather than adding new features

**Comment by deathbeam** [comment]
I think making presets or something like someone suggested way before this zoom limit fix would make more sense anyway

**Comment by Aborts** [comment]
i agree with deathbeam 💯

**Pull request merged**
