### PR TITLE
SocketTimeoutException on read

### PR DESCRIPTION
**Pull request by XeonPowder**
#8342

### CODE REVIEW

**Comment by XeonPowder** [comment]
Based on the client logs of linked issue, timeout exception occurs on read call of OkHTTP

**Comment by XeonPowder** [comment]
On the issue linked:

Allowing runelite through firewall fixed their issue: #8342 (kinda)... As it was reported that there still is a ~50% chance that it does not work.

**Comment by Abextm** [comment]
If you have >10 seconds of latency to the servers you will to be able to play they game. Regardless I highly doubt their issue is one of latency, but instead their network/isp not correctly routing packets and/or resolving dns

**Comment by XeonPowder** [comment]
Would https://airbrake.io/languages/java-error-monitoring help?

**Comment by Abextm** [comment]
Not in this case. because the issue is not something we can fix

**Pull request closed without merging**
