### PR TITLE
Added Camdozaal fishing spots to Fishing plugin

### LINKED ISSUE #15501: Default Fishing Plugin Not Displaying Tiles
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Default Fishing plugin is not displaying tile overlays. I have no other plugins installed bar 117 HD, and the issue still shows up even when it's disabled. I've tried reinstalling and deleting the cache and nothing seems to work. Issue is the same as described at https://github.com/runelite/runelite/issues/7750 but is meant to have been patched some time ago. Any ideas?

### Screenshots or videos

WhatsApp Image 2022-08-15 at 1 02 33 AM
Screenshot of OSRS Mobile which displays what behaviour should look like

WhatsApp Image 2022-08-15 at 1 02 39 AM
What is displayed by RuneLite

### RuneLite version

RuneLite version: 1.8.30
Launcher version: 2.4.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9338135/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9338136/launcher.log)

### PR DESCRIPTION
**Pull request by jordan-git**
Added the missing fishing spots from issue #15501. I wasn't certain what labels/IDs to use. This is my first open source pull request so please let me know if I could improve.

Closes #15501 

Camdozaal Tetra:
java_RsqxUoQPar
java_6m2vXUDwDn
java_jgfThuPsx3

Camdozaal Cave Eel:
java_AW06XZ7dXf
java_LFaXefjYHJ

### CODE REVIEW

**Comment by peterforsling** [comment]
Something isn't adding up for me. The WorldPoints you added in the code and the tiles highlighted in your screenshot are not the same. 

The tiles highlighted in red are the WorldPoints in the code you added. The tiles highlighted in yellow are the tiles I found the fishing spots on. I also found a few more spots to add.

Camdozaal South:
camdozaal_south

Camdozaal North:
camdozaal_north

**Comment by Alexsuperfly** [comment]
because thats the point of the icon on the map

**Comment by peterforsling** [comment]
Silly me. Looks like I need to spend more time understanding the source code before I start commenting on other PRs.

**Comment by jordan-git** [comment]
> Silly me. Looks like I need to spend more time understanding the source code before I start commenting on other PRs.

Don't worry it's understandable. During this PR I went through all that. 

It seems that the fishing spots are treated as NPCs that are auto-generated in another file. The NPC IDs correlate to their names, `FISHING_SPOT_10653` and `FISHING_SPOT_10686` so I didn't need to do much for the spots.

Then I had to manually find the fishing spot icon on the world map and overlap them to customize the text, which are the spots you mentioned. A bit tedious, being even slightly off lead to the edges of the icon showing the default text so it was trail and error.

**Pull request merged**
