### PR TITLE
WIP - Improve Look and Feel UI Click Feedback

### PR DESCRIPTION
**Pull request by RubenG123**
Makes the clickable containers in the Info Panel look/feel more like clickable buttons. This is done by changing the color of the container on hover and click, as well as changing the cursor on hover (for links that open a browser).

After:

(the cursor going transparent is just a gyazo recording thing)

### CODE REVIEW

**Comment by RubenG123** [comment]
@psikoi Think I'm done

**Comment by SoyChai** [comment]
Could you show off the changes you made to the click feedback? I can only see the hover effect in these gifs, looks perfect so far.

**Comment by RubenG123** [comment]
Ah, I just realized that I didn't really do that for some of the buttons 😅. I'll try to get to it tomorrow or next day. It's nothing special, just more color changes.

**Comment by psikoi** [comment]
For isolated images like the config cog icon, I wouldn't change the whole label background, I wrote a method in swing utils that returns a darker version of an image, check how I used it on the FeedPanel class in the feed plugin, it'll look better.

**Comment by psikoi** [comment]
You probably shouldn't be having all these commits

**Comment by RubenG123** [comment]
Yeah I definitely pushed way too often, Ill see if I can fix it

**Comment by RubenG123** [comment]
Gonna close this and make a new pr when I am actually done so its more organized

**Comment by Nightfirecat** [comment]
You can just force-push to your branch and re-open once you're ready to have it reviewed. :)

**Pull request closed without merging**
