### PR TITLE
item prices plugin: added hover to show inventory/equipment total GE value

### PR DESCRIPTION
**Pull request by alex-zoltowski**
When hovering over either the inventory or equipment icon, it will display a tooltip with their respective total GE value.

A bit of redundancy with my function - makeTotalValueTooltip()
and the existing function - getItemStackValueText()

Not sure if it should be handled differently or not^^^

Let me know of your thoughts.

Alex

### CODE REVIEW

**Comment by jplsek** [comment]
Would utilizing ContainerCalculation from the bank plugin work? That would help reduce some duplicate code.

**Comment by alex-zoltowski** [comment]
@jplsek Thanks for pointing that out, I think that would work - but the ContainerCalculation class is private... not sure how that should be handled.

**Comment by jplsek** [comment]
Just make it public. It's possible the maintainers will want that moved outside the bank plugin if you use it, but I'll let them decide what should happen.

**Comment by alex-zoltowski** [comment]
@jplsek  When implementing the ContainerCalculation class I realized it didn't account for noted items (because items in bank obviously aren't noted). My changes might be a stretch - but I added a boolean parameter to its function that will check for noted items if it is true.

**Comment by Adam-** [comment]
Generally we don't import things cross-plugin like this. The bool for notes seems fine, you could maybe just not make it a flag since it generally won't get hit since you can't put notes into the bank.

**Comment by alex-zoltowski** [comment]
@Adam- appreciate the feedback. How do you feel about my original change that adds the feature to show inventory/equipment total price when hovering over their respective icons? I can take out my recent cross-plugin changes and just manually calculate it in the item prices plugin. If you think this feature doesn't make much sense, just lemme know and I'll close this request.

**Comment by Adam-** [comment]
I'm not sure if it makes sense or not. You can price check your whole inv already ingame via 2 clicks. Though it doesn't work in combat. I guess if the implementation was clean enough I don't mind.

**Pull request closed without merging**
