### PR TITLE
Added infobox for unaggro calibration

### PR DESCRIPTION
**Pull request by DapperMickie**

### CODE REVIEW

**Comment by Adam-** [comment]
I would prefer to have just the infobox for the uncalibrated message instead of an option between both the infobox and the overlay panel

**Comment by DapperMickie** [comment]
@Adam- Alexsuperfly and ron had a discussion in the discord channel and said that having the infobox only, would still result in people asking why the plugin is not working. That's why I changed it to being optional. As you can see in my "added infobox for calibration" commit, it was exactly like you just said, the infobox only.

**Comment by Adam-** [comment]
I think that it should work like this comment details https://github.com/runelite/runelite/pull/17109#issuecomment-1875960335. As long as you always show the uncalibrated infobox that seems like it would be ok.

**Comment by DapperMickie** [comment]
So reverting back to my previous commit should be fine then?

**Pull request merged**
