### PR TITLE
Correct color picker default location

### LINKED ISSUE #15418: Runelite Color Picker default location is partially off-screen
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Window 10

### Bug description

First noticed with Runelite on my 2nd monitor. I went to lower the opacity on a screen market and noticed the color picker was half on 1 monitor and half on the other. I moved Runelite to the other monitor which dead-ends on the right side and checked again. It was half displayed, and half-off the monitor(exceeding resolution limits). 

### Screenshots or videos

image

### RuneLite version

Runelite Version: 1.8.29
Launcher Version: 2.1.7
Oldschool revision: Rev 207

### Logs

_No response_

### PR DESCRIPTION
**Pull request by MikeMillar**
Fix issue where default color picker displayed off-screen.

Fixes #15418

### CODE REVIEW

**Comment by raiyni** [comment]
This will just make the color picker go off the left side of the screen

**Comment by MikeMillar** [comment]
> This will just make the color picker go off the left side of the screen

All of the color picker settings I've seen are on the right side of the screen, so picker goes off to the right. Are there settings which display on the left side of the screen?

**Comment by MikeMillar** [comment]
Latest commit takes into account the client's current monitor for positioning details and resolves the multi-monitor problem.

**Comment by raiyni** [comment]
added in https://github.com/runelite/runelite/commit/707ab78cdb6da090032c59f72e4ebfbc245126b1

**Pull request closed without merging**
