### PR TITLE
Display Item Prices tooltips in the seed vault

### PR DESCRIPTION
**Pull request by EvanWalden**
Closes https://github.com/runelite/runelite/issues/9693

I was unsure if this warranted a config option, so I didn't included one.

### CODE REVIEW

**Comment by marcsasson** [comment]
What's the status on this? 
And also not sure if it needs a new issue but can we add the search by value option on the seed vault?

**Comment by Hydrox6** [comment]
@marcsasson 
Looks abandoned
And yes, new suggestions would need a new issue. Make sure to check for duplicates first

**Comment by marcsasson** [comment]
@Hydrox6 Thanks for the response. Created https://github.com/runelite/runelite/issues/10313

Also, as for this request, what is needed to pass? I could potentially grab it

**Comment by Hydrox6** [comment]
It would just be minor formatting stuff, and an update to remove the conflicts. I don't think this got looked at when it was originally PR'd though.

**Pull request merged**
