### PR TITLE
Add simple clue scroll instance map

### LINKED ISSUE #3416: add instance map for cord clue scroll like in #1373
add instance map for cord clue scroll like in #1373
Almost everyone that uses clue helper plugin is for cordinates maps/if i have to open a laggy map find the icon on the side of the map and click the big X just to find the spot/no thanks

### PR DESCRIPTION
**Pull request by deathbeam**
## Add instance map service to open map at location

- Add service to instance map plugin that will open map at specified
location
- Use new world map drawer in instance map to draw different regions

## Add support for opening map with location clues

Open world map from location clue:
1. Automatically when clue is first read
2. When "Preview location" on clue is called

Closes #3416
Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview:
peek 2018-05-28 15-13

### CODE REVIEW

**Comment by xpepi** [comment]
https://imgur.com/a/q7s5trt
This is why we need this all those guys above have around 4k+ clues and need a fast way to just see the cords.

**Comment by Nightfirecat** [comment]
I'd personally like instance maps not to open for fairy ring clues. I'll generally always use fairy rings to get there, and the local tile highlighting is sufficient for those.

**Comment by deathbeam** [comment]
Yeah, there is toggle for opening map automatically and i made it disabled by default.

**Comment by xpepi** [comment]
Can this be reviewed/merged??

**Comment by deathbeam** [comment]
the xtea api is down and world map received another bunch of enhancements, + @Abextm was working on some optimizations for official one, and I am mostly tired of updating this PR :d

**Pull request closed without merging**
