### PR TITLE
added solution to ACE MATCH ELM", "Cam The Camel"

### PR DESCRIPTION
**Pull request by merlindima**
added the solution "6" to clue step for ACE MATCH ELM

### CODE REVIEW

**Comment by Abextm** [comment]
Are you 100% sure this is correct? The wiki says this should be a puzzle box.

**Comment by merlindima** [comment]
you are right this is for MACHETE CLAM

**Comment by merlindima** [comment]
wrong title

**Comment by Kamielvf** [comment]
Cam is the solution to the hard anagram clue: ACE MATCH ELM. She will ask you to complete a Puzzle box.

She is also the solution to the elite anagram clue: MACHETE CLAM. The solution to the elite anagram clue is 6.

**Pull request closed without merging**
