### PR TITLE
Remove discord tag from party member name

### PR DESCRIPTION
**Pull request by TheStonedTurtle**

### CODE REVIEW

**Comment by forsco** [comment]
That`s all good and well if you need the unique identifier for the plugin to function, but that portion doesn't need to be displayed on the overlays. Especially for longer names that span outside of the overlay box and rather than truncating the string removing the `#0000` seems better suited.

**Comment by deathbeam** [comment]
It does, because you can have 2 different people with same name in party.

**Comment by forsco** [comment]
Then we go with the in game name PR and update it to not remove the required data for the plugin to function and just change the rendered string on the overlay.

**Comment by deathbeam** [comment]
As I said, this is bad idea

**Pull request closed without merging**
