### PR TITLE
Add check to enable fullscreen only when available

### LINKED ISSUE #3523: Full screen mode not working when losing focus/on mac
when in full screen doing ALT + TAB to switch from window and then back to runelite the full screen mode gets bugged which is only fixable by price checking an item in your inventory or by player lookup 

https://github.com/runelite/runelite/pull/3521

some players are not getting full screen at all as shown bellow

Draconyte - Today at 3:07 PM
http://prntscr.com/jp0wt6 this is what happened when i switched to fixed mode LUL
Lightshot
Screenshot

LUL http://prntscr.com/jp0wcm this is using fullscreen mode in "Runelite" settings on expanded window
Lightshot
Screenshot

^^^^^^ user above has the discord code: Draconyte#0019

### LINKED ISSUE #3540: Add a button to hide all chrome so the window is completely static (demo inside)
If I could get the game to have no border in conjunction with the new integer scaling mode while all desktop crap is hidden, I could finally achieve a 100% perfect "fullscreen experience" with the fixed mode.

zxerochrome

### PR DESCRIPTION
**Pull request by deathbeam**
- On some devices, the "true" fullscreen might cause issues, this checks
if the fullscreen is properly supported before enabling it.
- Set the dimensions of the frame based on screen dimensions
- Prevent modifying window size more
- Move the OSX fullscreen setting
- Do not undecorate OSX window, instead use native fullscreen
- On windows, use just fullscreen undecorated window
- As there is no easy way to exit fullscreen, add exit button to sidebar
in fullscreen.
- Merge fullscreen mode flag with custom window chrome flag and make it
enum dropdown
- Remove check for title pane present because it is still present even
if title pane is hidden, so it is useless check
- Make NATIVE_WINDOW default because custom window chrome has too many
bugs

Closes #3523 and closes #3540 

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Abextm** [comment]
I feel like fullscreen should be implemented in a borderless window approach as we get nothing useful from taking exclusive control of the display

**Comment by deathbeam** [comment]
We do, because it actually works also on linux, where the only borderless option does not. I can probably disable the exclusive fullscreen for windows as there it does not matter, I guess.

**Comment by deathbeam** [comment]
Updated the PR with undecorated window approach for Windows

**Comment by Abextm** [comment]
This is now working for me, on windows. I still think it needs a safe mode command line argument on other platforms, because turning it off is difficult otherwise

**Comment by deathbeam** [comment]
Uhh, I dont see exit button in your sidebars screenshot. Is that really this branch.

**Comment by deathbeam** [comment]
Oh, that was typo, I accidentally undecorated native window.

**Pull request closed without merging**
