### PR TITLE
Hotkey to remove all option but "Walk here" 

### PR DESCRIPTION
**Pull request by Reasel**
This will allow the user to select a hotkey that when pressed will remove all other options from a menu except for "Walk Here". This will not remove anything if the "Walk Here" option is not present.

### CODE REVIEW

**Comment by Jalopyy** [comment]
God bless for working on my suggestion :pray:

**Comment by Jalopyy** [comment]
Any update on this? I need it for bossing :thinking:

**Comment by Reasel** [comment]
Its pretty much done, just waiting on review and approval.

**Comment by Reasel** [comment]
Will submit new PR later

**Pull request closed without merging**
