### PR TITLE
Add !layout command to Chambers of Xeric plugin

### PR DESCRIPTION
**Pull request by deathbeam**
Add support for !layout command to raids plugin that will stream current
raid layout to everyone who will see the message.

The code for displaying the chat message is partially from #3919 and from #2992 so thanks for the work done in those PRs.

Depends on #4698

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Closes #4354 
Closes #3919 
Closes #2992

screenie

### CODE REVIEW

**Comment by MagicfTail** [comment]
!layout would probably be a more descriptive command name

**Comment by Matsyir** [comment]
I'd like to point out that I would still like to have the option of an automatic message on start from #3919 however at this point it would be a very negligible change, this will do the trick albeit not automatically. For team raids this will be very useful though.

**Comment by deathbeam** [comment]
Changed this PR to depend on #4698, what removes any duplicate code here from ChatCommandsPlugin

**Comment by deathbeam** [comment]
Closing this as it needs @Adam- 's review and idk if he even likes it, and I am not going to maintain this forever

**Pull request closed without merging**
